### ISSUE TITLE
Build piplelines are failing - "No service hubot  is running"

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1042]
Steps to recreate - with https://openshift.io
* Create new space
* Create new quickstart project
* Observe the build pipeline failing:

![screenshot from 2017-09-29 12-21-50](https://user-images.githubusercontent.com/642621/31025718-9edff960-a511-11e7-834a-25f019514467.png)

![screenshot from 2017-09-29 12-26-58](https://user-images.githubusercontent.com/642621/31025722-a74b3bb4-a511-11e7-8427-921afdea7899.png)

```

Timeout set to expire in 1 day 0 hr
[Pipeline] {
[Pipeline] hubotApprove
Hubot sending to room fabric8_default => Would you like to promote version 1.0.1 to the next environment?

    to Proceed reply:  fabric8 jenkins proceed job osiotestmachine/testsep291506701845933/master build 1
    to Abort reply:    fabric8 jenkins abort job osiotestmachine/testsep291506701845933/master build 1

No service hubot  is running!!!
No service found!
[Pipeline] approveRequestedEvent
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

groovy.lang.MissingPropertyException: No such property: id for class: approve
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:284)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:316)
```

**Comment by ldimaggi** [comment]
Build log attached
[build_log.txt](https://github.com/openshiftio/openshift.io/files/1345026/build_log.txt)

**Comment by rawlingsj** [comment]
Should be fixed now.
