### ISSUE TITLE
Forge errors showing up repeatedly when creating new project

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1043]
Starting see this late on Oct 1 - when creating new quickstart project:
![screenshot from 2017-10-01 23-06-41](https://user-images.githubusercontent.com/642621/31063047-ae5bd56a-a6fd-11e7-900e-62d0a4e1afb5.png)

Not seeing any issues in Jenkins log - see attached.
[jenkins_log.txt](https://github.com/openshiftio/openshift.io/files/1347798/jenkins_log.txt)

**Comment by corinnekrych** [comment]
@ldimaggi @jstrachan The error returned by the REST endpoint for execute on quickstart is:
https://gist.github.com/corinnekrych/fd30160ff2a35d9d8b219a756010d506 
The failure happens in`CreateBuildConfigStep` bc of missing class in classpath. 
@jstrachan Any new deployment version bump that occurs recently?

**Comment by jstrachan** [comment]
nothing's changed in a while - the pods have been running for 10 days now.

I saw this in one pod:
```
2017-10-02 06:43:11,202 SEVERE [org.obsidiantoaster.generator.rest.ObsidianResource] (default task-54) Could not register resource monitor: java.lang.IllegalStateException: Could not register resource monitor
	at org.jboss.forge.addon.resource.monitor.FileMonitor.registerMonitor(FileMonitor.java:107)
	at sun.reflect.GeneratedMethodAccessor578.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.resource.monitor.FileMonitor_$$_javassist_7014d415-edfe-4d66-9076-2ec15f4b18a2.registerMonitor(FileMonitor_$$_javassist_7014d415-edfe-4d66-9076-2ec15f4b18a2.java)
	at org.jboss.forge.addon.resource.ResourceFactoryImpl.monitor(ResourceFactoryImpl.java:98)
	at org.jboss.forge.addon.resource.ResourceFactoryImpl.monitor(ResourceFactoryImpl.java:84)
	at org.jboss.forge.addon.resource.AbstractFileResource.monitor(AbstractFileResource.java:339)
	at org.jboss.forge.addon.projects.impl.ProjectFactoryImpl.cacheProject(ProjectFactoryImpl.java:387)
	at org.jboss.forge.addon.projects.impl.ProjectFactoryImpl.findProjectInDirectory(ProjectFactoryImpl.java:219)
	at org.jboss.forge.addon.projects.impl.ProjectFactoryImpl.findProject(ProjectFactoryImpl.java:120)
	at org.jboss.forge.addon.projects.impl.ProjectFactoryImpl.findProject(ProjectFactoryImpl.java:97)
	at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.projects.impl.ProjectFactoryImpl_$$_javassist_fcad3a2d-33fe-443b-958c-a1bd3c9efe50.findProject(ProjectFactoryImpl_$$_javassist_fcad3a2d-33fe-443b-958c-a1bd3c9efe50.java)
	at org.jboss.forge.addon.projects.Projects.getSelectedProject(Projects.java:39)
	at org.jboss.forge.addon.projects.Projects.getSelectedProject(Projects.java:26)
	at io.fabric8.forge.generator.pipeline.AbstractDevToolsCommand.getCurrentSelectedProject(AbstractDevToolsCommand.java:96)
	at io.fabric8.forge.generator.pipeline.AbstractDevToolsCommand.getProjectName(AbstractDevToolsCommand.java:70)
	at io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep.execute(CreateBuildConfigStep.java:206)
	at sun.reflect.GeneratedMethodAccessor659.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep_$$_javassist_559efd1f-a5c5-4c66-85f5-4ad04ec8338e.execute(CreateBuildConfigStep_$$_javassist_559efd1f-a5c5-4c66-85f5-4ad04ec8338e.java)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:161)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:157)
	at sun.reflect.GeneratedMethodAccessor654.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_669a2d6f-980f-4ff4-90ea-4475fbd6df50.execute(CommandController_$$_javassist_669a2d6f-980f-4ff4-90ea-4475fbd6df50.java)
	at org.obsidiantoaster.generator.rest.ObsidianResource.executeCommandJson(ObsidianResource.java:483)
	at org.obsidiantoaster.generator.rest.ObsidianResource$Proxy$_$$_WeldClientProxy.executeCommandJson(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor653.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:62)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: User limit of inotify watches reached
	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)
	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
	... 1 more
```
looks like something swarm related maybe. I don't have karma to bounce pods so lemme try trigger a redeploy to see if restarting the pods helps

**Comment by ldimaggi** [comment]
Closing - it's OK now
