### ISSUE TITLE
Backend pod deployment failing

### ISSUE THREAD

**Issue by debianmaster** [openshiftio/openshift.io#1149]
> launchpad-backend  pod logs   $subject
```

2017-10-18 09:16:28,700 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Swarm 2017.10.0 (WildFly Core 2.2.1.Final) started (with errors) in 2493ms - Started 85 of 96 services (1 services failed or missing dependencies, 18 services are lazy, passive or on-demand)
--
  | 2017-10-18 09:16:28,724 ERROR [stderr] (main) java.lang.RuntimeException: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
  | 2017-10-18 09:16:28,724 ERROR [stderr] (main) 	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:45)
  | 2017-10-18 09:16:28,725 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.bootstrap(ServerBootstrapImpl.java:114)
  | 2017-10-18 09:16:28,725 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.start(Swarm.java:386)
  | 2017-10-18 09:16:28,725 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:720)
  | 2017-10-18 09:16:28,725 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | 2017-10-18 09:16:28,725 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | 2017-10-18 09:16:28,725 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | 2017-10-18 09:16:28,725 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:498)
  | 2017-10-18 09:16:28,726 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:54)
  | 2017-10-18 09:16:28,726 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.run(Main.java:133)
  | 2017-10-18 09:16:28,726 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:86)
  | 2017-10-18 09:16:28,726 ERROR [stderr] (main) Caused by: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
  | 2017-10-18 09:16:28,726 ERROR [stderr] (main) 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:153)
  | 2017-10-18 09:16:28,726 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
  | 2017-10-18 09:16:28,726 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
  | 2017-10-18 09:16:28,727 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | 2017-10-18 09:16:28,727 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | 2017-10-18 09:16:28,727 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:748)
  | 2017-10-18 09:16:28,727 ERROR [stderr] (main) Caused by: java.net.SocketException: Protocol family unavailable
  | 2017-10-18 09:16:28,727 ERROR [stderr] (main) 	at sun.nio.ch.Net.bind0(Native Method)
  | 2017-10-18 09:16:28,728 ERROR [stderr] (main) 	at sun.nio.ch.Net.bind(Net.java:433)
  | 2017-10-18 09:16:28,728 ERROR [stderr] (main) 	at sun.nio.ch.Net.bind(Net.java:425)
  | 2017-10-18 09:16:28,728 ERROR [stderr] (main) 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
  | 2017-10-18 09:16:28,728 ERROR [stderr] (main) 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
  | 2017-10-18 09:16:28,728 ERROR [stderr] (main) 	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:171)
  | 2017-10-18 09:16:28,729 ERROR [stderr] (main) 	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:245)
  | 2017-10-18 09:16:28,729 ERROR [stderr] (main) 	at org.wildfly.extension.undertow.HttpListenerService.startListening(HttpListenerService.java:126)
  | 2017-10-18 09:16:28,729 ERROR [stderr] (main) 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:142)
  | 2017-10-18 09:16:28,729 ERROR [stderr] (main) 	... 5 more
  | 2017-10-18 09:16:28,729 ERROR [stderr] (main) java.lang.reflect.InvocationTargetException
  | 2017-10-18 09:16:28,730 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | 2017-10-18 09:16:28,730 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | 2017-10-18 09:16:28,730 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | 2017-10-18 09:16:28,730 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:498)
  | 2017-10-18 09:16:28,730 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:54)
  | 2017-10-18 09:16:28,730 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.run(Main.java:133)
  | 2017-10-18 09:16:28,730 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:86)
  | 2017-10-18 09:16:28,731 ERROR [stderr] (main) Caused by: java.lang.RuntimeException: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
  | 2017-10-18 09:16:28,731 ERROR [stderr] (main) 	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:45)
  | 2017-10-18 09:16:28,731 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.bootstrap(ServerBootstrapImpl.java:114)
  | 2017-10-18 09:16:28,731 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.start(Swarm.java:386)
  | 2017-10-18 09:16:28,732 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:720)
  | 2017-10-18 09:16:28,732 ERROR [stderr] (main) 	... 7 more
  | 2017-10-18 09:16:28,732 ERROR [stderr] (main) Caused by: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
  | 2017-10-18 09:16:28,733 ERROR [stderr] (main) 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:153)
  | 2017-10-18 09:16:28,733 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
  | 2017-10-18 09:16:28,733 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
  | 2017-10-18 09:16:28,733 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | 2017-10-18 09:16:28,733 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | 2017-10-18 09:16:28,733 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:748)
  | 2017-10-18 09:16:28,734 ERROR [stderr] (main) Caused by: java.net.SocketException: Protocol family unavailable
  | 2017-10-18 09:16:28,734 ERROR [stderr] (main) 	at sun.nio.ch.Net.bind0(Native Method)
  | 2017-10-18 09:16:28,734 ERROR [stderr] (main) 	at sun.nio.ch.Net.bind(Net.java:433)
  | 2017-10-18 09:16:28,734 ERROR [stderr] (main) 	at sun.nio.ch.Net.bind(Net.java:425)
  | 2017-10-18 09:16:28,734 ERROR [stderr] (main) 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
  | 2017-10-18 09:16:28,734 ERROR [stderr] (main) 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
  | 2017-10-18 09:16:28,735 ERROR [stderr] (main) 	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:171)
  | 2017-10-18 09:16:28,735 ERROR [stderr] (main) 	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:245)
  | 2017-10-18 09:16:28,735 ERROR [stderr] (main) 	at org.wildfly.extension.undertow.HttpListenerService.startListening(HttpListenerService.java:126)
  | 2017-10-18 09:16:28,735 ERROR [stderr] (main) 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:142)
  | 2017-10-18 09:16:28,735 ERROR [stderr] (main) 	... 5 more
  | 2017-10-18 09:16:28,736 ERROR [stderr] (main) Exception in thread "main" java.lang.reflect.InvocationTargetException
  | 2017-10-18 09:16:28,736 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | 2017-10-18 09:16:28,736 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | 2017-10-18 09:16:28,736 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | 2017-10-18 09:16:28,736 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:498)
  | 2017-10-18 09:16:28,736 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:54)
  | 2017-10-18 09:16:28,737 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.run(Main.java:133)
  | 2017-10-18 09:16:28,737 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:86)
  | 2017-10-18 09:16:28,737 ERROR [stderr] (main) Caused by: java.lang.RuntimeException: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
  | 2017-10-18 09:16:28,737 ERROR [stderr] (main) 	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:45)
  | 2017-10-18 09:16:28,737 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.bootstrap(ServerBootstrapImpl.java:114)
  | 2017-10-18 09:16:28,737 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.start(Swarm.java:386)
  | 2017-10-18 09:16:28,737 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:720)
  | 2017-10-18 09:16:28,738 ERROR [stderr] (main) 	... 7 more
  | 2017-10-18 09:16:28,738 ERROR [stderr] (main) Caused by: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
  | 2017-10-18 09:16:28,738 ERROR [stderr] (main) 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:153)
  | 2017-10-18 09:16:28,738 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
  | 2017-10-18 09:16:28,738 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
  | 2017-10-18 09:16:28,739 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | 2017-10-18 09:16:28,739 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | 2017-10-18 09:16:28,739 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:748)
  | 2017-10-18 09:16:28,739 ERROR [stderr] (main) Caused by: java.net.SocketException: Protocol family unavailable
  | 2017-10-18 09:16:28,739 ERROR [stderr] (main) 	at sun.nio.ch.Net.bind0(Native Method)
  | 2017-10-18 09:16:28,739 ERROR [stderr] (main) 	at sun.nio.ch.Net.bind(Net.java:433)
  | 2017-10-18 09:16:28,740 ERROR [stderr] (main) 	at sun.nio.ch.Net.bind(Net.java:425)
  | 2017-10-18 09:16:28,740 ERROR [stderr] (main) 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
  | 2017-10-18 09:16:28,740 ERROR [stderr] (main) 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
  | 2017-10-18 09:16:28,740 ERROR [stderr] (main) 	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:171)
  | 2017-10-18 09:16:28,740 ERROR [stderr] (main) 	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:245)
  | 2017-10-18 09:16:28,740 ERROR [stderr] (main) 	at org.wildfly.extension.undertow.HttpListenerService.startListening(HttpListenerService.java:126)
  | 2017-10-18 09:16:28,740 ERROR [stderr] (main) 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:142)
  | 2017-10-18 09:16:28,741 ERROR [stderr] (main) 	... 5 more

```

**Comment by debianmaster** [comment]
<img width="1279" alt="screen shot 2017-10-18 at 2 21 27 am" src="https://user-images.githubusercontent.com/1439169/31710813-00b682ba-b3ab-11e7-899e-edcd8ff96b1f.png">

**Comment by joshuawilson** [comment]
Please explain in detail how to reproduce.

**Comment by debianmaster** [comment]
i just used template approach to install openshift.io  on   my   `oc cluster up` environment.  and all other services are up except   `launchpad-backend` pod.
I have shared logs in the issue above

**Comment by debianmaster** [comment]
Also tried giving  `privileged` and `anyuid`  to defult service accounts, no luck

**Comment by alexeykazakov** [comment]
@cc: @ALRubinger @gastaldi

**Comment by gastaldi** [comment]
No idea on how to reproduce that. Any ideas @quintesse @edewit ?

**Comment by debianmaster** [comment]
is there a slack for openshift.io ?

**Comment by quintesse** [comment]
@debianmaster  There is the `#1-launch` channel on `obsidian-toaster` on Slack

**Comment by quintesse** [comment]
I've used that template several times without problems, but only with minishift, never with `oc cluster up`. Is that something you could try @debianmaster ?

**Comment by debianmaster** [comment]
i tried on origin 3.7 aplpha version, i will give a try with 3.6 stable

**Comment by debianmaster** [comment]
just tested, this problem is not there on 3.6  minishift, closing

**Comment by joshuawilson** [comment]
@debianmaster for Openshift.io we have our own Mattermost, it is an OSS chat like slack. Free to join at https://chat.openshift.io/developers/
