### ISSUE TITLE
Intermittent issue - Pipeline not created, build log also not created on https://openshift.io

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1194]
Seeing this problem intermittently starting on October 22:

* Create a new space
* Create a new quickstart project 
* Observe that the pipeline is never created:

![screenshot from 2017-10-23 10-18-58](https://user-images.githubusercontent.com/642621/31907426-c8133038-b801-11e7-88c1-41264d03e36f.png)

Observe that quotas are not exceeded:

![screenshot from 2017-10-23 10-20-21](https://user-images.githubusercontent.com/642621/31907452-d7f70574-b801-11e7-904a-8800f99e64c7.png)
![screenshot from 2017-10-23 10-20-05](https://user-images.githubusercontent.com/642621/31907453-d806637a-b801-11e7-92e5-aa18352eab9d.png)

Observe that the pipeline build log is not created.

Observe only the following in the Jenkins pod log:
```
Oct 23, 2017 2:04:11 PM io.fabric8.jenkins.openshiftsync.ConfigMapWatcher$2 call
INFO: Updated job osiotestmachine from ConfigMap NamespaceName{ldimaggi-osiotest1:osiotestmachine} with revision: 655826720
Oct 23, 2017 2:04:11 PM io.fabric8.jenkins.openshiftsync.ConfigMapWatcher maybeScheduleConfigMapJob
INFO: triggered build!
Oct 23, 2017 2:04:11 PM org.jenkinsci.plugins.github.webhook.subscriber.PingGHEventSubscriber onEvent
INFO: PING webhook received from repo <https://github.com/osiotestmachine/testoct231508767394706>!
Oct 23, 2017 2:04:11 PM jenkins.branch.OrganizationFolder$OrganizationScan run
INFO: osiotestmachine #20171023.140411 organization scan action completed: SUCCESS in 0.56 sec
```

Not (yet) reproducible at will.

**Comment by ldimaggi** [comment]
The automated EE tests also encountered this on Oct 23/24

**Comment by ldimaggi** [comment]
This problem is still being seeing frequently.

From the Jenkins pod logs:

When the pipeline is not successful:

```
Nov 23, 2017 1:04:46 AM org.jenkinsci.plugins.github.webhook.subscriber.PingGHEventSubscriber onEvent
INFO: PING webhook received from repo <https://github.com/osiotestmachine/testnov221511399040613>!
Nov 23, 2017 1:04:47 AM jenkins.branch.OrganizationFolder$OrganizationScan run
INFO: osiotestmachine #20171123.010446 organization scan action completed: SUCCESS in 0.69 sec
```

And - when it is successful:
```
Nov 23, 2017 12:15:24 AM org.jenkinsci.plugins.github.webhook.subscriber.PingGHEventSubscriber onEvent
INFO: PING webhook received from repo <https://github.com/osiotestmachine/testnov221511396072208>!
Nov 23, 2017 12:15:24 AM jenkins.branch.OrganizationFolder$OrganizationScan run
INFO: osiotestmachine #20171123.001523 organization scan action completed: SUCCESS in 1.3 sec
Nov 23, 2017 12:15:25 AM io.fabric8.jenkins.openshiftsync.PipelineJobListener buildConfigProjectForJob
INFO: Creating BuildConfigProjectProperty for namespace: ldimaggi-osiotest1 name: testnov221511395690951
Nov 23, 2017 12:15:25 AM io.fabric8.jenkins.openshiftsync.PipelineJobListener upsertWorkflowJob
INFO: Upsert WorkflowJob master to BuildConfig: ldimaggi-osiotest1/testnov221511395690951 in OpenShift
Nov 23, 2017 12:15:25 AM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2 call
INFO: Updated job testnov221511395690951 from BuildConfig NamespaceName{ldimaggi-osiotest1:testnov221511395690951} with revision: 721910757
Nov 23, 2017 12:15:25 AM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: osiotestmachine/testnov221511395690951 #20171123.001524 branch indexing action completed: SUCCESS in 0.61 sec
Nov 23, 2017 12:15:25 AM io.fabric8.jenkins.openshiftsync.PipelineJobListener buildConfigProjectForJob
INFO: Creating BuildConfigProjectProperty for namespace: ldimaggi-osiotest1 name: testnov221511396072208
Nov 23, 2017 12:15:25 AM io.fabric8.jenkins.openshiftsync.PipelineJobListener upsertWorkflowJob
INFO: Upsert WorkflowJob master to BuildConfig: ldimaggi-osiotest1/testnov221511396072208 in OpenShift
Nov 23, 2017 12:15:25 AM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2 call
INFO: Updated job testnov221511396072208 from BuildConfig NamespaceName{ldimaggi-osiotest1:testnov221511396072208} with revision: 721910764
Nov 23, 2017 12:15:25 AM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: osiotestmachine/testnov221511396072208 #20171123.001524 branch indexing action completed: SUCCESS in 0.48 sec
Nov 23, 2017 12:15:29 AM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onStarted
```

**Comment by rajdavies** [comment]
Which environment is this in?  prod, pre-prod or .... ?

**Comment by rawlingsj** [comment]
Also what percentage of runs fail? 
What made an intermittent error that as far as I can tell has only affected the test user be a sev1?
Have there been any reports of real users being affected by this?

**Comment by maxandersen** [comment]
> be a sev1

its marked as sev2-high, not sev1. I think that is fair for an issue that is believe to make the end-2-end test fail often.

**Comment by rawlingsj** [comment]
waiting for info above

**Comment by maxandersen** [comment]
> waiting for info above

afaik the issue itself was opened by normal usage, not the test scenario. Test scenario just reproduced it.

the last info you are awaiting info on is what % of runs fail ?

For that I'll have to relay to @ldimaggi

**Comment by ldimaggi** [comment]
I am seeing this fail about 30-50% of the time - both from manual ("normal use") and automated testing.

**Comment by ldimaggi** [comment]
May have found a root case for this error:  Unexpected exception in CPS VM thread
```

Dec 26, 2017 6:38:10 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
Dec 26, 2017 6:38:10 PM org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService reportProblem
WARNING: Unexpected exception in CPS VM thread: CpsFlowExecution[Owner[osiotestmachine/testdec261514313206144/master/1:osiotestmachine/testdec261514313206144/master #1]]
java.lang.NullPointerException
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.getFirstHead(CpsFlowExecution.java:1188)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onProgramEnd(CpsFlowExecution.java:1034)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:351)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:243)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:231)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```


[jenkins_log.txt](https://github.com/openshiftio/openshift.io/files/1587884/jenkins_log.txt)

**Comment by ldimaggi** [comment]
Moving that new error into a separate issue -

**Comment by qodfathr** [comment]
@ldimaggi status check on this?

**Comment by ldimaggi** [comment]
I think I saw this over the weekend - will run some tests tonite and close it it does not happen - unclear what might have caused or fixed this.

**Comment by ldimaggi** [comment]
Closing this issue - I *think* that this is actually a variation on the bugs related to slow builds.  
* Intermittent slow thruput on prod-preview #1904
* Intermittent long delays (>1 hour) starting build pipeline #1926
