### ISSUE TITLE
Forge generator build fails

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1205]
The build fails since last week.
https://jenkins.cd.test.fabric8.io/job/fabric8io-auto-rel/job/generator-backend/job/master/

**Comment by alexeykazakov** [comment]
The last build finally succeed. Closing.

**Comment by bartoszmajsak** [comment]
I looked at failed builds logs - most of it was due to docker registry error. Do we know what was the issue?

<details>
<summary>Build error</summary>
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.22:push (default) on project generator-backend: Unable to push 'fabric8/generator-backend:1.0.85' from registry '10.15.255.18:80' : received unexpected HTTP status: 500 Internal Server Error -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.22:push (default) on project generator-backend: Unable to push 'fabric8/generator-backend:1.0.85' from registry '10.15.255.18:80' : received unexpected HTTP status: 500 Internal Server Error 
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to push 'fabric8/generator-backend:1.0.85' from registry '10.15.255.18:80' : received unexpected HTTP status: 500 Internal Server Error 
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:226)
	at io.fabric8.maven.plugin.mojo.build.PushMojo.execute(PushMojo.java:101)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: io.fabric8.maven.docker.access.DockerAccessException: Unable to push 'fabric8/generator-backend:1.0.85' from registry '10.15.255.18:80' : received unexpected HTTP status: 500 Internal Server Error 
	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.pushImage(DockerAccessWithHcClient.java:372)
	at io.fabric8.maven.docker.service.RegistryService.pushImages(RegistryService.java:49)
	at io.fabric8.maven.docker.PushMojo.executeInternal(PushMojo.java:38)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:223)
	... 23 more
Caused by: io.fabric8.maven.docker.access.DockerAccessException: received unexpected HTTP status: 500 Internal Server Error 
	at io.fabric8.maven.docker.access.chunked.PullOrPushResponseJsonHandler.throwDockerAccessException(PullOrPushResponseJsonHandler.java:45)
	at io.fabric8.maven.docker.access.chunked.PullOrPushResponseJsonHandler.process(PullOrPushResponseJsonHandler.java:22)
	at io.fabric8.maven.docker.access.chunked.EntityStreamReaderUtil.processJsonStream(EntityStreamReaderUtil.java:26)
	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient$HcChunkedResponseHandlerWrapper.handleResponse(DockerAccessWithHcClient.java:652)
	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate$StatusCodeCheckerResponseHandler.handleResponse(ApacheHttpClientDelegate.java:172)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate.post(ApacheHttpClientDelegate.java:97)
	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.doPushImage(DockerAccessWithHcClient.java:584)
	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.pushImage(DockerAccessWithHcClient.java:370)
	... 26 more
</details>

**Comment by alexeykazakov** [comment]
I don't know what was the reason. cc: @jstrachan @rawlingsj

**Comment by jstrachan** [comment]
the 2006 parsing issues are due to this: https://github.com/fabric8io/kubernetes-model/issues/241 - PR and release on the way shortly...
