### ISSUE TITLE
KeyError in recommender task (KeyError: 'status')

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1213]
Found this in the logs (prod).

```
  | 2017-10-23 19:58:50,507 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[e0291343-728e-478e-b71f-9d1ead9c4564] raised unexpected: KeyError('status',)
  | Traceback (most recent call last):
  | File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
  | R = retval = fun(*args, **kwargs)
  | File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
  | return self.run(*args, **kwargs)
  | File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 170, in run
  | raise self.retry(max_retries=0, exc=exc)
  | File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
  | raise_with_context(exc)
  | File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 115, in run
  | result = task.run(node_args)
  | File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 41, in run
  | result = self.execute(node_args)
  | File "/usr/lib/python3.4/site-packages/f8a_worker/workers/recommender.py", line 875, in execute
  | filtered_comp_packages_graph)
  | File "/usr/lib/python3.4/site-packages/f8a_worker/workers/recommender.py", line 692, in apply_license_filter
  | if la_output['status'] == 'Successful' and la_output['license_filter'] is not None:
  | KeyError: 'status'
```

**Comment by msrb** [comment]
cc @miteshvp
