### ISSUE TITLE
On prod-preview, app deployment to stage failing intermittently

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1216]
Iss https://github.com/openshiftio/openshift.io/issues/1204 described a problem where rollout to run fails due to a quota limit.

It looks like there are related issues. In the case of this issue, the rollout to run was successful, but the rollout to stage, while appearing to be successful, actually failed.

The user was presented with this feedback in the OSIO pipeline UI:
![1](https://user-images.githubusercontent.com/642621/32005777-24ef2d44-b973-11e7-9f5d-f91ae6d81c39.png)

And - the app was deployed successfully to the run environment:
![screenshot from 2017-10-25 10-44-38](https://user-images.githubusercontent.com/642621/32005800-36b8d606-b973-11e7-9177-fcddaa04dc2f.png)

But - the rollout to the stage environment failed:
![screenshot from 2017-10-25 10-44-15](https://user-images.githubusercontent.com/642621/32005825-4724dca6-b973-11e7-8cdc-62b0d4fd022a.png)

```
Oct 25, 2017 2:04:49 PM io.fabric8.kubernetes.api.Controller applyRoute
--
  | INFO: Creating Route ldimaggi-osiotest1-stage:testoct251508940099460 host: null
  | Oct 25, 2017 2:04:49 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
  | INFO: Terminating Kubernetes instance for agent jenkins-slave-wqln2-bcd50
  | Oct 25, 2017 2:04:49 PM jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
  | WARNING: Computer.threadPoolForRemoting [#34] for jenkins-slave-wqln2-bcd50 terminated
  | java.nio.channels.ClosedChannelException
  | at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
  | at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
  | at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
  | at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
  | at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
  | at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
  | at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
  | at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
  | at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
  | at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
  | at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
  | at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
  | at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:311)
  | at hudson.remoting.Channel.close(Channel.java:1304)
  | at hudson.remoting.Channel.close(Channel.java:1272)
  | at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:708)
  | at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:96)
  | at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:626)
  | at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  |  
  | Oct 25, 2017 2:04:49 PM org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution$PodTemplateCallback finished
  | INFO: Removing pod template and deleting pod jenkins-slave-wqln2 from cloud openshift
  | Oct 25, 2017 2:04:50 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
  | INFO: Terminated Kubernetes instance for agent ldimaggi-osiotest1-jenkins/jenkins-slave-wqln2-bcd50
  | Oct 25, 2017 2:04:50 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
  | INFO: Disconnected computer jenkins-slave-wqln2-bcd50
  | EXITCODE   0EXITCODE   0Terminated Kubernetes instance for agent ldimaggi-osiotest1-jenkins/jenkins-slave-wqln2-bcd50
  | Oct 25, 2017 2:04:50 PM org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution$PodTemplateCallback finished
  | WARNING: Failed to delete pod for agent ldimaggi-osiotest1-jenkins/jenkins-slave-wqln2: not found
  | Oct 25, 2017 2:04:50 PM jenkins.branch.WorkspaceLocatorImpl locate
  | WARNING: JENKINS-34564 path sanitization ineffective when using legacy Workspace Root Directory ‘${ITEM_ROOTDIR}/workspace’; switch to ${JENKINS_HOME}/workspace/${ITEM_FULLNAME} as in JENKINS-8446 / JENKINS-21942
  | Oct 25, 2017 2:04:50 PM org.jenkinsci.plugins.workflow.support.steps.input.POSTHyperlinkNote <init>
  | WARNING: You need to define the root URL of Jenkins
  | Oct 25, 2017 2:04:50 PM org.jenkinsci.plugins.workflow.support.steps.input.POSTHyperlinkNote <init>
  | WARNING: You need to define the root URL of Jenkins
  | Oct 25, 2017 2:04:54 PM hudson.slaves.NodeProvisioner$2 run
  | INFO: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
  | Oct 25, 2017 2:04:54 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
  | WARNING: Error in provisioning; slave=KubernetesSlave name: jenkins-slave-hrzk3-t6tmd, template=org.csanchez.jenkins.plugins.kubernetes.PodTemplate@1464947
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/ldimaggi-osiotest1-jenkins/pods . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "jenkins-slave-hrzk3-t6tmd" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=3,limits.memory=1536Mi, used: limits.cpu=3,limits.memory=1536Mi, limited: limits.cpu=4,limits.memory=2Gi.
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
  | at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:133)
  | at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:262)
  | at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
```

Log file attached: 
[jenkinslog.txt](https://github.com/openshiftio/openshift.io/files/1415050/jenkinslog.txt)

**Comment by joshuawilson** [comment]
I'm not sure if this issue is more for the SD team or Build. 
cc @kbsingh @vpavlin @rawlingsj

**Comment by jfchevrette** [comment]
According to the 'exceeded quota' error, this appear to be the same as #1204

**Comment by ldimaggi** [comment]
Closing - this issue is not being seen on prod-preview today.
