### ISSUE TITLE
On prod-preview, analytic reports are failing - 401 error

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1234]
Fragment from build log showing the error:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.026 s
[INFO] Finished at: 2017-10-26T16:40:47+00:00
[INFO] Final Memory: 9M/89M
[INFO] ------------------------------------------------------------------------
[Pipeline] retry
[Pipeline] {
[Pipeline] bayesianAnalysis
Running Bayesian stack analysis...
Bayesian API URL is https://recommender.api.prod-preview.openshift.io/api/v1
com.redhat.jenkins.plugins.bayesian.BayesianException: Bayesian error: 401
	at com.redhat.jenkins.plugins.bayesian.Bayesian.submitStackForAnalysis(Bayesian.java:109)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:99)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:68)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jfchevrette** [comment]
This was a problem with the recommender api token. The token has been updated until the work on the per-user token is done. This test should pass now.

**Comment by joshuawilson** [comment]
@ldimaggi can you please verify?

**Comment by samuzzal-choudhury** [comment]
@jfchevrette thanks for updating the hardcoded access token. Manual test shows no error 401 or any other error for Bayesian during the build. Waiting for the e2e.

**Comment by GeorgeActon** [comment]
@samuzzal is there a work item in our backlog for the per user token or are you keeping this open and on our priority list?

**Comment by ldimaggi** [comment]
Sorry - I cannot verify this bug fix as I cannot get the Che/Jenkins pods on prod-preview to start up/deploy after an environment reset. See this bug:   https://github.com/openshiftio/openshift.io/issues/1326

**Comment by samuzzal-choudhury** [comment]
@GeorgeActon This was taken on priority and I worked with @jfchevrette to get the new access token deployed on the prod-preview. We do not have any open todo item to work on at this moment, unless @ldimaggi finds otherwise after he overcomes the bug https://github.com/openshiftio/openshift.io/issues/1326.

**Comment by samuzzal-choudhury** [comment]
#### Brief about the solution:
This issue was  caused by an expired hardcoded access token (openshift secret _jenkins-recommender-api-token_) on the staging cluster which was set up for Jenkins pipeline to integrate with the recommender API. 

The auth team had earlier generated a token for the prod-preview with 365 days expiry which I shared with @jfchevrette who deployed the secret with that. This was done to make the stack reports operational on the prod-preview.

**Comment by ldimaggi** [comment]
Closing - I am now able to generate reports on prod-preview.
