### ISSUE TITLE
On prod-preview - slowness of jenkins pods causes frequent errors where build pipeline fails to run

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1267]
After a successful environment reset, a new quickstart's build pipeline fails. Jenkins reports the following in an infinite loop:

```
Nov 01, 2017 7:48:13 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
--
  | INFO: Started provisioning Kubernetes Pod Template from openshift with 1 executors. Remaining excess workload: 0
  | EXITCODE   0EXITCODE   1   174
  | EXITCODE   0EXITCODE   1   174
  | EXITCODE   0EXITCODE   1   174
  | EXITCODE   0EXITCODE   1   174
  | EXITCODE   0EXITCODE   1   174
  | EXITCODE   0EXITCODE   1   174
  | EXITCODE   0EXITCODE   1   174
  | EXITCODE   0EXITCODE   1   174
  | EXITCODE   0EXITCODE   1   174
  | EXITCODE   0EXITCODE   1   174
  | Nov 01, 2017 7:48:23 PM hudson.slaves.NodeProvisioner$2 run
  | INFO: Kubernetes Pod Template provisioning successfully completed. We have now 3 computer(s)
  | Nov 01, 2017 7:48:23 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
  | INFO: Excess workload after pending Spot instances: 1
  | Nov 01, 2017 7:48:23 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
  | INFO: Template: Kubernetes Pod Template
  | Nov 01, 2017 7:48:23 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
  | INFO: Started provisioning Kubernetes Pod Template from openshift with 1 executors. Remaining excess workload: -0.282
  | Nov 01, 2017 7:48:23 PM hudson.slaves.NodeProvisioner$2 run
  | INFO: Kubernetes Pod Template provisioning successfully completed. We have now 4 computer(s)
  | Nov 01, 2017 7:48:23 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
  | WARNING: Error in provisioning; slave=KubernetesSlave name: jenkins-slave-0tksj-tf8z8, template=org.csanchez.jenkins.plugins.kubernetes.PodTemplate@1f671a1
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/ldimaggi-osiotest1-jenkins/pods . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "jenkins-slave-0tksj-tf8z8" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=3,limits.memory=1536Mi, used: limits.cpu=3,limits.memory=1536Mi, limited: limits.cpu=4,limits.memory=2Gi.
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
  | at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:133)
  | at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:262)
  | at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  |  
  | Nov 01, 2017 7:48:23 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
  | WARNING: Error in provisioning; slave=KubernetesSlave name: jenkins-slave-91fjr-gtzx5, template=org.csanchez.jenkins.plugins.kubernetes.PodTemplate@1d75588
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/ldimaggi-osiotest1-jenkins/pods . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "jenkins-slave-91fjr-gtzx5" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=3,limits.memory=1536Mi, used: limits.cpu=3,limits.memory=1536Mi, limited: limits.cpu=4,limits.memory=2Gi.
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
  | at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:133)
  | at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:262)
  | at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)


```

**Comment by ldimaggi** [comment]
Not reproducible

**Comment by ldimaggi** [comment]
This error is causing all the EE tests running on prod-preview to fail.

**Comment by rajdavies** [comment]
This looks like different limits are set on prod-preview to prod - if you looked at the log - you'd see the problem is that there is an error in provisioning. Not sure why limits are different on prod preview to prod - they should be the same. Not a pipeline problem though

**Comment by ldimaggi** [comment]
It looks like the problem is that the jenkins pods take too long to terminate after a build, so subsequent builds and/or promotions that happen before the first pod dies won't work because of quota limits. The first jenkins slave pod should be gone and have released from quotas for the next one to work.

And - the pods on prod-preview seem to be much slower than on production.

**Comment by jfchevrette** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1510556

**Comment by ldimaggi** [comment]
Closing - not seeing this issue today on prod-preview.
