### ISSUE TITLE
Can't open pipeline view. Navigation fails silently

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#130]
See 
![may-02-2017 10-59-01](https://cloud.githubusercontent.com/assets/148698/25624121/79471460-2f26-11e7-894a-c7d9fbfa3d61.gif)

**Comment by fbricon** [comment]
This seems caused by something gone bad on the openshift side I guess. From the chrome dev tools I can see :

```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'fbricon%40redhat.com/vscode-java/create/pipelines/vscode-marketplace-stats/history/vscode-marketplace-stats/builds/vscode-marketplace-stats-1'
Error: Cannot match any routes. URL Segment: 'fbricon%40redhat.com/vscode-java/create/pipelines/vscode-marketplace-stats/history/vscode-marketplace-stats/builds/vscode-marketplace-stats-1'
    at ApplyRedirects.noMatchError (main.f85060454181524f53ba.bundle.js:1) [angular]
    at CatchSubscriber.selector (main.f85060454181524f53ba.bundle.js:1) [angular]
    at CatchSubscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber._error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber._error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber._error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at LastSubscriber.Subscriber._error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at LastSubscriber.Subscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MergeAllSubscriber.OuterSubscriber.notifyError (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at InnerSubscriber._error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at InnerSubscriber.Subscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at ApplyRedirects.noMatchError (main.f85060454181524f53ba.bundle.js:1) [angular]
    at CatchSubscriber.selector (main.f85060454181524f53ba.bundle.js:1) [angular]
    at CatchSubscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber._error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber._error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber._error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MapSubscriber.Subscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at LastSubscriber.Subscriber._error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at LastSubscriber.Subscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at MergeAllSubscriber.OuterSubscriber.notifyError (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at InnerSubscriber._error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at InnerSubscriber.Subscriber.error (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at resolvePromise (polyfills.f49acb8aeb061f0c40eb.bundle.js:1) [angular]
    at resolvePromise (polyfills.f49acb8aeb061f0c40eb.bundle.js:1) [angular]
    at /_assets/lib/polyfills.f49acb8aeb061f0c40eb.bundle.js:1:56091 [angular]
    at Object.onInvokeTask (vendor.73b76953eab25ca018c6.bundle.js:1) [angular]
    at ZoneDelegate.invokeTask (polyfills.f49acb8aeb061f0c40eb.bundle.js:1) [angular]
    at Zone.runTask (polyfills.f49acb8aeb061f0c40eb.bundle.js:1) [<root> => angular]
    at drainMicroTaskQueue (polyfills.f49acb8aeb061f0c40eb.bundle.js:1) [<root>]
    at HTMLAnchorElement.ZoneTask.invoke (polyfills.f49acb8aeb061f0c40eb.bundle.js:1) [<root>]
defaultErrorLogger @ vendor.73b76953eab25ca018c6.bundle.js:1
```
...which is an orthogonal problem. There should be some user feedback, explaining the action can't be done

**Comment by fbricon** [comment]
Additionally, none of the menus on the left of the pipeline work. Similar errors are shown in the browser console.

Deleting the pipeline fails with:
```
patternfly.css:2 ERROR TypeError: Cannot read property 'open' of undefined
    at PipelinesListComponent.openDeleteDialog (main.f850604….bundle.js:1)
    at Object.eval [as handleEvent] (PipelinesListComponent.ngfactory.js:895)
    at Object._ [as handleEvent] (patternfly.css:2)
    at Object.handleEvent (patternfly.css:2)
    at dispatchEvent (patternfly.css:2)
    at patternfly.css:2
    at HTMLAnchorElement.<anonymous> (patternfly.css:2)
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1)
    at Object.onInvokeTask (patternfly.css:2)
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1)
    at Zone.runTask (polyfills.f49acb8….bundle.js:1)
    at HTMLAnchorElement.ZoneTask.invoke (polyfills.f49acb8….bundle.js:1)
```

**Comment by fbricon** [comment]
Now, clicking on the Build link, I get a webpack related error

```
ERROR Error: Uncaught (in promise): Error: Cannot find module '../build/build.module'.
Error: Cannot find module '../build/build.module'.
    at webpackEmptyContext (patternfly.css:2) [angular]
    at SystemJsNgModuleLoader.loadAndCompile (patternfly.css:2) [angular]
    at SystemJsNgModuleLoader.load (patternfly.css:2) [angular]
    at RouterConfigLoader.loadModuleFactory (main.f850604….bundle.js:1) [angular]
    at RouterConfigLoader.load (main.f850604….bundle.js:1) [angular]
    at MergeMapSubscriber.project (main.f850604….bundle.js:1) [angular]
    at MergeMapSubscriber._tryNext (patternfly.css:2) [angular]
    at MergeMapSubscriber._next (patternfly.css:2) [angular]
    at MergeMapSubscriber.Subscriber.next (patternfly.css:2) [angular]
    at ScalarObservable._subscribe (patternfly.css:2) [angular]
    at ScalarObservable.Observable._trySubscribe (patternfly.css:2) [angular]
    at ScalarObservable.Observable.subscribe (patternfly.css:2) [angular]
    at MergeMapOperator.call (patternfly.css:2) [angular]
    at Observable.subscribe (patternfly.css:2) [angular]
    at webpackEmptyContext (patternfly.css:2) [angular]
    at SystemJsNgModuleLoader.loadAndCompile (patternfly.css:2) [angular]
    at SystemJsNgModuleLoader.load (patternfly.css:2) [angular]
    at RouterConfigLoader.loadModuleFactory (main.f850604….bundle.js:1) [angular]
    at RouterConfigLoader.load (main.f850604….bundle.js:1) [angular]
    at MergeMapSubscriber.project (main.f850604….bundle.js:1) [angular]
    at MergeMapSubscriber._tryNext (patternfly.css:2) [angular]
    at MergeMapSubscriber._next (patternfly.css:2) [angular]
    at MergeMapSubscriber.Subscriber.next (patternfly.css:2) [angular]
    at ScalarObservable._subscribe (patternfly.css:2) [angular]
    at ScalarObservable.Observable._trySubscribe (patternfly.css:2) [angular]
    at ScalarObservable.Observable.subscribe (patternfly.css:2) [angular]
    at MergeMapOperator.call (patternfly.css:2) [angular]
    at Observable.subscribe (patternfly.css:2) [angular]
    at resolvePromise (polyfills.f49acb8….bundle.js:1) [angular]
    at resolvePromise (polyfills.f49acb8….bundle.js:1) [angular]
    at /_assets/lib/polyfills.f49acb8aeb061f0c40eb.bundle.js:1:56091 [angular]
    at Object.onInvokeTask (patternfly.css:2) [angular]
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1) [angular]
    at Zone.runTask (polyfills.f49acb8….bundle.js:1) [<root> => angular]
    at drainMicroTaskQueue (polyfills.f49acb8….bundle.js:1) [<root>]
    at HTMLAnchorElement.ZoneTask.invoke (polyfills.f49acb8….bundle.js:1) [<root>]
```

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1349

**Comment by joshuawilson** [comment]
fixed
