### ISSUE TITLE
Intermittent issue on prod-preview and https://openshift.io - Che workspaces cannot be created - Didn't find publicKey for specified kid

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1303]
Seeing this error logged:

```

2017-11-07 15:10:56,958[nio-8080-exec-3]  [ERROR] [.k.a.r.AdapterRSATokenVerifier 46]   - Didn't find publicKey for kid: 
--
  | 2017-11-07 15:10:56,958[nio-8080-exec-3]  [ERROR] [earerTokenRequestAuthenticator 89]   - Failed to verify token
  | org.keycloak.common.VerificationException: Didn't find publicKey for specified kid
  | at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.getPublicKey(AdapterRSATokenVerifier.java:47)
  | at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:55)
  | at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:37)
  | at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:87)
  | at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:82)
  | at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:67)
  | at org.keycloak.adapters.servlet.KeycloakOIDCFilter.doFilter(KeycloakOIDCFilter.java:168)
  | at com.redhat.che.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:83)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
  | at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:317)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:574)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)
```

**Comment by ibuziuk** [comment]
@ldimaggi could you please explain how have you tried to create a workspace ? Also, please specify the version of che ? 
In any case che on prod-preview is broken due to https://github.com/openshiftio/openshift.io/issues/1067, but according to the logs this issue does not look like a duplicate

**Comment by ldimaggi** [comment]
Sorry for the confusion. The issue here is that the user is not able to created a workspace as the "your workspaces are loading" waiting icon is displayed, but, the link to create a workspace is not displayed:

![screenshot from 2017-11-07 13-48-20](https://user-images.githubusercontent.com/642621/32511914-3de3e740-c3c3-11e7-8a32-715f5d1ab335.png)

**Comment by ibuziuk** [comment]
@ldimaggi thanks for clarifications, could you please also clarify the logs origin - this does not look like che-server logs

**Comment by aslakknutsen** [comment]
@ibuziuk I can confirm. Seeing the same error in che-host in tenant space on preview.

**Comment by ibuziuk** [comment]
I suspect that this issue is a side effect of https://github.com/openshiftio/openshift.io/issues/1067

**Comment by aslakknutsen** [comment]
@ibuziuk Yea, I was suspecting a missing auth URL somewhere. Tenant service supports the variable CHE_KEYCLOAK_AUTH__SERVER__URL so it should be just to use it in the templates

**Comment by ldimaggi** [comment]
The log fragment is from the Che pod's log.

**Comment by ibuziuk** [comment]
> Update: The value of that is actually not mapped to anything in preview. It should be https://sso.prod-preview.openshift.io correct?

@aslakknutsen yeah. looks correct cc: @davidfestal

**Comment by aslakknutsen** [comment]
@ibuziuk Related https://github.com/fabric8-services/fabric8-tenant-che/pull/33

**Comment by ibuziuk** [comment]
PR for fabric8-tenant-che - https://github.com/fabric8-services/fabric8-tenant-che/pull/60

**Comment by ldimaggi** [comment]
[che_log.txt](https://github.com/openshiftio/openshift.io/files/1458345/che_log.txt)

**Comment by ibuziuk** [comment]
@ldimaggi fixed. Could you please verify ?

**Comment by ldimaggi** [comment]
Not seeing this issue on prod-preview today - closing.
