### ISSUE TITLE
dependency_snapshot worker fails with ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1394]
dependency_snapshot task fails for `go:github.com/dhowett/go-plist:233df3c4f07b0c562da0e8a6fb850681ac49bb90`

```
2017-11-17 19:53:19,589 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[18197152-70c6-4360-b282-bfa206ea7200] raised unexpected: ValueError('need more than 2 values to unpack',)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 170, in run
    raise self.retry(max_retries=0, exc=exc)
  File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
    raise_with_context(exc)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 115, in run
    result = task.run(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 41, in run
    result = self.execute(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/workers/dependency_snapshot.py", line 95, in execute
    resolved = self._resolve_dependency(ecosystem, dep)
  File "/usr/lib/python3.4/site-packages/f8a_worker/workers/dependency_snapshot.py", line 65, in _resolve_dependency
    pkgspec = solver.solve([dep])
  File "/usr/lib/python3.4/site-packages/f8a_worker/solver.py", line 810, in solve
    version = self.release_fetcher.fetch_releases(dependency.name)[1][0]
  File "/usr/lib/python3.4/site-packages/f8a_worker/solver.py", line 310, in fetch_releases
    gh_host, gh_org, gh_proj = package.split("/")[:3]
ValueError: need more than 2 values to unpack
```

**Comment by msrb** [comment]
cc @tuxdna 

Saleem, could you please take a look what's wrong here?

**Comment by tuxdna** [comment]
This error looks strange to me because:

```
package = 'github.com/dhowett/go-plist'
gh_host, gh_org, gh_proj = package.split("/")[:3]

In [3]: (gh_host, gh_org, gh_proj)
Out[3]: ('github.com', 'dhowett', 'go-plist')
```
Looks like `package` is malformed before that `split`() call. 

https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/solver.py#L310

**Comment by tuxdna** [comment]
The error is happening due to `gopkg.in/yaml.v1` which apparently is one of the dependency of the package being anlyzed.

```
worker-ingestion_1      | Input package: gopkg.in/yaml.v1
worker-ingestion_1      | {"event": "TASK_FAILURE", "parent": {"metadata": "f8f857a0-7d33-4812-a5f1-c5b87443819a"}, "task_name": "dependency_snapshot", "node_args": {"version": "233df3c4f07b0c562da0e8a6fb850681ac49bb90", "_release": "go:github.com/dhowett/go-plist:233df3c4f07b0c562da0e8a6fb850681ac49bb90", "_audit": {"ended_at": "2017-11-20T13:05:26.367211", "version": "v1", "started_at": "2017-11-20T13:05:16.171580"}, "force": false, "name": "github.com/dhowett/go-plist", "force_graph_sync": true, "document_id": 1, "ecosystem": "go"}, "what": "Traceback (most recent call last):\n  File \"/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 115, in run\n    result = task.run(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 41, in run\n    result = self.execute(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/dependency_snapshot.py\", line 95, in execute\n    resolved = self._resolve_dependency(ecosystem, dep)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/dependency_snapshot.py\", line 65, in _resolve_dependency\n    pkgspec = solver.solve([dep])\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/solver.py\", line 812, in solve\n    version = self.release_fetcher.fetch_releases(dependency.name)[1][0]\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/solver.py\", line 312, in fetch_releases\n    gh_host, gh_org, gh_proj = package.split(\"/\")[:3]\nValueError: need more than 2 values to unpack\n", "dispatcher_id": "286ee1ff-e325-46c4-8756-a768b986a675", "task_id": "cd1c5fb8-2948-425d-81fd-468544c49956", "flow_name": "bayesianAnalysisFlow", "queue": "tuxdna_ingestion_DependencySnapshotTask_v0", "retried_count": 0}
worker-ingestion_1      | {"error_type": "<class 'ValueError'>", "storage_task_name": "dependency_snapshot", "error_value": "need more than 2 values to unpack", "storage_name": "BayesianPostgres", "error_traceback": "  File \"/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 115, in run\n    result = task.run(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 41, in run\n    result = self.execute(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/dependency_snapshot.py\", line 95, in execute\n    resolved = self._resolve_dependency(ecosystem, dep)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/dependency_snapshot.py\", line 65, in _resolve_dependency\n    pkgspec = solver.solve([dep])\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/solver.py\", line 812, in solve\n    version = self.release_fetcher.fetch_releases(dependency.name)[1][0]\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/solver.py\", line 312, in fetch_releases\n    gh_host, gh_org, gh_proj = package.split(\"/\")[:3]\n", "record_id": null, "task_name": "dependency_snapshot", "node_args": {"version": "233df3c4f07b0c562da0e8a6fb850681ac49bb90", "_release": "go:github.com/dhowett/go-plist:233df3c4f07b0c562da0e8a6fb850681ac49bb90", "_audit": {"ended_at": "2017-11-20T13:05:26.367211", "version": "v1", "started_at": "2017-11-20T13:05:16.171580"}, "force": false, "name": "github.com/dhowett/go-plist", "force_graph_sync": true, "document_id": 1, "ecosystem": "go"}, "task_id": "cd1c5fb8-2948-425d-81fd-468544c49956", "event": "STORAGE_STORE_ERROR", "flow_name": "bayesianAnalysisFlow"}
coreapi-pgbouncer       | 2017-11-20 13:05:43.536 14 LOG C-0x92e5d0: coreapi/coreapi@172.17.0.13:35316 login attempt: db=coreapi user=coreapi tls=no
coreapi-pgbouncer       | 2017-11-20 13:05:43.579 14 LOG C-0x92e5d0: coreapi/coreapi@172.17.0.13:35316 closing because: client close request (age=0)
worker-ingestion_1      | 2017-11-20 13:05:43,580 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[cd1c5fb8-2948-425d-81fd-468544c49956] raised unexpected: ValueError('need more than 2 values to unpack',)
worker-ingestion_1      | Traceback (most recent call last):
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
worker-ingestion_1      |     R = retval = fun(*args, **kwargs)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
worker-ingestion_1      |     return self.run(*args, **kwargs)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 170, in run
worker-ingestion_1      |     raise self.retry(max_retries=0, exc=exc)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
worker-ingestion_1      |     raise_with_context(exc)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 115, in run
worker-ingestion_1      |     result = task.run(node_args)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 41, in run
worker-ingestion_1      |     result = self.execute(node_args)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/workers/dependency_snapshot.py", line 95, in execute
worker-ingestion_1      |     resolved = self._resolve_dependency(ecosystem, dep)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/workers/dependency_snapshot.py", line 65, in _resolve_dependency
worker-ingestion_1      |     pkgspec = solver.solve([dep])
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/solver.py", line 812, in solve
worker-ingestion_1      |     version = self.release_fetcher.fetch_releases(dependency.name)[1][0]
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/solver.py", line 312, in fetch_releases
worker-ingestion_1      |     gh_host, gh_org, gh_proj = package.split("/")[:3]
worker-ingestion_1      | ValueError: need more than 2 values to unpack
worker-ingestion_1      | 2017-11-20 13:05:43,588 [INFO] celery.worker.strategy: Received task: selinon.Dispatcher[286ee1ff-e325-46c4-8756-a768b986a675]  ETA:[2017-11-20 13:05:56.729654+00:00] 

```

**Comment by joshuawilson** [comment]
Was this fixed, is that why it is closed?

**Comment by tuxdna** [comment]
@joshuawilson Yes, it was fixed in the PR attached to this issue.
