### ISSUE TITLE
Intermittent error - Che workspaces cannot be created on https://openshift.io - Start of environment 'default' failed

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1599]
Seeing this error 20-30% of the time today - December 8 - when trying to create a new Che workspace:

```
Could not start workspace <name>. Reason: Start of environment 'default' failed. Error: Failed to get the ID of the container running in the OpenShift pod
```

Steps to recreate:
* Create a new space
* Create a new app/quickstart
* Attempt to create a new Che workspace

This issue was previously reported in https://github.com/openshiftio/openshift.io/issues/1041 (now closed)

**Comment by ldimaggi** [comment]
In the Che pod log:

```

2017-12-08 20:16:49,944[aceSharedPool-4]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Failed to get the ID of the container running in the OpenShift pod
--
  | org.eclipse.che.api.core.ServerException: Failed to get the ID of the container running in the OpenShift pod
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1005)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:797)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
  | at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: org.eclipse.che.api.core.ServerException: Failed to get the ID of the container running in the OpenShift pod
  | at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:401)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:768)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:942)
  | ... 11 common frames omitted
  | Caused by: org.eclipse.che.plugin.openshift.client.exception.OpenShiftException: Failed to get the ID of the container running in the OpenShift pod
  | at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.createContainer(OpenShiftConnector.java:714)
  | at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:648)
  | at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:357)
  | ... 13 common frames omitted


```

**Comment by l0rd** [comment]
That's coherent with what I am observing too. In ~30% of the cases Che is still started before the route is constantly returning HTTP code 200. That means that #1304 was mitigated but not completely solved. 

There are a couple of things we can do to address that:
- The short term solution: change Che configuration. Che is configured to start 20 seconds after the first successful ping. We need to augment this value. I will test the minimum value to have 10 successful workspaces created in a row and set it accordingly. 
- The long term solution: don't start based on a fixed number of seconds after the first ping but after a fixed number of consecutive successful pings. That's how it should already work but for some reason it's not. After the first successful HTTP 200 Che only get other HTTP 200 even if the route is clearly not returning consistent HTTP 200 responses.

**Comment by sbose78** [comment]
As per @l0rd 's comment above, change has been deployed to production yesterday.
https://github.com/openshiftio/saas-openshiftio/pull/508

Verification is pending.

**Comment by ldimaggi** [comment]
While this problem was intermittent in the past - I have not seen it today. Closing this issue unless/until it is seen again.
