### ISSUE TITLE
[MT-che] Runtime exception when deleting workspaces (Forbidden!Configured service account doesn't have access.)

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#1651]
When deleting ~10 workspaces at once using che.openshift.io dashboard, I've noticed these errors in che master pod log:
```
2017-12-13 14:31:44,991[entSubscriber-0]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspaceux5msn0fjyjblp3u on PVC claim-che-workspace
2017-12-13 14:31:44,992[entSubscriber-0]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
2017-12-13 14:31:44,992[entSubscriber-0]  [INFO ] [c8WorkspaceEnvironmentProvider 197]  - Retrieving user Che tenant data
2017-12-13 14:31:44,993[entSubscriber-1]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspace1ng67ihd2yd7siol on PVC claim-che-workspace
2017-12-13 14:31:44,994[entSubscriber-1]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
2017-12-13 14:31:45,008[entSubscriber-2]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspacekew7oh1xx44oy8v3 on PVC claim-che-workspace
2017-12-13 14:31:45,008[entSubscriber-2]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
2017-12-13 14:31:45,042[entSubscriber-3]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspaces8kjmup7dmr9rv9x on PVC claim-che-workspace
2017-12-13 14:31:45,042[entSubscriber-3]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
2017-12-13 14:31:45,165[io-8080-exec-10]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspace1ng67ihd2yd7siol' removed by user 'rhopp-osiotest1'
2017-12-13 14:31:45,167[nio-8080-exec-7]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspaces8kjmup7dmr9rv9x' removed by user 'rhopp-osiotest1'
2017-12-13 14:31:45,171[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspacekew7oh1xx44oy8v3' removed by user 'rhopp-osiotest1'
2017-12-13 14:31:45,174[entSubscriber-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspacesuyniywgfkkg0vvc on PVC claim-che-workspace
2017-12-13 14:31:45,174[entSubscriber-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
2017-12-13 14:31:45,178[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspaceux5msn0fjyjblp3u' removed by user 'rhopp-osiotest1'
2017-12-13 14:31:45,184[entSubscriber-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspace7yxmyhs7p0jv4nzg on PVC claim-che-workspace
2017-12-13 14:31:45,185[entSubscriber-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
2017-12-13 14:31:45,190[nio-8080-exec-4]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspacesuyniywgfkkg0vvc' removed by user 'rhopp-osiotest1'
2017-12-13 14:31:45,194[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspace7yxmyhs7p0jv4nzg' removed by user 'rhopp-osiotest1'
2017-12-13 14:31:45,340[entSubscriber-0]  [INFO ] [c8WorkspaceEnvironmentProvider 230]  - cheTenantData = {rhopp-osiotest1-che,https://api.starter-us-east-2.openshift.com,null}
2017-12-13 14:31:45,395[entSubscriber-3]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
2017-12-13 14:31:45,396[entSubscriber-1]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
2017-12-13 14:31:45,397[entSubscriber-4]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
2017-12-13 14:31:45,397[entSubscriber-0]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
2017-12-13 14:31:45,397[entSubscriber-5]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
2017-12-13 14:31:45,398[entSubscriber-2]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
2017-12-13 14:31:45,782[entSubscriber-6]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspacelkn6i8e9o8ii2e0r on PVC claim-che-workspace
2017-12-13 14:31:45,783[entSubscriber-6]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
2017-12-13 14:31:45,783[entSubscriber-6]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
2017-12-13 14:31:45,802[entSubscriber-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspace0jly0lxjarz8a1kr on PVC claim-che-workspace
2017-12-13 14:31:45,802[entSubscriber-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
2017-12-13 14:31:45,802[entSubscriber-7]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
2017-12-13 14:31:45,822[entSubscriber-8]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspaceizlstczkl99ar705 on PVC claim-che-workspace
2017-12-13 14:31:45,822[entSubscriber-8]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
2017-12-13 14:31:45,822[entSubscriber-8]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
2017-12-13 14:31:45,839[nio-8080-exec-5]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspace0jly0lxjarz8a1kr' removed by user 'rhopp-osiotest1'
2017-12-13 14:31:45,842[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspacelkn6i8e9o8ii2e0r' removed by user 'rhopp-osiotest1'
2017-12-13 14:31:45,852[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspaceizlstczkl99ar705' removed by user 'rhopp-osiotest1'
2017-12-13 14:31:45,865[entSubscriber-9]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspace5x1r24yb15dor1re on PVC claim-che-workspace
2017-12-13 14:31:45,866[entSubscriber-9]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
2017-12-13 14:31:45,866[entSubscriber-9]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
2017-12-13 14:31:45,868[nio-8080-exec-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspace5x1r24yb15dor1re' removed by user 'rhopp-osiotest1'
2017-12-13 14:31:46,291[entSubscriber-7]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-7. Message: Failure executing: POST at: https://api.starter-us-east-2.openshift.com/api/v1/namespaces/rhopp-osiotest1-che/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.starter-us-east-2.openshift.com/api/v1/namespaces/rhopp-osiotest1-che/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:320)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:267)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:239)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:210)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:699)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:324)
	at org.eclipse.che.plugin.openshift.client.OpenShiftPvcHelper.createJobPod(OpenShiftPvcHelper.java:186)
	at org.eclipse.che.plugin.openshift.client.OpenShiftWorkspaceFilesCleaner.deleteWorkspacesOnPvc(OpenShiftWorkspaceFilesCleaner.java:120)
	at org.eclipse.che.plugin.openshift.client.OpenShiftWorkspaceFilesCleaner.clear(OpenShiftWorkspaceFilesCleaner.java:101)
	at org.eclipse.che.plugin.docker.machine.cleaner.RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber.lambda$onEvent$0(RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber.java:68)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-13 14:31:46,479[entSubscriber-2]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-2. Message: Failure executing: POST at: https://api.starter-us-east-2.openshift.com/api/v1/namespaces/rhopp-osiotest1-che/pods. Message: Operation cannot be fulfilled on resourcequotas "compute-resources-timebound": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=resourcequotas, name=compute-resources-timebound, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on resourcequotas "compute-resources-timebound": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.starter-us-east-2.openshift.com/api/v1/namespaces/rhopp-osiotest1-che/pods. Message: Operation cannot be fulfilled on resourcequotas "compute-resources-timebound": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=resourcequotas, name=compute-resources-timebound, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on resourcequotas "compute-resources-timebound": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:320)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:269)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:239)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:210)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:699)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:324)
	at org.eclipse.che.plugin.openshift.client.OpenShiftPvcHelper.createJobPod(OpenShiftPvcHelper.java:186)
	at org.eclipse.che.plugin.openshift.client.OpenShiftWorkspaceFilesCleaner.deleteWorkspacesOnPvc(OpenShiftWorkspaceFilesCleaner.java:120)
	at org.eclipse.che.plugin.openshift.client.OpenShiftWorkspaceFilesCleaner.clear(OpenShiftWorkspaceFilesCleaner.java:101)
	at org.eclipse.che.plugin.docker.machine.cleaner.RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber.lambda$onEvent$0(RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber.java:68)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Though it seems that all workspaces were successfully deleted.

**Comment by ibuziuk** [comment]
I have slightly different logs:

`{"@timestamp":"2017-12-18T10:06:42.193+00:00","@version":1,"message":"Runtime exception caught in thread RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-0. Message: An error has occurred.","logger_name":"org.eclipse.che.commons.lang.concurrent.LoggingUncaughtExceptionHandler","thread_name":"RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-0","level":"ERROR","level_value":40000,"stack_trace":"io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.\n\tat io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:61)\n\tat io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:52)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:331)\n\tat org.eclipse.che.plugin.openshift.client.OpenShiftPvcHelper.createJobPod(OpenShiftPvcHelper.java:187)\n\tat org.eclipse.che.plugin.openshift.client.OpenShiftWorkspaceFilesCleaner.deleteWorkspacesOnPvc(OpenShiftWorkspaceFilesCleaner.java:120)\n\tat org.eclipse.che.plugin.openshift.client.OpenShiftWorkspaceFilesCleaner.clear(OpenShiftWorkspaceFilesCleaner.java:101)\n\tat org.eclipse.che.plugin.docker.machine.cleaner.RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber.lambda$onEvent$0(RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber.java:68)\n\tat org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:29)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n\tat sun.security.ssl.Alerts.getSSLException(Alerts.java:192)\n\tat sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.j
ava:1959)\n\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)\n\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)\n\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)\n\tat sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)\n\tat sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)\n\tat sun.security.ssl.Handshaker.process_record(Handshaker.java:961)\n\tat sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)\n\tat sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)\n\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)\n\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)\n\tat okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:267)\n\tat okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237)\n\tat okhttp3.internal.connection.RealConnection.connect(RealConnection.java:148)\n\tat okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)\n\tat okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)\n\tat okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)\n\tat okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n\tat okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n\tat okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n\tat okhttp3.internal.http.RetryAndFollowUpInterceptor.interc
ept(RetryAndFollowUpInterceptor.java:120)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n\tat org.eclipse.che.plugin.openshift.client.OpenShiftClientFactory$1.intercept(OpenShiftClientFactory.java:87)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n\tat okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)\n\tat okhttp3.RealCall.execute(RealCall.java:63)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:210)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:699)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:324)\n\t... 8 common frames omitted\nCaused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)\n\tat sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)\n\tat sun.security.validator.Validator.validate(Validator.java:253)\n\tat sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)\n\tat sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)\n\tat sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)\n\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)\n\t... 42 common frames omitted\nCaused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find va
lid certification path to requested target\n\tat sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)\n\tat sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)\n\tat java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)\n\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)\n\t... 48 common frames omitted\n"}`

**Comment by ibuziuk** [comment]
Ok looks like it is another issue related to the certificate. Every operation that involves openshift / k8s client (including workspace creation) fails with certificate problem:


{"@timestamp":"2017-12-18T10:11:34.692+00:00","@version":1,"message":"Workspace 'ibuziuk@redhat.com/wksp-sj5r' with id 'workspace9q0wss99iil9e4ru' created by user 'ibuziuk@redhat.com'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"http-nio-8080-exec-2","level":"INFO","level_value":20000,"identity_id":"9956255a-776f-4c8a-950e-878dc54f871a"}
--
  | {"@timestamp":"2017-12-18T10:11:36.701+00:00","@version":1,"message":"Failed to check image che/vertx availability. Cause: Unable connect to unix socket: '/var/run/docker.sock'","logger_name":"org.eclipse.che.plugin.docker.machine.MachineProviderImpl","thread_name":"WorkspaceSharedPool-2","level":"WARN","level_value":30000}
  | {"@timestamp":"2017-12-18T10:11:36.741+00:00","@version":1,"message":"An error has occurred.","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"WorkspaceSharedPool-2","level":"ERROR","level_value":40000,"stack_trace":"org.eclipse.che.api.core.ServerException: An error has occurred.\n\tat org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1005)\n\tat org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:797)\n\tat org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)\n\tat org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)\n\tat org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)\n\tat org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)\n\tat org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)\n\tat org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.eclipse.che.api.core.ServerException: An error has occurred.\n\tat org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:401)\n\tat org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:768)\n\tat org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:942)\n\t... 11 common frames omitted\nCaused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.\n\tat io.fabric8.kubernetes.clien
  | t.KubernetesClientException.launderThrowable(KubernetesClientException.java:61)\n\tat io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:52)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:199)\n\tat org.eclipse.che.plugin.openshift.client.OpenShiftConnector.pull(OpenShiftConnector.java:986)\n\tat org.eclipse.che.plugin.docker.machine.MachineProviderImpl.pullImage(MachineProviderImpl.java:539)\n\tat org.eclipse.che.plugin.docker.machine.MachineProviderImpl.prepareImage(MachineProviderImpl.java:448)\n\tat org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:355)\n\t... 13 common frames omitted\nCaused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n\tat sun.security.ssl.Alerts.getSSLException(Alerts.java:192)\n\tat sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)\n\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)\n\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)\n\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)\n\tat sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)\n\tat sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)\n\tat sun.security.ssl.Handshaker.process_record(Handshaker.java:961)\n\tat sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)\n\tat sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)\n\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)\n\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)\n\tat okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:267)\n\tat okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237)\n\tat okhttp3.internal.conne
  | ction.RealConnection.connect(RealConnection.java:148)\n\tat okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)\n\tat okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)\n\tat okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)\n\tat okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n\tat okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n\tat okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n\tat okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n\tat io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:64)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n\tat okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)\n\tat okhttp3.RealCall.execute(RealCall.java:63)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:228)\n\tat io.fabric8.kubernetes.c
  | lient.dsl.base.BaseOperation.handleGet(BaseOperation.java:711)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:192)\n\t... 17 common frames omitted\nCaused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)\n\tat sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)\n\tat sun.security.validator.Validator.validate(Validator.java:253)\n\tat sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)\n\tat sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)\n\tat sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)\n\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)\n\t... 51 common frames omitted\nCaused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n\tat sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)\n\tat sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)\n\tat java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)\n\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)\n\t... 57 common frames omitted\n"}

**Comment by ibuziuk** [comment]
Related rh-che issue https://github.com/redhat-developer/rh-che/issues/486

**Comment by rhopp** [comment]
I wasnt' able to reproduce this issue on latest che on che.openshift.io. Closing.
