### ISSUE TITLE
On prod-preview  - seeing slower than usual times to start a build pipeline

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1731]
Noticed this today - it is taking up to 5-6 minutes for a build pipeline to start, while creating a new quickstart/app:

![screenshot from 2017-12-21 12-30-54](https://user-images.githubusercontent.com/642621/34269129-383c07f4-e651-11e7-8c4c-5fb93aaed234.png)

Seeing messages such as the following written to the Jenkins log every 30 seconds - does nayone know what is going on here?
[jenkins_log.txt](https://github.com/openshiftio/openshift.io/files/1580164/jenkins_log.txt)

```
WARNING: JENKINS-45892: reference to org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject@181b3d1[osiotestmachine/testdec211513879393388] being saved from unexpected /var/lib/jenkins/jobs/osiotestmachine/jobs/testdec211513879393388/indexing/indexing.xml
  | java.lang.IllegalStateException
  | at hudson.XmlFile.replaceIfNotAtTopLevel(XmlFile.java:208)
  | at hudson.model.AbstractItem.writeReplace(AbstractItem.java:492)
  | at sun.reflect.GeneratedMethodAccessor457.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteReplace(SerializationMethodInvoker.java:89)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:141)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
  | at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
  | at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
  | at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
  | at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
  | at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
  | at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
  | at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
  | at hudson.XmlFile.write(XmlFile.java:179)
  | at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.save(FolderComputation.java:208)
  | at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:192)
  | at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1004)
  | at hudson.model.ResourceController.execute(ResourceController.java:97)
  | at hudson.model.Executor.run(Executor.java:429)
 


```

## Impacts
- [ ] #2155 CI Experience placeholder

**Comment by ldimaggi** [comment]
Seeing multiple instances on December 31 - log attached.

[pod_slow_start.txt](https://github.com/openshiftio/openshift.io/files/1595572/pod_slow_start.txt)

**Comment by ldimaggi** [comment]
Another example - 14+ minutes to start a build:

![screenshot from 2018-01-01 20-24-13](https://user-images.githubusercontent.com/642621/34472524-55e78ff0-ef32-11e7-857c-177463173259.png)

**Comment by rupalibehera** [comment]
@ldimaggi , could you please mention the Jenkins version you were using when you reproduced this issue ?

**Comment by ldimaggi** [comment]
I reset the env at least daily - not sure what the version was when I was seeing this last week. Are you no longer able to see this issue? I *think* it is better now - running with 4.0.47 today.  Will update the issue if the problem appears again.

**Comment by rupalibehera** [comment]
@ldimaggi , I was not able to see this issue let me know if could reproduce this one.

**Comment by ldimaggi** [comment]
Thanks - looking today - this issue was very common last week - not so today. What changed?

**Comment by rupalibehera** [comment]
@ldimaggi, from last 15 days we have the same version of Jenkins, atleast nothing from that side :)

**Comment by ldimaggi** [comment]
Seeing it today on prod-preview:

![screenshot from 2018-01-05 14-11-37](https://user-images.githubusercontent.com/642621/34631808-33a8c484-f240-11e7-82f6-b87622c82a59.png)

**Comment by rupalibehera** [comment]
@ldimaggi , Looks like some resources problem if with the same version of Jenkins is behaving differently in two different environment. 
I think so this issue should be closed, or have some info or error logs on this, this isn't enough for debugging this issue.
The error logs which you have provided above they are warnings which we can ignore.

**Comment by chmouel** [comment]
This should probably go along with https://github.com/openshiftio/openshift.io/issues/1903 @jaseemabid i think it may be a good idea to talk about  monitoring on Jenkins to at least have a view how long we have the runs going on,

**Comment by fche** [comment]
For monitoring OSIO tenant jenkins instances, see https://github.com/fabric8io/fabric8-build-team/issues/24

**Comment by ldimaggi** [comment]
Related to #1904

**Comment by ldimaggi** [comment]
Closing as non-reproducible.
