### ISSUE TITLE
Intermittent error in creating pipeline - Unexpected exception in CPS VM thread

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1732]
Seeing this once or twice this week -  Unexpected exception in CPS VM thread

Steps to recreate:
* Create new space
* Create new quickstart
* Observe build pipeline fail
```

Dec 26, 2017 6:38:10 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
Dec 26, 2017 6:38:10 PM org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService reportProblem
WARNING: Unexpected exception in CPS VM thread: CpsFlowExecution[Owner[osiotestmachine/testdec261514313206144/master/1:osiotestmachine/testdec261514313206144/master #1]]
java.lang.NullPointerException
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.getFirstHead(CpsFlowExecution.java:1188)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onProgramEnd(CpsFlowExecution.java:1034)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:351)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:243)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:231)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

[jenkins_log.txt](https://github.com/openshiftio/openshift.io/files/1587884/jenkins_log.txt)

**Comment by kbsingh** [comment]
dropping service delivery, let us know if we can help with anything here.

**Comment by ldimaggi** [comment]
Closing as this problem is not reproducible.

**Comment by ldimaggi** [comment]
Issue found/encountered by EE tests.
