### ISSUE TITLE
When creating new quickstart, IllegalStateException seen in Jenkins log - for successful builds

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1759]
There doesn't seem to be any adverse impact to the build, but the message as written to the Jenkins pod log may cause user concern. What is the cause of the IllegalStateException?

Steps to recreate:
* Create new quickstart
* Observe Jenkins pod log

```
INFO: Upsert WorkflowJob master to BuildConfig: ldimaggi-osiotest1/testjan21514914223761 in OpenShift
--
  | Jan 02, 2018 5:31:13 PM hudson.XmlFile replaceIfNotAtTopLevel
  | WARNING: JENKINS-45892: reference to org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject@43a145[osiotestmachine/testjan21514914223761] being saved from unexpected /var/lib/jenkins/jobs/osiotestmachine/jobs/testjan21514914223761/indexing/indexing.xml
  | java.lang.IllegalStateException
  | at hudson.XmlFile.replaceIfNotAtTopLevel(XmlFile.java:208)
  | at hudson.model.AbstractItem.writeReplace(AbstractItem.java:492)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteReplace(SerializationMethodInvoker.java:89)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:141)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
  | at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
  | at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
  | at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
  | at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
  | at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
  | at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
  | at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
  | at hudson.XmlFile.write(XmlFile.java:179)
  | at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.save(FolderComputation.java:208)
  | at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:192)
  | at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1004)
  | at hudson.model.ResourceController.execute(ResourceController.java:97)
  | at hudson.model.Executor.run(Executor.java:429)
  |  
  | Jan 02, 2018 5:31:13 PM jenkins.branch.MultiBranchProject$BranchIndexing run
  | INFO: osiotestmachine/testjan21514914223761 #20180102.173112 branch indexing action completed: SUCCESS in 0.98 sec
  | Jan 02, 2018 5:31:14 PM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2 call
  | INFO: Updated job testjan21514914223761 from BuildConfig NamespaceName{ldimaggi-osiotest1:testjan21514914223761} with revision: 794113573


```

**Comment by ldimaggi** [comment]
This is still an issue, but it has zero functional impact to the user.  It  would be nice to not write any alarming messages to our logs if possible,

**Comment by rupalibehera** [comment]
This is some exceptions thrown by Jenkins I am not sure how much control we have on this.

**Comment by sthaha** [comment]
@ldimaggi I am closing this as "Won't Fix" since we don't have much control over the message written by various plugins to stdout/stderr.
