### ISSUE TITLE
wfswarm-circuit-breaker booster fails to build after import into OSIO

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1880]
This is a placeholder for running the RHOAR booster programs after importing into OSIO.

wfswarm-circuit-breaker fails with this build error:

```
OpenShift Build ldimaggi-osiotest1/wfswarm-circuit-breaker-3 from https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker.git
17:35:35 Connecting to https://api.github.com using wildfly-swarm-openshiftio-boosters/****** (cd-github)
Obtained Jenkinsfile from b7948a778a587b0839ded7e29efa1469203d70bb
Loading library github.com/fabric8io/fabric8-pipeline-library@master
Attempting to resolve master from remote references...
 > git --version # timeout=10
 > git ls-remote -h -t https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
Found match: refs/heads/master revision 79feba197d05f9926885ea8fd8be0d172e9a426a
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git
 > git --version # timeout=10
 > git fetch --no-tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision 79feba197d05f9926885ea8fd8be0d172e9a426a (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 79feba197d05f9926885ea8fd8be0d172e9a426a
Commit message: "Merge pull request #374 from valdar/issue#373"
 > git rev-list 79feba197d05f9926885ea8fd8be0d172e9a426a # timeout=10
[Pipeline] echo
Kubernetes Plugin Version 013
[Pipeline] echo
Loaded PipelineConfiguration PipelineConfiguration{jobNameToKindMap={}, ciBranchPatterns=[PR-.*], cdBranchPatterns=[master], cdGitHostAndOrganisationToBranchPatterns={}, disableITestsCD=false, disableITestsCI=false, useDockerSocketFlag=false}
[Pipeline] echo
Loaded the useDockerSocket flag false
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
jenkins-slave-2btgh-8hfn4 is offline
Running on jenkins-slave-2btgh-8hfn4 in /home/jenkins/workspace/warm-circuit-breaker_master-T2KFDIASUF3ZYT3RWTBZK37UGXRHC4THCPKWMSNUI7LFWNWLOMBA
[Pipeline] {
[Pipeline] checkout
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker.git
 > git init /home/jenkins/workspace/warm-circuit-breaker_master-T2KFDIASUF3ZYT3RWTBZK37UGXRHC4THCPKWMSNUI7LFWNWLOMBA # timeout=10
Fetching upstream changes from https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials cd-github
 > git fetch --no-tags --progress https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker.git +refs/heads/master:refs/remotes/origin/master
 > git config remote.origin.url https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config remote.origin.url https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker.git
using GIT_ASKPASS to set credentials cd-github
 > git fetch --no-tags --progress https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker.git +refs/heads/master:refs/remotes/origin/master
Checking out Revision b7948a778a587b0839ded7e29efa1469203d70bb (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f b7948a778a587b0839ded7e29efa1469203d70bb
Commit message: "Adding pipeline"
 > git rev-list b7948a778a587b0839ded7e29efa1469203d70bb # timeout=10
[Pipeline] echo
Using branch master
[Pipeline] echo
Using branch master
[Pipeline] echo
NOTE: running pipelines for the first time will take longer as build and base docker images are pulled onto the node
[Pipeline] container
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build Release)
[Pipeline] sh
[warm-circuit-breaker_master-T2KFDIASUF3ZYT3RWTBZK37UGXRHC4THCPKWMSNUI7LFWNWLOMBA] Running shell script
+ git checkout -b wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker/master-1.0.4
Switched to a new branch 'wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker/master-1.0.4'
[Pipeline] sh
[warm-circuit-breaker_master-T2KFDIASUF3ZYT3RWTBZK37UGXRHC4THCPKWMSNUI7LFWNWLOMBA] Running shell script
+ mvn org.codehaus.mojo:versions-maven-plugin:2.2:set -U -DnewVersion=1.0.4
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] WildFly Swarm - Circuit Breaker Booster
[INFO] WildFly Swarm - C/B Booster - Name Service
[INFO] WildFly Swarm - C/B Booster - Greeting Service
[INFO] WildFly Swarm - C/B Booster - Tests
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building WildFly Swarm - Circuit Breaker Booster 5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.2:set (default-cli) @ wfswarm-circuit-breaker-parent ---
[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: /home/jenkins/workspace/warm-circuit-breaker_master-T2KFDIASUF3ZYT3RWTBZK37UGXRHC4THCPKWMSNUI7LFWNWLOMBA
[INFO] Processing change of io.openshift.booster:wfswarm-circuit-breaker-parent:5-SNAPSHOT -> 1.0.4
[INFO] Processing io.openshift.booster:wfswarm-circuit-breaker-parent
[INFO]     Updating project io.openshift.booster:wfswarm-circuit-breaker-parent
[INFO]         from version 5-SNAPSHOT to 1.0.4
[INFO] 
[INFO] Processing io.openshift.booster:wfswarm-circuit-breaker-greeting
[INFO]     Updating parent io.openshift.booster:wfswarm-circuit-breaker-parent
[INFO]         from version 5-SNAPSHOT to 1.0.4
[INFO] 
[INFO] Processing io.openshift.booster:wfswarm-circuit-breaker-name
[INFO]     Updating parent io.openshift.booster:wfswarm-circuit-breaker-parent
[INFO]         from version 5-SNAPSHOT to 1.0.4
[INFO] 
[INFO] Processing io.openshift.booster:wfswarm-circuit-breaker-tests
[INFO]     Updating parent io.openshift.booster:wfswarm-circuit-breaker-parent
[INFO]         from version 5-SNAPSHOT to 1.0.4
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] WildFly Swarm - Circuit Breaker Booster ............ SUCCESS [  5.996 s]
[INFO] WildFly Swarm - C/B Booster - Name Service ......... SKIPPED
[INFO] WildFly Swarm - C/B Booster - Greeting Service ..... SKIPPED
[INFO] WildFly Swarm - C/B Booster - Tests ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.776 s
[INFO] Finished at: 2018-01-12T17:37:18+00:00
[INFO] Final Memory: 8M/12M
[INFO] ------------------------------------------------------------------------
[Pipeline] sh
[warm-circuit-breaker_master-T2KFDIASUF3ZYT3RWTBZK37UGXRHC4THCPKWMSNUI7LFWNWLOMBA] Running shell script
+ mvn clean -B -e -U deploy -Dmaven.test.skip=false -P openshift
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] WildFly Swarm - Circuit Breaker Booster
[INFO] WildFly Swarm - C/B Booster - Name Service
[INFO] WildFly Swarm - C/B Booster - Greeting Service
[INFO] WildFly Swarm - C/B Booster - Tests
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building WildFly Swarm - Circuit Breaker Booster 1.0.4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ wfswarm-circuit-breaker-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java-version) @ wfswarm-circuit-breaker-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-maven-version) @ wfswarm-circuit-breaker-parent ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ wfswarm-circuit-breaker-parent ---
[INFO] Executing: /bin/sh -c cd '/home/jenkins/workspace/warm-circuit-breaker_master-T2KFDIASUF3ZYT3RWTBZK37UGXRHC4THCPKWMSNUI7LFWNWLOMBA' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/jenkins/workspace/warm-circuit-breaker_master-T2KFDIASUF3ZYT3RWTBZK37UGXRHC4THCPKWMSNUI7LFWNWLOMBA
[INFO] Storing buildNumber: b7948a778a587b0839ded7e29efa1469203d70bb at timestamp: 1515778649534
[INFO] Storing buildScmBranch: wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker/master-1.0.4
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.28:resource (default) @ wfswarm-circuit-breaker-parent ---
[INFO] F8: Running in OpenShift mode
[INFO] F8: Using docker image name of namespace: ldimaggi-osiotest1-jenkins
[INFO] F8: Running generator wildfly-swarm
[INFO] F8: wildfly-swarm: Using Docker image registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift as base / builder
[INFO] 
[INFO] --- wildfly-swarm-plugin:2017.10.0:package (default) @ wfswarm-circuit-breaker-parent ---
[INFO] Not processing project with pom packaging
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.28:build (default) @ wfswarm-circuit-breaker-parent ---
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] F8: Running generator wildfly-swarm
[INFO] F8: wildfly-swarm: Using Docker image registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift as base / builder
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] WildFly Swarm - Circuit Breaker Booster ............ FAILURE [ 17.484 s]
[INFO] WildFly Swarm - C/B Booster - Name Service ......... SKIPPED
[INFO] WildFly Swarm - C/B Booster - Greeting Service ..... SKIPPED
[INFO] WildFly Swarm - C/B Booster - Tests ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.758 s
[INFO] Finished at: 2018-01-12T17:37:40+00:00
[INFO] Final Memory: 22M/33M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.28:build (default) on project wfswarm-circuit-breaker-parent: Execution default of goal io.fabric8:fabric8-maven-plugin:3.5.28:build failed: Cannot extract generator config: org.apache.maven.plugin.MojoExecutionException: Cannot extract main class to startup -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.28:build (default) on project wfswarm-circuit-breaker-parent: Execution default of goal io.fabric8:fabric8-maven-plugin:3.5.28:build failed: Cannot extract generator config: org.apache.maven.plugin.MojoExecutionException: Cannot extract main class to startup
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal io.fabric8:fabric8-maven-plugin:3.5.28:build failed: Cannot extract generator config: org.apache.maven.plugin.MojoExecutionException: Cannot extract main class to startup
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalArgumentException: Cannot extract generator config: org.apache.maven.plugin.MojoExecutionException: Cannot extract main class to startup
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.customizeConfig(BuildMojo.java:297)
	at io.fabric8.maven.docker.config.ConfigHelper.resolveImages(ConfigHelper.java:51)
	at io.fabric8.maven.docker.AbstractDockerMojo.initImageConfiguration(AbstractDockerMojo.java:308)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:215)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute(BuildMojo.java:193)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot extract main class to startup
	at io.fabric8.maven.generator.javaexec.JavaExecGenerator.getEnv(JavaExecGenerator.java:149)
	at io.fabric8.maven.generator.wildflyswarm.WildFlySwarmGenerator.getEnv(WildFlySwarmGenerator.java:45)
	at io.fabric8.maven.generator.javaexec.JavaExecGenerator.customize(JavaExecGenerator.java:122)
	at io.fabric8.maven.plugin.generator.GeneratorManager.generate(GeneratorManager.java:62)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.customizeConfig(BuildMojo.java:295)
	... 26 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by gastaldi** [comment]
@heiko-braun @kenfinnigan any clues?

**Comment by kenfinnigan** [comment]
Nothing I've seen before

**Comment by gastaldi** [comment]
This looks like a bug in the fabric8-maven-plugin. Who is in charge of this plugin that could have a look at this error?

**Comment by joshuawilson** [comment]
Looks like @jstrachan worked on it initially but I don't recognize any of the other major contributors.

**Comment by gastaldi** [comment]
Moving to Deploy team, as we believe this is an issue in the Fabric8 maven plugin

**Comment by hrishin** [comment]
@gastaldi @sbose78 @pradeepto we are looking into it. Thanks for reporting an issue.

**Comment by ldimaggi** [comment]
Closing as the quickstart was removed from OSIO.
