### ISSUE TITLE
Cannot create Che workspace for Wildfly Swarm quickstarts

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1991]
The new WildFly Swarm - HTTP and WildFly Swarm - Health Checks quickstarts build and run, but creating a new workspace fails with this error:

```

api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create:1 POST https://api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create 500 (Internal Server Error)
api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create:1 POST https://api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create 500 (Internal Server Error)
api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create:1 POST https://api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create 500 (Internal Server Error)
api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create:1 POST https://api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create 500 (Internal Server Error)
api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create:1 POST https://api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create 500 (Internal Server Error)
api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create:1 POST https://api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create 500 (Internal Server Error)
api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create:1 POST https://api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create 500 (Internal Server Error)
api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create:1 POST https://api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create 500 (Internal Server Error)
api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create:1 POST https://api.openshift.io/api/codebases/d6cff5c9-188c-4166-b318-2dafe763a0f6/create 500 (Internal Server Error)
_formulas.less:2 Response {_body: "{"errors":[{"code":"internal","detail":"Not Found"…status":"500","title":"Internal Server Error"}]}↵", status: 500, ok: false, statusText: "Internal Server Error", headers: Headers, …}
```

No errors are logged here:
https://console.rh-idev.openshift.com/console/project/dsaas-preview/browse/pods/che-44-72gwk?tab=log

**Comment by gastaldi** [comment]
Assigning to the che team to investigate.

**Comment by ibuziuk** [comment]
`Status 404 Error Not Found Message Not Found Trace
io.fabric8.che.starter.exception.StackNotFoundException: Stack with id 'WildFly Swarm' was not found
	at io.fabric8.che.starter.client.StackClient.getStack(StackClient.java:63)
	at io.fabric8.che.starter.client.WorkspaceClient.createWorkspace(WorkspaceClient.java:140)
	at io.fabric8.che.starter.client.WorkspaceClient$$FastClassBySpringCGLIB$$9ee2512d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652)
	at io.fabric8.che.starter.client.WorkspaceClient$$EnhancerBySpringCGLIB$$e4594119.createWorkspace(<generated>)
	at io.fabric8.che.starter.controller.WorkspaceController.createWorkspaceFromParams(WorkspaceController.java:168)
	at io.fabric8.che.starter.controller.WorkspaceController.createWorkspace(WorkspaceController.java:158)
	at io.fabric8.che.starter.controller.WorkspaceController.create(WorkspaceController.java:101)
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at io.fabric8.che.starter.mdc.filter.RequestFilter.doFilter(RequestFilter.java:56)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)`

@gastaldi looks like UI is passing invalid stack id to wit / che-starter (`Stack with id 'WildFly Swarm' was not found`) - valid one is `wildfly-swarm`

[1] https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-stacks/src/main/resources/stacks.json#L600

**Comment by gastaldi** [comment]
Thanks Ilya, I pushed a fix to launcher-backend. @ldimaggi can you test again in prod-preview once https://ci.centos.org/view/Devtools/job/devtools-launcher-backend-generator-build-master/105/console finishes?

**Comment by ibuziuk** [comment]
works for me on prod-preview, but will let @ldimaggi to verify & close

**Comment by gastaldi** [comment]
I updated production with the fix. @ldimaggi please retest and close this issue if your tests pass

**Comment by ldimaggi** [comment]
Closing - it's fixed in production:

![screenshot from 2018-01-24 10-13-18](https://user-images.githubusercontent.com/642621/35339821-94b0d9fc-00ef-11e8-86df-2165ee2db12e.png)


(The issue related to the "run" command missing may have returned - will investigate and log that in a separate issue.)
