### ISSUE TITLE
Springboot CRUD quickstart failed to build

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#204]
Reproduce:
* Add new project to space via quickstart
* Select Springboot CRUD
* Build in pipeline fales.

This is the repo that I worked with: I've created: https://github.com/luebken/test-springboot-crud

This is the of my jenkins log:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project test-springboot-crud: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-0.b14.el7_2.x86_64/jre/bin/java -jar /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefirebooter2942557765197514862.jar /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefire1880715196361917498tmp /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefire_08229920062567054966tmp
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project test-springboot-crud: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-0.b14.el7_2.x86_64/jre/bin/java -jar /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefirebooter2942557765197514862.jar /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefire1880715196361917498tmp /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefire_08229920062567054966tmp
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-0.b14.el7_2.x86_64/jre/bin/java -jar /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefirebooter2942557765197514862.jar /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefire1880715196361917498tmp /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefire_08229920062567054966tmp
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.RuntimeException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-0.b14.el7_2.x86_64/jre/bin/java -jar /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefirebooter2942557765197514862.jar /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefire1880715196361917498tmp /home/jenkins/workspace/test-springboot-crud_master-RTFE3XH4HDX7TZMRUQ2WR6DHH67TST4YUY4COWNQDLYPTQ5ZGMIA/target/surefire/surefire_08229920062567054966tmp
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:590)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:460)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:229)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:201)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1026)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:862)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
sh-4.2$ exit
exit
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-ui#1466

**Comment by RanjithRV** [comment]
Closing this issue as Joshua mentioned it was moved to a different repo and the issue has been closed 
https://github.com/fabric8-ui/fabric8-ui/issues/1466

**Comment by joshuawilson** [comment]
It was closed with the comment 

> Closing. Will track the original.

**Comment by joshuawilson** [comment]
In the early days we moved from one repo to another. We finally settled on this one to track all issues.

**Comment by joshuawilson** [comment]
@ldimaggi have you seen this issue?

**Comment by ldimaggi** [comment]
Just tried it - the quickstart builds for me on prod-preview and production.

**Comment by joshuawilson** [comment]
Closing, if this is still an issue please reopen.
