### ISSUE TITLE
Usage of Hawkular REST Client in "Deployments" leak Go Routines

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#2087]
Each call to https://github.com/fabric8-services/fabric8-wit/blob/master/controller/apps.go#L47 creates a new Hawkluar client under the hood which starts up a new goroutine (https://github.com/hawkular/hawkular-client-go/blob/master/metrics/client.go#L670). The client is never reused nor closed, so each client creation leaks 1 goroutine. These calls are also done in a refresh loop on the client side so it accumulates relatively quickly. 

![screenshot from 2018-01-28 20-34-42](https://user-images.githubusercontent.com/132158/35486202-dc24d2b0-046a-11e8-86d4-db2765723fb8.png)

```
goroutine 6144 [chan receive, 2 minutes]:
github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics.(*Client).sendRoutine(0xc420c50360)
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics/helpers.go:30 +0x5b
created by github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics.NewHawkularClient
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics/client.go:671 +0x427

goroutine 6268 [chan receive, 2 minutes]:
github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics.(*Client).sendRoutine(0xc420adcc00)
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics/helpers.go:30 +0x5b
created by github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics.NewHawkularClient
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics/client.go:671 +0x427

goroutine 6175 [chan receive, 2 minutes]:
github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics.(*Client).sendRoutine(0xc420ba0660)
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics/helpers.go:30 +0x5b
created by github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics.NewHawkularClient
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics/client.go:671 +0x427

goroutine 6505 [chan receive]:
github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics.(*Client).sendRoutine(0xc420ff41e0)
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics/helpers.go:30 +0x5b
created by github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics.NewHawkularClient
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/hawkular/hawkular-client-go/metrics/client.go:671 +0x427
```

**Comment by aslakknutsen** [comment]
@stooke Something for you?

**Comment by aslakknutsen** [comment]
Seems to have calmed down after the fix. Closing.

![screenshot from 2018-01-30 04-48-04](https://user-images.githubusercontent.com/132158/35547352-d550b490-0578-11e8-801d-2fe1baccfd66.png)

**Comment by ebaron** [comment]
The issue has reoccurred. Reopening to ensure the problem is fixed.
