### ISSUE TITLE
401 Client Error: Unauthorized for url: https://api.github.com/rate_limit

### ISSUE THREAD

**Issue by jpopelka** [openshiftio/openshift.io#2151]
Seeing this on prod-preview when GithubTask is run:

```python
Traceback (most recent call last):                                                                                                                                                                  
  File "<stdin>", line 1, in <module>                                                                                                                                                               
  File "/usr/lib/python3.4/site-packages/f8a_worker/defaults.py", line 151, in select_random_github_token                                                                                           
    if cls._rate_limit_exceeded(headers):                                                                                                                                                           
  File "/usr/lib/python3.4/site-packages/f8a_worker/defaults.py", line 126, in _rate_limit_exceeded                                                                                                 
    response = get_response(urljoin(cls.GITHUB_API, "rate_limit"), headers=headers)                                                                                                                 
  File "/usr/lib/python3.4/site-packages/f8a_worker/utils.py", line 666, in get_response                                                                                                            
    raise TaskError(message) from err                                                                                                                                                               
f8a_worker.errors.TaskError: Failed to get results from https://api.github.com/rate_limit with 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
```

**Comment by jpopelka** [comment]
https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1212
