### ISSUE TITLE
 'GreetingServiceTest' from wildfly booster is failing in Che

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#2152]
Steps to reproduce:
- start workspace with wildfly booster quickstart
- execute build command

```
[INFO] Running io.openshift.booster.GreetingServiceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.184 s <<< FAILURE! - in io.openshift.booster.GreetingServiceTest
[ERROR] io.openshift.booster.GreetingServiceTest  Time elapsed: 1.183 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: WFSWARM0012: Cannot identify FileSystemLayout for given path: /projects/xzxz
Caused by: java.lang.IllegalArgumentException: WFSWARM0012: Cannot identify FileSystemLayout for given path: /projects/xzxz
```

**Comment by lordofthejars** [comment]
I found this issue running on `openshift.io`. If I run `mvn clean install` locally it runs correctly this test that is failing on Che.

**Comment by eivantsov** [comment]
```
Resolving 0 out of 596 artifacts
Fri Feb 02 08:24:20 UTC 2018 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.037 s <<< FAILURE! - in io.openshift.booster.GreetingServiceTest
[ERROR] io.openshift.booster.GreetingServiceTest  Time elapsed: 10.036 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
Caused by: org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
```
I get a different error for some reason.

**Comment by bartoszmajsak** [comment]
@eivantsov is that the whole log you are getting? That's a bit blurry to reason what is really going on.

**Comment by eivantsov** [comment]
`scl enable rh-maven33 'cd ${current.project.path} && mvn clean install'` if you try this command you will get past the error but hit another one.

As you can see, maven is invoked in root dir rather than path to pom.xml is passed as an arg

**Comment by bartoszmajsak** [comment]
Provided more details in #2262 to only realize that it's a duplicate of this issue, so pasting it here to avoid looping through tabs:

#### Steps to reproduce

1. Run GreetingServiceTest (either from the IDE or from Maven `mvn test -Dtest=GreetingServiceTest`)

##### Prerequisites if starting from scratch:
1. Select WildFly Swarm Http Booster as a quickstart to import
2. **Optionally in Che:** Comment out Cube dependency in the `pom.xml`
3. **Optionally in Che:** Delete `OpenshiftIT` test (there is another potential issue with Cube on OSIO/Che we are investigating)

(alternatively, clone this repository https://github.com/lordofthejars/swarmq where all the steps are already applied)

#### Detailed stack traces

<details>
<summary>Error while running Che (after clean build of the project)</summary>

```
org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
	at org.wildfly.swarm.arquillian.adapter.WildFlySwarmContainer.deploy(WildFlySwarmContainer.java:92)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:161)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:128)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:271)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deploy(ContainerDeployController.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createDeploymentContext(ContainerDeploymentContextHandler.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.container.impl.client.container.DeploymentExceptionHandler.verifyExpectedExceptionDuringDeploy(DeploymentExceptionHandler.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$1.perform(ContainerDeployController.java:95)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$1.perform(ContainerDeployController.java:80)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.forEachDeployment(ContainerDeployController.java:263)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.forEachManagedDeployment(ContainerDeployController.java:239)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deployManaged(ContainerDeployController.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeClass(EventTestRunnerAdaptor.java:87)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:202)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:431)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:55)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:219)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:167)
	at org.eclipse.che.junit.junit4.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.che.junit.junit4.CheJUnitCoreRunner.run(CheJUnitCoreRunner.java:56)
	at org.eclipse.che.junit.junit4.CheJUnitLauncher.main(CheJUnitLauncher.java:29)
Caused by: org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
	at org.wildfly.swarm.arquillian.adapter.UberjarSimpleContainer.start(UberjarSimpleContainer.java:306)
	at org.wildfly.swarm.arquillian.adapter.WildFlySwarmContainer.deploy(WildFlySwarmContainer.java:79)
	... 84 more
```
</details>

<details>
<summary>Error while running from Maven (mvn test -Dtest=GreetingServiceTest)</summary>

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.openshift.booster.GreetingServiceTest
Resolving 0 out of 563 artifacts
Wed Feb 14 10:45:11 UTC 2018 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.323 s <<< FAILURE! - in io.openshift.booster.GreetingServiceTest
[ERROR] io.openshift.booster.GreetingServiceTest  Time elapsed: 10.322 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
Caused by: org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
```
</details>

**Comment by eivantsov** [comment]
@ibuziuk I have run tests on Docker and OpenShift, without Che at all. Tests fail with exact same error.

Tests were held on a local Docker and Origin, as well as on OSO Pro. I can share OpenShift deployment yaml so that you can quickly test it locally as well.

It is interesting that commands:

`mvn clean install` in the project root
and
`mvn clean install -f /path/to/project`

cause different behavior. The former just makes tests hang with a message:

```
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.openshift.booster.GreetingServiceTest
Resolving 271 out of 596 artifacts
```

We should probably get some input from arquillian team?

**Comment by l0rd** [comment]
@eivantsov That makes sense with what I have observed. It doesn't look like OpenShift kills the process because it's using too much memory (there would be an evidence in the openshfit events). What we should looked at are the `JAVA_OPTS` memory settings more than the infrastructure configuration.

**Comment by l0rd** [comment]
We never really finished to tune `JAVA_OPTS` for workspaces https://github.com/redhat-developer/rh-che/issues/451 and the time may have come to work on that.

**Comment by ibuziuk** [comment]
@slemeur this is the last P0 that is not addressed from che side. Are we ok to add flag for skipping tests in wildfly commands as a temp workaround ? I'm afraid we will not be able to provide better fix before summit

**Comment by slemeur** [comment]
Fine for me as a temporary solution.

**Comment by ibuziuk** [comment]
@maxandersen do you happen to know who is the wildfly quickstart mainatainer ?

**Comment by slemeur** [comment]
We figured out that even by skipping the test from the che command, we are not able to build the application.

See: https://github.com/openshiftio/openshift.io/issues/3463

**Comment by ibuziuk** [comment]
PR with updating wildfly recipe is send - let's see if it improve the situation

**Comment by ibuziuk** [comment]
Unfortumately, nothing changed after stack rebuilding :-(

**Comment by slemeur** [comment]
We would have a workaround provided in https://github.com/openshiftio/openshift.io/issues/3463#issuecomment-386812715

**Comment by ibuziuk** [comment]
Workaround with disabling tests is already available on prod-preview - https://github.com/openshiftio/openshift.io/issues/3463#issuecomment-386893023

**Comment by ibuziuk** [comment]
Adding `area/launcher/runtime/wildfly` label. Created a wildfly issue for failing tests when building using -f option https://issues.jboss.org/browse/WFARQ-45 cc: @gastaldi @kenfinnigan

**Comment by kenfinnigan** [comment]
Moved the issue to https://issues.jboss.org/browse/THORN-2049 as it's not to do with WildFly or Arquillian, it's to do with WildFly Swarm (now Thorntail)

**Comment by bartoszmajsak** [comment]
@ibuziuk I provided PR for the `-f` issue. Not really sure which issues from this huge snowball it will fix, so can we sync on how to verify that in Che?

**Comment by dkranz** [comment]
Is there any way to work around this and continue with the Getting Started?

**Comment by ibuziuk** [comment]
@bartoszmajsak sorry for the late response. Basically, `-f`  should fix the first part of the problem since thornail does not handles `-f` option. However, I see that PR is still not merged upstream so we still can not run the sample via coommand
@dkranz current workaround is executing the tests via run command which disables tests during the build or skipping tests via `-DskipTests=true` in terminal

**Comment by fabineri** [comment]
A solved passing system property and force a layout

System.setProperty("thorntail.filesystem.layout.class", "org.wildfly.swarm.internal.MavenFileSystemLayout");

A see the class FileSystemLayout.CUSTOM_LAYOUT_CLASS implementation. sorry my english
