### ISSUE TITLE
[3] psycopg2.IntegrityError: insert or update on table "package_worker_results" violates foreign key constraint "package_worker_results_package_analysis_id_fkey"

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2218]
_From @jpopelka on June 7, 2017 15:22_

```
2017-06-07 13:28:26,033 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[4f4bc5dc-1942-4354-9cd8-835d6d4f54d9] raised unexpected: IntegrityError('(psycopg2.IntegrityError) insert or update on table "package_worker_results" violates foreign key constraint "package_worker_results_package_analysis_id_fkey"\nDETAIL:  Key (package_analysis_id)=(432710) is not present in table "package_analyses".\n',)
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: insert or update on table "package_worker_results" violates foreign key constraint "package_worker_results_package_analysis_id_fkey"
DETAIL:  Key (package_analysis_id)=(432710) is not present in table "package_analyses".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 124, in run
    StoragePool.set(node_args, flow_name, task_name, self.request.id, result)
  File "/usr/lib/python3.4/site-packages/selinon/storagePool.py", line 137, in set
    record_id = storaption:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 124, in run
    StoragePool.set(node_args, flow_name, task_name, self.request.id, result)
  File "/usr/lib/python3.4/site-packages/selinon/storagePool.py", line 137, in set
    record_id = storage.store(node_args, flow_name, storage_task_name, task_id, result)
  File "/usr/lib/python3.4/site-packages/cucoslib/storages/postgres_base.py", line 102, in store
    PostgresBase.session.commit()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 2137, in flush
    self._flush(objects)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 2257, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 2221, in _flush
    flush_context.execute()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 176, in save_obj
    mapper, table, insert)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 830, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) insert or update on table "package_worker_results" violates foreign key constraint "package_worker_results_package_analysis_id_fkey"
DETAIL:  Key (package_analysis_id)=(432710) is not present in table "package_analyses".
 [SQL: 'INSERT INTO package_worker_results (package_analysis_id, worker, worker_id, external_request_id, task_result, error) VALUES (%(package_analysis_id)s, %(worker)s, %(worker_id)s, %(external_request_id)s, %(task_result)s, %(error)s) RETURNING package_worker_results.id'] [parameters: {'external_request_id': None, 'error': False, 'package_analysis_id': 432710, 'worker': 'InitPackageFlow', 'worker_id': '4f4bc5dc-1942-4354-9cd8-835d6d4f54d9', 'task_result': '{"ecosystem": "maven", "_release": "maven:org.xwiki.commons:xwiki-commons-legacy-configuration:None", "force": false, "name": "org.xwiki.commons:xwik ... (203 characters truncated) ... /xwiki-commons/tree/master/xwiki-commons-pom/xwiki-commons-core/xwiki-commons-legacy/xwiki-commons-legacy-configuration/", "force_graph_sync": false}'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: insert or update on table "package_worker_results" violates foreign key constraint "package_worker_results_package_analysis_id_fkey"
DETAIL:  Key (package_analysis_id)=(432710) is not present in table "package_analyses".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 162, in run
    and not StoragePool.set_error(node_args, flow_name, task_name, self.request.id, exc_info):
  File "/usr/lib/python3.4/site-packages/selinon/storagePool.py", line 167, in set_error
    record_id = storage.store_error(node_args, flow_name, storage_task_name, task_id, exc_info)
  File "/usr/lib/python3.4/site-packages/cucoslib/storages/postgres_base.py", line 115, in store_error
    PostgresBase.session.commit()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 2137, in flush
    self._flush(objects)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 2257, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 2221, in _flush
    flush_context.execute()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 176, in save_obj
    mapper, table, insert)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 830, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) insert or update on table "package_worker_results" violates foreign key constraint "package_worker_results_package_analysis_id_fkey"
DETAIL:  Key (package_analysis_id)=(432710) is not present in table "package_analyses".
[SQL: 'INSERT INTO package_worker_results (package_analysis_id, worker, worker_id, external_request_id, task_result, error) VALUES (%(package_analysis_id)s, %(worker)s, %(worker_id)s, %(external_request_id)s, %(task_result)s, %(error)s) RETURNING package_worker_results.id'] [parameters: {'worker': 'InitPackageFlow', 'error': False, 'package_analysis_id': 432710, 'external_request_id': None, 'worker_id': '4f4bc5dc-1942-4354-9cd8-835d6d4f54d9', 'task_result': 'null'}]
```

_Copied from original issue: fabric8-analytics/fabric8-analytics-worker#43_

**Comment by msrb** [comment]
_From @fridex on June 12, 2017 12:50_

Was this issue found in the cluster?

**Comment by msrb** [comment]
_From @jpopelka on June 12, 2017 12:59_

Yes, I can still (*2017-06-12 12:43:55,589*) see it on `bayesian-production`

**Comment by msrb** [comment]
_From @fridex on June 12, 2017 13:11_

Thanks, I think the reason why we see this are old messages in the queue where `InitPackageFlow` was not run and `package_analysis_id` tends to be old `analysis_id` as it matches `document_id` - this was introduced in https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/27

Are we sure that all scheduled messages were processed to this day? Especially `github_details` task.

CC @msrb

**Comment by msrb** [comment]
_From @fridex on August 3, 2017 12:31_

I haven't seen this issue for a while. I think it was caused by introduction of package level flows as stated above. Closing but feel free to reopen if this issue persists.

**Comment by msrb** [comment]
_From @jpopelka on August 15, 2017 9:40_

Bad news, I can still see this on prod when ingesting nugets.

**Comment by msrb** [comment]
_From @fridex on August 16, 2017 8:26_

Tracing this issue a bit - my observations:

This issue is caused by InitPackageFlow based on `worker` field. The error in `store_error` shouldn't occur as we do not store errors of init tasks (see https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/storages/postgres_base.py#L118 ).

The error with non-existing package_analyses_id is also suspicious as this record should be created in the `InitPackageFlow` before results of this task are written to database - https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/init_package_flow.py#L102

**Comment by msrb** [comment]
This looks fishy: https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/init_package_flow.py#L84-L95

**Comment by msrb** [comment]
@pkajaba any luck with this one?

**Comment by msrb** [comment]
@pkajaba I am actually still able to reproduce the issue locally.

With latest worker changes, if I first scan `maven/net.iharder:base64/2.3.9` and then `maven/net.iharder:base64/2.3.8` immediately after that (but without `force=True`), then I see the exception in the logs.

**Comment by msrb** [comment]
PR: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/588

**Comment by msrb** [comment]
Fixed in prod.
