### ISSUE TITLE
[3] No such bucket error encountered

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2219]
_From @tuxdna on January 31, 2018 11:34_

Start the import :

http://localhost:32000/api/v1/component-analyses/maven/org.apache.tomcat:tomcat-servlet-api/8.5.6

Data import into graph fails for a  package: /maven/org.apache.tomcat:tomcat-servlet-api/8.5.6

```
data-model-importer_1   | --------------------------------------------------------------------------------
data-model-importer_1   | INFO in rest_api [/src/rest_api.py:94]:
data-model-importer_1   | Ingesting the given list of EPVs - [{"ecosystem": "maven", "version": "8.5.6", "name": "org.apache.tomcat:tomcat-servlet-api"}]
data-model-importer_1   | --------------------------------------------------------------------------------
data-model-importer_1   | ERROR:data_importer:import_epv() failed with error: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist
data-model-importer_1   | ERROR:data_importer:Traceback for latest failure in import call: Traceback (most recent call last):
data-model-importer_1   |   File "/src/data_importer.py", line 164, in import_epv_http
data-model-importer_1   |     prefix=pkg_key_prefix))
data-model-importer_1   |   File "/src/data_source/s3_data_source.py", line 66, in list_files
data-model-importer_1   |     for obj in bucket.objects.filter(Prefix=prefix):
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
data-model-importer_1   |     for page in self.pages():
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/boto3/resources/collection.py", line 166, in pages
data-model-importer_1   |     for page in pages:
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
data-model-importer_1   |     response = self._make_request(current_kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
data-model-importer_1   |     return self._method(**current_kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
data-model-importer_1   |     return self._make_api_call(operation_name, kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 615, in _make_api_call
data-model-importer_1   |     raise error_class(parsed_response, operation_name)
data-model-importer_1   | NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist
data-model-importer_1   | [2018-01-31 11:29:48 +0000] [70] [ERROR] Error handling request /api/v1/ingest_to_graph
data-model-importer_1   | Traceback (most recent call last):
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/async.py", line 56, in handle
data-model-importer_1   |     self.handle_request(listener_name, req, client, addr)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
data-model-importer_1   |     super(GeventWorker, self).handle_request(*args)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/async.py", line 107, in handle_request
data-model-importer_1   |     respiter = self.wsgi(environ, resp.start_response)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1997, in __call__
data-model-importer_1   |     return self.wsgi_app(environ, start_response)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
data-model-importer_1   |     response = self.handle_exception(e)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
data-model-importer_1   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
data-model-importer_1   |     reraise(exc_type, exc_value, tb)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
data-model-importer_1   |     response = self.full_dispatch_request()
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
data-model-importer_1   |     rv = self.handle_user_exception(e)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
data-model-importer_1   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
data-model-importer_1   |     reraise(exc_type, exc_value, tb)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
data-model-importer_1   |     rv = self.dispatch_request()
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
data-model-importer_1   |     return self.view_functions[rule.endpoint](**req.view_args)
data-model-importer_1   |   File "/src/rest_api.py", line 102, in ingest_to_graph
data-model-importer_1   |     report = data_importer.import_epv_from_s3_http(list_epv=input_json)
data-model-importer_1   |   File "/src/data_importer.py", line 214, in import_epv_from_s3_http
data-model-importer_1   |     list_epv, select_doc)
data-model-importer_1   |   File "/src/data_importer.py", line 199, in import_epv_http
data-model-importer_1   |     raise RuntimeError(msg)
data-model-importer_1   | RuntimeError: import_epv() failed with error: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist
data-model-importer_1   | --------------------------------------------------------------------------------
data-model-importer_1   | INFO in rest_api [/src/rest_api.py:94]:
data-model-importer_1   | Ingesting the given list of EPVs - [{"ecosystem": "maven", "version": null, "name": "org.apache.tomcat:tomcat-servlet-api"}]

```

_Copied from original issue: fabric8-analytics/fabric8-analytics-data-model#74_

**Comment by msrb** [comment]
_From @jpopelka on January 31, 2018 11:40_

Yeah, I think I've seen that too.
Would be nice if the data_importer could cope with the non-existing bucket.
But if it really needs the bucket to be there,
then for local testing we have [fabric8-analytics-cvedb-s3-dump-docker](https://github.com/fabric8-analytics/fabric8-analytics-cvedb-s3-dump-docker),
which uploads data to minio (local S3 equivalent) when starting whole f8a via docker-compose.

**Comment by msrb** [comment]
_From @tuxdna on February 5, 2018 19:54_

I could reproduce the error again. However it seems like the bucket gets created once we analyze some other package, and later force analyze ( using curl -X POST ) the first package again. 

Therefore, the bucket is getting created after it is required the first time by data importer.

**Comment by msrb** [comment]
> Therefore, the bucket is getting created after it is required the first time by data importer.

This is weird, isn't it? It sounds like some logical error somewhere. Do we know what bucket is missing?

**Comment by tuxdna** [comment]
```
worker-ingestion_1      | 2018-03-08 11:54:55,199 [INFO] GraphImporterTask: Invoke graph importer at url: 'http://data-model-importer:9192/api/v1/ingest_to_graph' for [{'ecosystem': 'maven', 'name': 'org.apache.tomcat:tomcat-servlet-api', 'version': None}]
data-model-importer_1   | --------------------------------------------------------------------------------
data-model-importer_1   | INFO in rest_api [/src/rest_api.py:103]:
data-model-importer_1   | Ingesting the given list of EPVs - [{"ecosystem": "maven", "version": null, "name": "org.apache.tomcat:tomcat-servlet-api"}]
data-model-importer_1   | --------------------------------------------------------------------------------
bayesian-gremlin-http   | 463474 [gremlin-server-exec-6] WARN  org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler  - Invalid request - responding with 500 Internal Server Error and Error encountered evaluating script: g.V().has('ecosystem','maven').has('name','org.apache.tomcat:tomcat-servlet-api').properties('tokens').drop().iterate();pkg = g.V().has('ecosystem','maven').has('name', 'org.apache.tomcat:tomcat-servlet-api').tryNext().orElseGet{graph.addVertex('ecosystem', 'maven', 'name', 'org.apache.tomcat:tomcat-servlet-api', 'vertex_label', 'Package')};pkg.property('last_updated', 1520510095.36);pkg.property('tokens', 'org'); pkg.property('tokens', 'apache'); pkg.property('tokens', 'tomcat'); pkg.property('tokens', 'tomcat'); pkg.property('tokens', 'servlet'); pkg.property('tokens', 'api');pkg.property('libio_latest_release', '1518035035.0');pkg.property('libio_dependents_projects', '71');pkg.property('libio_dependents_repos', '2690');pkg.property('libio_total_releases', '145');pkg.property('libio_latest_version', '8.0.50');
bayesian-gremlin-http   | java.lang.NullPointerException
bayesian-gremlin-http   | 	at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.verifyAttribute(StandardTitanTx.java:562)
bayesian-gremlin-http   | 	at com.thinkaurelius.titan.graphdb.query.QueryUtil.addConstraint(QueryUtil.java:219)
bayesian-gremlin-http   | 	at com.thinkaurelius.titan.graphdb.query.QueryUtil.constraints2QNF(QueryUtil.java:209)
bayesian-gremlin-http   | 	at com.thinkaurelius.titan.graphdb.query.graph.GraphCentricQueryBuilder.constructQueryWithoutProfile(GraphCentricQueryBuilder.java:199)
bayesian-gremlin-http   | 	at com.thinkaurelius.titan.graphdb.query.graph.GraphCentricQueryBuilder.constructQuery(GraphCentricQueryBuilder.java:188)
bayesian-gremlin-http   | 	at com.thinkaurelius.titan.graphdb.query.graph.GraphCentricQueryBuilder.vertices(GraphCentricQueryBuilder.java:151)
bayesian-gremlin-http   | 	at com.thinkaurelius.titan.graphdb.tinkerpop.optimize.TitanGraphStep.lambda$new$0(TitanGraphStep.java:48)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:136)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.hasNext(ExpandableStepIterator.java:42)
bayesian-gremlin-http   | 	at com.thinkaurelius.titan.graphdb.tinkerpop.optimize.TitanPropertiesStep.initialize(TitanPropertiesStep.java:74)
bayesian-gremlin-http   | 	at com.thinkaurelius.titan.graphdb.tinkerpop.optimize.TitanPropertiesStep.processNextStart(TitanPropertiesStep.java:93)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.iterate(Traversal.java:175)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal.iterate(GraphTraversal.java:1505)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal$Admin.iterate(GraphTraversal.java:175)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.iterate(DefaultGraphTraversal.java:48)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal$Admin$iterate.call(Unknown Source)
bayesian-gremlin-http   | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
bayesian-gremlin-http   | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
bayesian-gremlin-http   | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
bayesian-gremlin-http   | 	at Script5.run(Script5.groovy:1)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:619)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:448)
bayesian-gremlin-http   | 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines.eval(ScriptEngines.java:119)
bayesian-gremlin-http   | 	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:287)
bayesian-gremlin-http   | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
bayesian-gremlin-http   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
bayesian-gremlin-http   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
bayesian-gremlin-http   | 	at java.lang.Thread.run(Thread.java:748)
data-model-importer_1   | ERROR:data_importer:The import failed: 'status'
data-model-importer_1   | ERROR:data_importer:Traceback for latest failure in import call: Traceback (most recent call last):
data-model-importer_1   |   File "/src/data_importer.py", line 117, in _import_keys_from_s3_http
data-model-importer_1   |     if resp['status']['code'] == 200:
data-model-importer_1   | KeyError: 'status'
data-model-importer_1   | 
data-model-importer_1   | ERROR:data_importer:
data-model-importer_1   |         Report from import_epv():
data-model-importer_1   |         The import failed: 'status'
data-model-importer_1   |         Total number of EPVs imported: 0
data-model-importer_1   |         The last successfully imported EPV: None
data-model-importer_1   |     
worker-ingestion_1      | {"task_name": "PackageGraphImporterTask", "node_args": {"_release": "maven:org.apache.tomcat:tomcat-servlet-api:None", "force": false, "_audit": {"started_at": "2018-03-08T11:52:30.998381", "version": "v1", "ended_at": "2018-03-08T11:52:31.068924"}, "force_graph_sync": true, "url": null, "ecosystem": "maven", "name": "org.apache.tomcat:tomcat-servlet-api", "document_id": 1}, "dispatcher_id": "eb9e3ac1-4f20-40a3-9258-38d11f151605", "retried_count": 0, "queue": "tuxdna_ingestion_GraphImporterTask_v0", "flow_name": "bayesianPackageFlow", "what": "Traceback (most recent call last):\n  File \"/usr/lib/python3.4/site-packages/selinon/task_envelope.py\", line 114, in run\n    result = task.run(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 54, in run\n    result = self.execute(node_args)\n  File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/graph_importer.py\", line 63, in execute\n    raise RuntimeError(\"Failed to invoke graph import at '%s' for %s\" % (endpoint, param))\nRuntimeError: Failed to invoke graph import at 'http://data-model-importer:9192/api/v1/ingest_to_graph' for [{'ecosystem': 'maven', 'name': 'org.apache.tomcat:tomcat-servlet-api', 'version': None}]\n", "event": "TASK_FAILURE", "parent": {"PackageResultCollector": "a906af0d-b6c5-4800-bec3-7dc8b3ba2482"}, "task_id": "abef0db4-2ebb-46fc-85a8-65b1ba34dbdc"}


```

**Comment by msrb** [comment]
During ingestion, we actually call data-importer twice. Once for version-level data and second time for package-level data (but that's much later, only after package-level analysis is done). I *think* data-importer checks both buckets when we call it. If people run this locally, on docker-compose, then we call data-importer for version-level data, but package-level data are not there in the bucket yet. And what's more important, if people don't have any data in minio yet (except those version-level data that we just gathered), then the package-level bucket doesn't exist yet. Because we create it only when we actually need it.

**Comment by tuxdna** [comment]
Also observed this in production instance:

```



INFO in rest_api [/src/rest_api.py:103]:
  | Ingesting the given list of EPVs - [{"ecosystem": "npm", "version": "1.0.0", "name": "react-ws"}, {"ecosystem": "npm", "version": "0.0.1", "name": "caetano-react-base"}, {"ecosystem": "npm", "version": "0.0.2", "name": "caetano-react-base"}, {"ecosystem": "npm", "version": "0.0.1", "name": "portman"}, {"ecosystem": "npm", "version": "0.0.1", "name": "@mrdev023/module_encrypt"}, {"ecosystem": "npm", "version": "0.1.0", "name": "canvas-image-sequencer"}, {"ecosystem": "npm", "version": "0.1.0", "name": "@rebelcode/vc-toggleable"}, {"ecosystem": "npm", "version": "1.1.3", "name": "electron-sentry-modtest"}, {"ecosystem": "npm", "version": "0.1.0", "name": "@worldia/eslint-config"}, {"ecosystem": "npm", "version": "3.0.0", "name": "sails-hook-grunt"}]
  | --------------------------------------------------------------------------------
  | --------------------------------------------------------------------------------
  | INFO in rest_api [/src/rest_api.py:52]:
  | /api/v1/pending - {'ecosystem': [u'npm'], 'limit': [u'10'], 'offset': [u'1720']}
  | --------------------------------------------------------------------------------
  | --------------------------------------------------------------------------------
  | INFO in rest_api [/src/rest_api.py:61]:
  | params - {'ecosystem': u'npm', 'version': None, 'limit': u'10', 'offset': u'1720', 'package': None}
  | --------------------------------------------------------------------------------
  | ERROR:data_importer:The import failed: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
  | ERROR:data_importer:Traceback for latest failure in import call: Traceback (most recent call last):
  | File "/src/data_importer.py", line 84, in _import_keys_from_s3_http
  | first_obj = _first_key_info(data_source, first_key, config.AWS_EPV_BUCKET)
  | File "/src/data_importer.py", line 38, in _first_key_info
  | t = data_source.read_json_file(first_key, bucket_name)
  | File "/src/data_source/s3_data_source.py", line 45, in read_json_file
  | obj = self.s3_resource.Object(bucket_name, filename).get()['Body'].read()
  | File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
  | response = action(self, *args, **kwargs)
  | File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
  | response = getattr(parent.meta.client, operation_name)(**params)
  | File "/usr/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
  | return self._make_api_call(operation_name, kwargs)
  | File "/usr/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
  | raise error_class(parsed_response, operation_name)
  | NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
 


```

**Comment by msrb** [comment]
@tuxdna Looks like multiple different issues here. But we want to fix them all, of course :)

**Comment by tuxdna** [comment]
Also need to fix this issue:

- [ ]  https://github.com/fabric8-analytics/fabric8-analytics-data-model/issues/122

**Comment by tuxdna** [comment]
Another blocker:

 

- [ ] https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/570

**Comment by tuxdna** [comment]
This changes fix the issue for me:

- [ ] https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/127

- [ ] https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/577

**Comment by tuxdna** [comment]
Graph importer gets called after results collector for both Package and Version. However it is also called at other places:

https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/bc61b9abe6b3d4421326a413b2ef71f023f07ee4/f8a_worker/dispatcher/flows/bayesianFlow.yml#L28-L37

```
        - from: 'InitAnalysisFlow'
          to: 'GraphImporterTask'
          condition:
            and:
              - not:
                  <<: *shouldScheduleAnalysisCheck
              - name: 'argsFieldEqual'
                args:
                  key: 'force_graph_sync'
                  value: true
```

and https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/bc61b9abe6b3d4421326a413b2ef71f023f07ee4/f8a_worker/dispatcher/flows/bayesianPackageFlow.yml#L54-L62

```
          to: 'PackageGraphImporterTask'
          condition:
            and:
              - not:
                  <<: *shouldSchedulePackageAnalysisCheck
              - name: 'argsFieldEqual'
                args:
                  key: 'force_graph_sync'
                  value: true
```


After many attempts to change `nowait` and uncommenting / commentiong the above, the bug still persists. It only moves from either Package causing NoSuchBucket or Version causing NoSuchBucket error. 

However if you look at the image below, one thing is clear that the flows definition is causing `GraphImporter` task to be called immediately after `InitAnalysisFlow`.

![screenshot from 2018-03-22 17-11-23](https://user-images.githubusercontent.com/52947/37768799-e16bdc24-2df4-11e8-85f5-5725fdd64258.png)

**Comment by tuxdna** [comment]
Here is the notebook: https://gist.github.com/tuxdna/b49a3ea484177a0cb53c4960ef9b6c59#file-gantt_charts-ipynb

**Comment by msrb** [comment]
Lowering the severity as this issue is not affecting staging/production.

**Comment by msrb** [comment]
@tuxdna Do we agree that the problem here is that data-importer tries to check both buckets when analysis is only partially done (component-level done, package-level in progress)?
