### ISSUE TITLE
[CVEDBSyncTask] dependency-check.sh --updateonly ended with 248

### ISSUE THREAD

**Issue by jpopelka** [openshiftio/openshift.io#2222]
I've spotted the following on **prod-preview** couple times, so it's probably not a one-time issue:

{"task_id": "680a9129-890d-4b67-b9ed-04e1b2f64f33", "node_args": {"job_id": "cveCheckJob", "only_already_scanned": true, "ignore_modification_time": false}, "parent": {}, "queue": "STAGE_ingestion_CVEDBSyncTask_v0", "task_name": "CVEDBSyncTask", "flow_name": "cveCheckFlow", "dispatcher_id": "57ce1748-1d8a-4f40-8133-0686d58c97f2", "event": "TASK_START"}
  | 2018-02-11 19:27:11,190 [WARNING] f8a_worker.utils: command ['/opt/dependency-check/bin/dependency-check.sh', '--updateonly', '--data', '/tmp/tmp152kkh6q'] ended with 248
  | [INFO] Checking for updates
  | [INFO] starting getUpdatesNeeded() ...
  | [INFO] NVD CVE requires several updates; this could take a couple of minutes.
  | [INFO] Download Started for NVD CVE - 2002
  | [INFO] Download Started for NVD CVE - 2003
  | [INFO] Download Started for NVD CVE - 2004
  | [INFO] Download Started for NVD CVE - 2005
  | [INFO] Download Started for NVD CVE - 2006
  | [INFO] Download Started for NVD CVE - 2007
  | [INFO] Download Complete for NVD CVE - 2003  (2475 ms)
  | [INFO] Download Started for NVD CVE - 2008
  | [INFO] Processing Started for NVD CVE - 2003
  | [INFO] Download Complete for NVD CVE - 2005  (3803 ms)
  | [INFO] Download Started for NVD CVE - 2009
  | [INFO] Processing Started for NVD CVE - 2005
  | [INFO] Download Complete for NVD CVE - 2004  (4683 ms)
  | [INFO] Download Started for NVD CVE - 2010
  | [INFO] Processing Started for NVD CVE - 2004
  | [INFO] Download Complete for NVD CVE - 2002  (5286 ms)
  | [INFO] Download Started for NVD CVE - 2011
  | [INFO] Processing Started for NVD CVE - 2002
  | [INFO] Download Complete for NVD CVE - 2007  (9501 ms)
  | [INFO] Download Complete for NVD CVE - 2006  (10006 ms)
  | [INFO] Download Started for NVD CVE - 2012
  | [INFO] Download Started for NVD CVE - 2013
  | [INFO] Download Complete for NVD CVE - 2008  (9200 ms)
  | [INFO] Download Started for NVD CVE - 2014
  | [INFO] Download Complete for NVD CVE - 2009  (10914 ms)
  | [INFO] Download Started for NVD CVE - 2015
  | [INFO] Download Complete for NVD CVE - 2010  (12292 ms)
  | [INFO] Download Started for NVD CVE - 2016
  | [WARN] An exception occurred downloading NVD CVE - 2013
  | Some CVEs may not be reported.
  | [INFO] Download Started for NVD CVE - 2017
  | [WARN] An exception occurred downloading NVD CVE - 2012
  | Some CVEs may not be reported.
  | [INFO] Download Started for NVD CVE - 2018
  | [WARN] An exception occurred downloading NVD CVE - 2014
  | Some CVEs may not be reported.
  | [INFO] Download Started for NVD CVE - Modified
  | [WARN] An exception occurred downloading NVD CVE - 2011
  | Some CVEs may not be reported.
  | [WARN] An exception occurred downloading NVD CVE - 2015
  | Some CVEs may not be reported.
  | [WARN] Download Failed for NVD CVE - 2017
  | Some CVEs may not be reported.
  | [INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
  | [INFO] Processing Started for NVD CVE - 2007
  | [INFO] Processing Started for NVD CVE - 2006
  | [INFO] Processing Started for NVD CVE - 2008
  | [INFO] Processing Started for NVD CVE - 2009
  | [WARN] An exception occurred downloading NVD CVE - 2018
  | Some CVEs may not be reported.
  | [WARN] An exception occurred downloading NVD CVE - 2016
  | Some CVEs may not be reported.
  | [ERROR] The download was interrupted; unable to complete the update
  | [INFO] Download Complete for NVD CVE - Modified  (2801 ms)
  | [WARN] An exception occurred downloading NVD CVE - Modified
  | Some CVEs may not be reported.

EDIT: on dev cluster the process is simply killed (unknown reasons) without any errors

**Comment by jpopelka** [comment]
Checking the memory consumption: 
`docker stats` claims the container needs  max 1.4GiB when updating the DB so the current memory limit 1.5GiB should be fine.

**Comment by msrb** [comment]
Good catch 👍 

Older issue with similar symptoms: https://github.com/jeremylong/DependencyCheck/issues/523

**Comment by jpopelka** [comment]
I have not been able to reproduce this on dev cluster.

On dev cluster I see that the process is killed everytime - tried to raise the memory limit to 4GB, but still the same - and I haven't found how to debug it further since dmesg/journalctl don't work in non-privileged container.

**Comment by jpopelka** [comment]
Giving up for now.

The upstream issue which Michal references talks about disabled EC, ECDHE, ECDH algorithms in openJDK, but the version in worker image should be OK (and also if it was wrong it'd probably fail when running locally too as it runs in container, right ?):
```
>>>docker run -ti registry.devshift.net/bayesian/cucos-worker java -version
openjdk version "1.8.0_151"

>>>docker run -ti registry.devshift.net/bayesian/cucos-worker grep -n -A1 "jdk.tls.disabledAlgorithms" /usr/lib/jvm/java/jre/lib/security/java.security
624:jdk.tls.disabledAlgorithms=SSLv3, RC4, MD5withRSA, DH keySize < 768, \
625-    EC keySize < 224
```

No idea why the process is killed on dev cluster though.

**Comment by msrb** [comment]
@jpopelka I think what's worth trying is to simply delete the cached DB from S3 and let the job to recreate it from scratch again.

**Comment by jpopelka** [comment]
Nice idea.
Tested and this time it was the same as on dev cluster, i.e. the process was killed (ended with -9)

**Comment by msrb** [comment]
@jpopelka killed in staging?

**Comment by jpopelka** [comment]
Yes, in staging the process is killed when pulling the NVD db from scratch.

**Comment by jpopelka** [comment]
Looks like "No space left on device" is the problem.

```
$ mkdir /tmp/abcd
$ cd /opt/dependency-check/bin/
$ ./dependency-check.sh --updateonly --data /tmp/abcd
...
[INFO] Download Complete for NVD CVE - 2016  (8899 ms)
[WARN] An exception occurred downloading NVD CVE - 2017
Some CVEs may not be reported.
[ERROR] The download was interrupted; unable to complete the update
$ cat /tmp/abcd/dc.trace.db
2018-02-22 13:57:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: Stream Closed"; "/tmp/abcd/dc.h2.db" [90031-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.message.DbException.convertIOException(DbException.java:330)
        at org.h2.store.FileStore.write(FileStore.java:331)
        at org.h2.store.PageStore.writePage(PageStore.java:1369)
        at org.h2.store.PageStreamData.write(PageStreamData.java:106)
        at org.h2.store.PageOutputStream.storePage(PageOutputStream.java:147)                                                                                                                       
        at org.h2.store.PageOutputStream.write(PageOutputStream.java:130)                                                                                                                           
        at org.h2.store.PageLog.write(PageLog.java:551)                                                                                                                                             
        at org.h2.store.PageLog.commit(PageLog.java:571)                                                                                                                                            
        at org.h2.store.PageStore.commit(PageStore.java:1477)                                                                                                                                       
        at org.h2.engine.Database.commit(Database.java:2024)                                                                                                                                        
        at org.h2.engine.Session.commit(Session.java:635)                                                                                                                                           
        at org.h2.command.Command.stop(Command.java:156)                                                                                                                                            
        at org.h2.command.Command.executeUpdate(Command.java:290)                                                                                                                                   
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:164)                                                                                                  
        at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1215)                                                                                                          
        at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerability(CveDB.java:741)                                                                                                          
        at org.owasp.dependencycheck.data.update.nvd.NvdCve20Handler.saveEntry(NvdCve20Handler.java:284)                                                                                            
        at org.owasp.dependencycheck.data.update.nvd.NvdCve20Handler.endElement(NvdCve20Handler.java:189)                                                                                           
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)                                                                                      
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)                                                          
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)                                              
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)                                                                                     
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)                                                             
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)                                                                                         
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)                                                                                         
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)                                                                                                           
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)                                                                                          
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)                                                                                        
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)                                                                                                      
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:328)                                                                                                                                    
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importXML(ProcessTask.java:154)                                                                                                    
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:167)                                                                                                 
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:119)                                                                                                         
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:46)                                                                                                          
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                          
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                          
        at java.lang.Thread.run(Thread.java:748)                                                                                                                                                    
Caused by: java.io.IOException: Stream Closed                                                                                                                                                       
        at java.io.RandomAccessFile.writeBytes(Native Method)                                                                                                                                       
        at java.io.RandomAccessFile.write(RandomAccessFile.java:525)                                                                                                                                
        at org.h2.store.fs.FileDisk.write(FilePathDisk.java:484)                                                                                                                                    
        at org.h2.store.fs.FileUtils.writeFully(FileUtils.java:372)                                                                                                                                 
        at org.h2.store.FileStore.write(FileStore.java:328)                                                                                                                                         
        ... 36 more

org.h2.message.DbException: IO Exception: "java.io.IOException: No space left on device"; "/tmp/abcd/dc.h2.db" [90031-196]                                                                          
        at org.h2.message.DbException.get(DbException.java:168)                                                                                                                                     
        at org.h2.message.DbException.convertIOException(DbException.java:330)                                                                                                                      
        at org.h2.store.FileStore.write(FileStore.java:331)                                                                                                                                         
        at org.h2.store.PageStore.writePage(PageStore.java:1369)                                                                                                                                    
        at org.h2.index.PageBtreeLeaf.write(PageBtreeLeaf.java:271)                                                                                                                                 
        at org.h2.store.PageStore.writeBack(PageStore.java:1047)                                                                                                                                    
        at org.h2.store.PageStore.writeBack(PageStore.java:419)                                                                                                                                     
        at org.h2.store.PageStore.checkpoint(PageStore.java:437)                                                                                                                                    
        at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1364)                                                                                                                       
        at org.h2.engine.Database.close(Database.java:1297)                                                                                                                                         
        at org.h2.engine.Database.removeSession(Database.java:1179)                                                                                                                                 
        at org.h2.engine.Session.close(Session.java:851)                                                                                                                                            
        at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:395)                                                                                                                                
        at org.owasp.dependencycheck.data.nvdcve.CveDB.close(CveDB.java:252)                                                                                                                        
        at org.owasp.dependencycheck.Engine.close(Engine.java:259)                                                                                                                                  
        at org.owasp.dependencycheck.App.runUpdateOnly(App.java:387)                                                                                                                                
        at org.owasp.dependencycheck.App.run(App.java:162)                                                                                                                                          
        at org.owasp.dependencycheck.App.main(App.java:69)                                                                                                                                          
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: No space left on device"; "/tmp/abcd/dc.h2.db" [90031-196]                                                             
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)                                                                                                                     
        ... 18 more                                                                                                                                                                                 
Caused by: java.io.IOException: No space left on device                                                                                                                                             
        at java.io.RandomAccessFile.writeBytes(Native Method)                                                                                                                                       
        at java.io.RandomAccessFile.write(RandomAccessFile.java:525)                                                                                                                                
        at org.h2.store.fs.FileDisk.write(FilePathDisk.java:484)                                                                                                                                    
        at org.h2.store.fs.FileUtils.writeFully(FileUtils.java:372)                                                                                                                                 
        at org.h2.store.FileStore.write(FileStore.java:328)                                                                                                                                         
        ... 15 more
```

**Comment by msrb** [comment]
We have a [persistent volume](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/openshift/template.yaml#L133-L135) that is attached to the container. There is 10GiB of space under `/pv/` directory. We already [use it](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/Dockerfile#L6) for building [maven index](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/handlers/maven_releases.py).

I think the same trick could be used here as well.

**Comment by msrb** [comment]
I can see the DB being updated now. We are moving away from DependecyCheck in https://github.com/openshiftio/openshift.io/issues/2480 (Maven) so this issue is not so pressing any more.

**Comment by GeorgeActon** [comment]
@msrb I see #2480 has been closed. Does that mean this defect can be closed as well?

**Comment by msrb** [comment]
Yes, thanks.
