### ISSUE TITLE
Strange error message + stacktrace is shown in f8analytics-data-model build+test job on CI

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#2263]
https://ci.centos.org/job/devtools-fabric8-analytics-data-model-fabric8-analytics/68/console

```
test/test_insertion_from_minio.py .ERROR:data_importer:import_epv() failed with error: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
ERROR:data_importer:Traceback for latest failure in import call: Traceback (most recent call last):
  File "/root/payload/src/data_importer.py", line 164, in import_epv_http
    prefix=pkg_key_prefix))
  File "/root/payload/src/data_source/s3_data_source.py", line 66, in list_files
    for obj in bucket.objects.filter(Prefix=prefix):
  File "/root/payload/env-test/lib/python2.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/root/payload/env-test/lib/python2.7/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/root/payload/env-test/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/root/payload/env-test/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/root/payload/env-test/lib/python2.7/site-packages/botocore/client.py", line 324, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/payload/env-test/lib/python2.7/site-packages/botocore/client.py", line 622, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.

ERROR:test_insertion_from_minio:Traceback for latest failure in import call: Traceback (most recent call last):
  File "/root/payload/test/test_insertion_from_minio.py", line 89, in test_insertion
    report = import_epv_from_s3_http(list_epv)
  File "/root/payload/src/data_importer.py", line 214, in import_epv_from_s3_http
    list_epv, select_doc)
  File "/root/payload/src/data_importer.py", line 199, in import_epv_http
    raise RuntimeError(msg)
RuntimeError: import_epv() failed with error: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
```

**Comment by tisnik** [comment]
Seems like the exception is just printed onto the standard output, but its ignored then.

https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/master/test/test_insertion_from_minio.py#L94

**Comment by joshuawilson** [comment]
what Severity is this?

**Comment by GeorgeActon** [comment]
@sivaavkd review with @tisnik and add prioirity

**Comment by msrb** [comment]
This is SEV2 high in my opinion. Tests are failing, but CI thinks everything is OK and we are promoting such code to production.

**Comment by msrb** [comment]
Thanks @tisnik, good catch 👍

**Comment by msrb** [comment]
@tuxdna could you please take a look? Thanks 😉

**Comment by tuxdna** [comment]
Looks like test environment issue. It exists for a long time so it must be working at some point.

 @miteshvp Could you check if it works for you?

**Comment by miteshvp** [comment]
@tuxdna - seems strange. Tests fail for me locally but the local access key works just fine.

**Comment by miteshvp** [comment]
Need to debug whether the tests are no longer talking to local but trying to reach cloud?

**Comment by miteshvp** [comment]
From this logs https://ci.centos.org/job/devtools-fabric8-analytics-data-model-fabric8-analytics/17/consoleFull 
this change looks to be the culprit as it is trying to reach to actual AWS services now

<img width="817" alt="image" src="https://user-images.githubusercontent.com/17736013/36294441-bd116dac-1306-11e8-84de-a25933bff360.png">

cc @msrb @tuxdna

**Comment by tuxdna** [comment]
@miteshvp Can you share your proposed fix in a PR?
