### ISSUE TITLE
Response with status: 404 Not Found for URL: https://api.openshift.io/api/spaces/7f851fa5-8840-4e...

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#2303]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-ui/issues/239/

```
Stacktrace (most recent call first):

  at Raven.captureMessage (./src/assets/stylesheets/shared/_scrollbars.less:6:3)
  at Raven.captureException (./src/assets/stylesheets/shared/_scrollbars.less:6:3)
  at apply (./src/assets/stylesheets/shared/_scrollbars.less:6:3)
  at ZoneDelegate.invokeTask (./node_modules/zone.js/dist/zone.js:425:1)
  at onInvokeTask (./node_modules/patternfly/dist/css/patternfly.min.css:1:5147)
  at invokeTask (./node_modules/zone.js/dist/zone.js:424:1)
  at runTask (./node_modules/zone.js/dist/zone.js:192:1)
  at invoke (./node_modules/zone.js/dist/zone.js:499:1)
  at invokeTask (./node_modules/zone.js/dist/zone.js:1540:1)
  at XMLHttpRequest.h (./node_modules/zone.js/dist/zone.js:1566:1)

Response with status: 404 Not Found for URL: https://api.openshift.io/api/spaces/7f851fa5-8840-4e2c-94e0-f3014ea781d1
```

**Comment by dgutride** [comment]
@aslakknutsen @joshuawilson  - when I delete a space, the recent spaces list for the user doesn't have it removed - that is causing the 404 on my system, should the UI clear the recent space on delete or should the API make sure it doesn't return the space.  I think it would be the api cascading the delete and clearing it from all users so multiple users of the space are updated correctly.

**Comment by joshuawilson** [comment]
I like the cascading delete, though I'm not sure how you would make that work for other users. How would you 'push' to them. I can see them getting it on a refresh.

**Comment by aslakknutsen** [comment]
@dgutride We created contextInformation as a 'UI' controlled 'storage' area for some quick turnaround before last Summit. So technically backend has no knowledge of what is stored there or why. Which is why the UI is trying to 'know the state of the world' by checking the API calls and backend returning 404 so the UI cleans up it's storage. 

This is less of a problem in a 'real world' scenario as less Spaces would be deleted. But I agree, assuming that 'last visited' is still a UX wanted behavior, the tracking should be moved to backend.

We would need to define an API and the expected behavior around it.

**Comment by christianvogt** [comment]
Closing as this is an old sentry error.
Pushing data to the user is a general issue and requires subscriptions to data and event bus.
The issue according to Dana above has been fixed as the list is now cleared when the space is removed.
