### ISSUE TITLE
Intermittent build failures on https://openshift.io - no route to host

### ISSUE THREAD

**Issue by rksharma1401** [openshiftio/openshift.io#2345]
When running a build it unable to connect to http://content-repository/content/repositories/staging/ 

[INFO] F8: Found tag on ImageStream tutorial tag: sha256:8091fea8b5dd488e8ebee7db6b59635cfc134e554e377084587c7baec81d1272
Feb 23, 2018 6:26:40 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://kubernetes.default.svc/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
[INFO] F8: ImageStream tutorial written to /home/jenkins/workspace/_springboot-turorial_master-HUXMIDFK3JAGN34OVG5GF32S74X5HLQ75Z246TLAGHKPSOX65YSA/target/tutorial-is.yml
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ tutorial ---
Feb 23, 2018 6:26:40 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection reset
Feb 23, 2018 6:26:40 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo.maven.apache.org:443
Feb 23, 2018 6:26:40 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection reset
Feb 23, 2018 6:26:40 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo.maven.apache.org:443
[INFO] Installing /home/jenkins/workspace/_springboot-turorial_master-HUXMIDFK3JAGN34OVG5GF32S74X5HLQ75Z246TLAGHKPSOX65YSA/target/springboot-1.0.1.jar to /root/.mvnrepository/springboot/tutorial/1.0.1/tutorial-1.0.1.jar
[INFO] Installing /home/jenkins/workspace/_springboot-turorial_master-HUXMIDFK3JAGN34OVG5GF32S74X5HLQ75Z246TLAGHKPSOX65YSA/pom.xml to /root/.mvnrepository/springboot/tutorial/1.0.1/tutorial-1.0.1.pom
[INFO] Installing /home/jenkins/workspace/_springboot-turorial_master-HUXMIDFK3JAGN34OVG5GF32S74X5HLQ75Z246TLAGHKPSOX65YSA/target/classes/META-INF/fabric8/openshift.yml to /root/.mvnrepository/springboot/tutorial/1.0.1/tutorial-1.0.1-openshift.yml
[INFO] Installing /home/jenkins/workspace/_springboot-turorial_master-HUXMIDFK3JAGN34OVG5GF32S74X5HLQ75Z246TLAGHKPSOX65YSA/target/classes/META-INF/fabric8/openshift.json to /root/.mvnrepository/springboot/tutorial/1.0.1/tutorial-1.0.1-openshift.json
[INFO] Installing /home/jenkins/workspace/_springboot-turorial_master-HUXMIDFK3JAGN34OVG5GF32S74X5HLQ75Z246TLAGHKPSOX65YSA/target/classes/META-INF/fabric8/kubernetes.yml to /root/.mvnrepository/springboot/tutorial/1.0.1/tutorial-1.0.1-kubernetes.yml
[INFO] Installing /home/jenkins/workspace/_springboot-turorial_master-HUXMIDFK3JAGN34OVG5GF32S74X5HLQ75Z246TLAGHKPSOX65YSA/target/classes/META-INF/fabric8/kubernetes.json to /root/.mvnrepository/springboot/tutorial/1.0.1/tutorial-1.0.1-kubernetes.json
[INFO] Installing /home/jenkins/workspace/_springboot-turorial_master-HUXMIDFK3JAGN34OVG5GF32S74X5HLQ75Z246TLAGHKPSOX65YSA/target/tutorial-is.yml to /root/.mvnrepository/springboot/tutorial/1.0.1/tutorial-1.0.1-is.yml
[INFO] 
[INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ tutorial ---
[INFO] Using alternate deployment repository local-nexus::default::http://content-repository/content/repositories/staging/
Feb 23, 2018 6:26:44 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://content-repository:80: No route to host (Host unreachable)
Feb 23, 2018 6:26:44 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://content-repository:80
Feb 23, 2018 6:26:46 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://content-repository:80: No route to host (Host unreachable)
Feb 23, 2018 6:26:46 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://content-repository:80
Feb 23, 2018 6:26:49 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://content-repository:80: No route to host (Host unreachable)
Feb 23, 2018 6:26:49 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://content-repository:80
Feb 23, 2018 6:26:55 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://content-repository:80: No route to host (Host unreachable)
Feb 23, 2018 6:26:55 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://content-repository:80
Feb 23, 2018 6:26:58 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://content-repository:80: No route to host (Host unreachable)
Feb 23, 2018 6:26:58 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://content-repository:80
Feb 23, 2018 6:27:01 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://content-repository:80: No route to host (Host unreachable)
Feb 23, 2018 6:27:01 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://content-repository:80
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:13 min
[INFO] Finished at: 2018-02-23T06:27:04+00:00
[INFO] Final Memory: 36M/49M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project tutorial: Failed to deploy artifacts: Could not transfer artifact springboot:tutorial:jar:1.0.1 from/to local-nexus (http://content-repository/content/repositories/staging/): No route to host (Host unreachable) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project tutorial: Failed to deploy artifacts: Could not transfer artifact springboot:tutorial:jar:1.0.1 from/to local-nexus (http://content-repository/content/repositories/staging/): No route to host (Host unreachable)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to deploy artifacts: Could not transfer artifact springboot:tutorial:jar:1.0.1 from/to local-nexus (http://content-repository/content/repositories/staging/): No route to host (Host unreachable)
	at org.apache.maven.plugin.deploy.DeployMojo.deployProject(DeployMojo.java:284)
	at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:169)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Failed to deploy artifacts: Could not transfer artifact springboot:tutorial:jar:1.0.1 from/to local-nexus (http://content-repository/content/repositories/staging/): No route to host (Host unreachable)
	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:143)
	at org.apache.maven.plugin.deploy.AbstractDeployMojo.deploy(AbstractDeployMojo.java:171)
	at org.apache.maven.plugin.deploy.DeployMojo.deployProject(DeployMojo.java:250)
	... 23 more
Caused by: org.eclipse.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact springboot:tutorial:jar:1.0.1 from/to local-nexus (http://content-repository/content/repositories/staging/): No route to host (Host unreachable)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:317)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:245)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:413)
	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:139)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact springboot:tutorial:jar:1.0.1 from/to local-nexus (http://content-repository/content/repositories/staging/): No route to host (Host unreachable)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.put(BasicRepositoryConnector.java:274)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:311)
	... 28 more
Caused by: org.apache.maven.wagon.TransferFailedException: No route to host (Host unreachable)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:646)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:541)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:523)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:517)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:497)
	at org.eclipse.aether.transport.wagon.WagonTransporter$PutTaskRunner.run(WagonTransporter.java:644)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.put(WagonTransporter.java:410)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.runTask(BasicRepositoryConnector.java:510)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 30 more
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.maven.wagon.providers.http.httpclient.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:832)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:592)
	... 39 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

**Comment by joshuawilson** [comment]
Duplicates #2341, closing. If you feel this is different, please reopen.
