### ISSUE TITLE
Che workspace becomes unresponsive

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#2366]
Working with a default booster, I managed to break the Che workspace.  

- Changed the message the 'Spring Boot' greeter produced
- Ran the Unit tests from the Che console with 'mvn test'
- Che started getting strange immediately after.  Note that the tests would fail, I had changed the message but did not have the Asserted test string properly changed yet.

Screenshots to follow.

**Comment by rhopp** [comment]
Hi @RickJWagner 
Is this issue reproducible?
I was looking into che-server logs and only error I found in vicinity of this particular workspace logs is this:
```
{"@timestamp":"2018-02-22T20:04:18.890+00:00","@version":1,"message":"An OpenShift Pod with label cheContainerIdentifier=1cc526ef75268971a173218c1874e50728c3b7c99514636a8a6adc858c0d4f01 could not be found","logger_name":"org.eclipse.che.plugin.docker.machine.DockerInstance","thread_name":"WorkspaceSharedPool-2","level":"ERROR","level_value":40000,"stack_trace":"java.io.IOException: An OpenShift Pod with label cheContainerIdentifier=1cc526ef75268971a173218c1874e50728c3b7c99514636a8a6adc858c0d4f01 could not be found
	at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.getChePodByContainerId(OpenShiftConnector.java:1593)
	at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.getDeploymentName(OpenShiftConnector.java:2242)
	at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.removeContainer(OpenShiftConnector.java:831)
	at org.eclipse.che.plugin.docker.machine.DockerInstance.destroy(DockerInstance.java:282)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyMachine(CheEnvironmentEngine.java:1172)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyEnvironment(CheEnvironmentEngine.java:1147)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.stop(CheEnvironmentEngine.java:322)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stopEnvironmentAndPublishEvents(WorkspaceRuntimes.java:788)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:356)
	at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$stopAsync$3(WorkspaceManager.java:732)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:29)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"}
{"@timestamp":"2018-02-22T20:04:18.890+00:00","@version":1,"message":"Could not destroy machine 'machinew3fmp1ms612t1u19' of workspace 'workspace5vvn2ow271l8kzww'","logger_name":"org.eclipse.che.api.environment.server.CheEnvironmentEngine","thread_name":"WorkspaceSharedPool-2","level":"ERROR","level_value":40000,"stack_trace":"org.eclipse.che.api.machine.server.exception.MachineException: An OpenShift Pod with label cheContainerIdentifier=1cc526ef75268971a173218c1874e50728c3b7c99514636a8a6adc858c0d4f01 could not be found
	at org.eclipse.che.plugin.docker.machine.DockerInstance.destroy(DockerInstance.java:286)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyMachine(CheEnvironmentEngine.java:1172)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyEnvironment(CheEnvironmentEngine.java:1147)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.stop(CheEnvironmentEngine.java:322)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stopEnvironmentAndPublishEvents(WorkspaceRuntimes.java:788)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:356)
	at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$stopAsync$3(WorkspaceManager.java:732)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:29)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"}
```
Not sure it's relevant though.

@l0rd @eivantsov Any idea what can be causing this?

**Comment by eivantsov** [comment]
Most certainly OOM, and ws agent process is killed

**Comment by RickJWagner** [comment]
Hi Radim,

Thanks for having a look.  I'll try to work with similar scenarios, to see
if I can replicate the problem.  I'll update the issue if I manage to do it.

Rick

**Comment by ibuziuk** [comment]
@RickJWagner are you still able to reproduce this problem ?

**Comment by RickJWagner** [comment]
Hi @ibuziuk,
I'm not able to reproduce this issue, so this one can be closed.
Thanks,
Rick
