### ISSUE TITLE
Building vertx apps on prod fails with maven dependency errors.

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#2397]
This is the gist of the error. 

```
[ERROR] Failed to execute goal on project vertxapp: Could not resolve dependencies for project io.openshift.booster:vertxapp:jar:1.0.1: The following artifacts could not be resolved: org.assertj:assertj-core:jar:3.8.0, io.rest-assured:rest-assured:jar:3.0.5, org.codehaus.groovy:groovy:jar:2.4.9, org.codehaus.groovy:groovy-xml:jar:2.4.9, org.apache.httpcomponents:httpclient:jar:4.5.3: Could not transfer artifact org.assertj:assertj-core:jar:3.8.0 from/to central (https://repo.maven.apache.org/maven2): 
```

Jenkins build : https://jenkins.openshift.io/job/jaseemabid/job/vertxapp/job/master/1/console

Full build logs: 

```
OpenShift Build jabid/vertxapp-2 from https://github.com/jaseemabid/vertxapp.git
Connecting to https://api.github.com using jaseemabid/****** (cd-github)
Obtained Jenkinsfile from a836a698b646f7869906d572af76de7771ae43f7
Loading library github.com/fabric8io/fabric8-pipeline-library@master
Attempting to resolve master from remote references...
 > git --version # timeout=10
 > git ls-remote -h -t https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
Found match: refs/heads/master revision ed80ca334cd25477b1045a329e5c21b6b7eade12
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/fabric8io/fabric8-pipeline-library.git
 > git init /var/lib/jenkins/jobs/jaseemabid/jobs/vertxapp/branches/master/workspace@libs/github.com/fabric8io/fabric8-pipeline-library # timeout=10
Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git
 > git --version # timeout=10
 > git fetch --no-tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git
 > git fetch --no-tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision ed80ca334cd25477b1045a329e5c21b6b7eade12 (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ed80ca334cd25477b1045a329e5c21b6b7eade12
Commit message: "Merge pull request #382 from rupalibehera/token-env-planner-team"
First time build. Skipping changelog.
[Pipeline] echo
Kubernetes Plugin Version 013
[Pipeline] echo
Loaded PipelineConfiguration PipelineConfiguration{jobNameToKindMap={}, ciBranchPatterns=[PR-.*], cdBranchPatterns=[master], cdGitHostAndOrganisationToBranchPatterns={}, disableITestsCD=false, disableITestsCI=false, useDockerSocketFlag=false}
[Pipeline] echo
Loaded the useDockerSocket flag false
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
Jenkins doesn’t have label mavenvertxapp_1
Running on jenkins-slave-7r1vx-d5kxf in /home/jenkins/workspace/jaseemabid_vertxapp_master-H32ZJFBTIYTHVJ3ER6OMNP2WKR2G54WF6CUM3E3DAZZLYSGOCDWQ
[Pipeline] {
[Pipeline] checkout
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/jaseemabid/vertxapp.git
 > git init /home/jenkins/workspace/jaseemabid_vertxapp_master-H32ZJFBTIYTHVJ3ER6OMNP2WKR2G54WF6CUM3E3DAZZLYSGOCDWQ # timeout=10
Fetching upstream changes from https://github.com/jaseemabid/vertxapp.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials cd-github
 > git fetch --no-tags --progress https://github.com/jaseemabid/vertxapp.git +refs/heads/master:refs/remotes/origin/master
 > git config remote.origin.url https://github.com/jaseemabid/vertxapp.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config remote.origin.url https://github.com/jaseemabid/vertxapp.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/jaseemabid/vertxapp.git
using GIT_ASKPASS to set credentials cd-github
 > git fetch --no-tags --progress https://github.com/jaseemabid/vertxapp.git +refs/heads/master:refs/remotes/origin/master
Checking out Revision a836a698b646f7869906d572af76de7771ae43f7 (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a836a698b646f7869906d572af76de7771ae43f7
Commit message: "Initial import"
First time build. Skipping changelog.
fatal: bad object ed80ca334cd25477b1045a329e5c21b6b7eade12
[Pipeline] echo
Using branch master
[Pipeline] echo
Using branch master
[Pipeline] echo
NOTE: running pipelines for the first time will take longer as build and base docker images are pulled onto the node
[Pipeline] container
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build Release)
[Pipeline] sh
[jaseemabid_vertxapp_master-H32ZJFBTIYTHVJ3ER6OMNP2WKR2G54WF6CUM3E3DAZZLYSGOCDWQ] Running shell script
+ git checkout -b jaseemabid/vertxapp/master-1.0.1
Switched to a new branch 'jaseemabid/vertxapp/master-1.0.1'
[Pipeline] sh
[jaseemabid_vertxapp_master-H32ZJFBTIYTHVJ3ER6OMNP2WKR2G54WF6CUM3E3DAZZLYSGOCDWQ] Running shell script
+ mvn org.codehaus.mojo:versions-maven-plugin:2.2:set -U -DnewVersion=1.0.1
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x - HTTP 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.2:set (default-cli) @ vertxapp ---
EXITCODE   0[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: /home/jenkins/workspace/jaseemabid_vertxapp_master-H32ZJFBTIYTHVJ3ER6OMNP2WKR2G54WF6CUM3E3DAZZLYSGOCDWQ
[INFO] Processing change of io.openshift.booster:vertxapp:1.0.0-SNAPSHOT -> 1.0.1
[INFO] Processing io.openshift.booster:vertxapp
[INFO]     Updating project io.openshift.booster:vertxapp
[INFO]         from version 1.0.0-SNAPSHOT to 1.0.1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:18 min
[INFO] Finished at: 2018-03-01T10:05:30+00:00
[INFO] Final Memory: 10M/15M
[INFO] ------------------------------------------------------------------------
[Pipeline] sh
[jaseemabid_vertxapp_master-H32ZJFBTIYTHVJ3ER6OMNP2WKR2G54WF6CUM3E3DAZZLYSGOCDWQ] Running shell script
+ mvn clean -B -e -U deploy -Dmaven.test.skip=false -P openshift
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x - HTTP 1.0.1
[INFO] ------------------------------------------------------------------------
EXITCODE   0[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:18 min
[INFO] Finished at: 2018-03-01T10:08:00+00:00
[INFO] Final Memory: 14M/24M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project vertxapp: Could not resolve dependencies for project io.openshift.booster:vertxapp:jar:1.0.1: The following artifacts could not be resolved: org.assertj:assertj-core:jar:3.8.0, io.rest-assured:rest-assured:jar:3.0.5, org.codehaus.groovy:groovy:jar:2.4.9, org.codehaus.groovy:groovy-xml:jar:2.4.9, org.apache.httpcomponents:httpclient:jar:4.5.3: Could not transfer artifact org.assertj:assertj-core:jar:3.8.0 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/org/assertj/assertj-core/3.8.0/assertj-core-3.8.0.jar.part (No such file or directory) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project vertxapp: Could not resolve dependencies for project io.openshift.booster:vertxapp:jar:1.0.1: The following artifacts could not be resolved: org.assertj:assertj-core:jar:3.8.0, io.rest-assured:rest-assured:jar:3.0.5, org.codehaus.groovy:groovy:jar:2.4.9, org.codehaus.groovy:groovy-xml:jar:2.4.9, org.apache.httpcomponents:httpclient:jar:4.5.3: Could not transfer artifact org.assertj:assertj-core:jar:3.8.0 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/org/assertj/assertj-core/3.8.0/assertj-core-3.8.0.jar.part (No such file or directory)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project io.openshift.booster:vertxapp:jar:1.0.1: The following artifacts could not be resolved: org.assertj:assertj-core:jar:3.8.0, io.rest-assured:rest-assured:jar:3.0.5, org.codehaus.groovy:groovy:jar:2.4.9, org.codehaus.groovy:groovy-xml:jar:2.4.9, org.apache.httpcomponents:httpclient:jar:4.5.3: Could not transfer artifact org.assertj:assertj-core:jar:3.8.0 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/org/assertj/assertj-core/3.8.0/assertj-core-3.8.0.jar.part (No such file or directory)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.assertj:assertj-core:jar:3.8.0, io.rest-assured:rest-assured:jar:3.0.5, org.codehaus.groovy:groovy:jar:2.4.9, org.codehaus.groovy:groovy-xml:jar:2.4.9, org.apache.httpcomponents:httpclient:jar:4.5.3: Could not transfer artifact org.assertj:assertj-core:jar:3.8.0 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/org/assertj/assertj-core/3.8.0/assertj-core-3.8.0.jar.part (No such file or directory)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.assertj:assertj-core:jar:3.8.0, io.rest-assured:rest-assured:jar:3.0.5, org.codehaus.groovy:groovy:jar:2.4.9, org.codehaus.groovy:groovy-xml:jar:2.4.9, org.apache.httpcomponents:httpclient:jar:4.5.3: Could not transfer artifact org.assertj:assertj-core:jar:3.8.0 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/org/assertj/assertj-core/3.8.0/assertj-core-3.8.0.jar.part (No such file or directory)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.assertj:assertj-core:jar:3.8.0 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/org/assertj/assertj-core/3.8.0/assertj-core-3.8.0.jar.part (No such file or directory)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /root/.m2/repository/org/assertj/assertj-core/3.8.0/assertj-core-3.8.0.jar.part (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:568)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 4 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by jaseemabid** [comment]
@kbsingh, @hrishin says this is related to the proxy we use and you could help.

**Comment by hrishin** [comment]
@jaseemabid @kbsingh it could be networking issue for downloading the dependencies but weirdly its boiled down to file I/O as well while writing dependencies to file system.

Btw just to note `/root/.m2` is a mount path for secrete  `jenkins-maven-settings'.

**Comment by stevengutz** [comment]
Is anyone looking at this.  Since it's blocking https://github.com/openshiftio/openshift.io/issues/2368 it's a pretty high priority to get resolved

**Comment by jaseemabid** [comment]
@hrishin and I are looking into this

**Comment by stevengutz** [comment]
@jaseemabid Please assign it to yourselves if you are working on it, just so everyone knows it's getting some love

**Comment by piyush1594** [comment]
@jaseemabid @hrishin Is this still a valid issue? Right now boosters are working properly.

**Comment by jaseemabid** [comment]
@piyush1594 Let's close it. Thanks for spotting it.
