### ISSUE TITLE
Celery exceptions not showing up in Sentry

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2535]
# Description

We integrated workers with Sentry in https://github.com/openshiftio/openshift.io/issues/2236, but I can clearly see following exception in the logs, but not in Sentry:

```
{"version": "1.0.0", "force_graph_sync": false, "name": "leaflet-usermarker", "_release": "npm:leaflet-usermarker:1.0.0", "ecosystem": "npm", "recursive_limit": 0, "_audit": {"version": "v1", "ended_at": "2018-03-12T09:07:45.026620", "started_at": "2018-03-12T09:07:39.940694"}, "job_id": "dc553fb9-b84e-4619-a3b6-9ffe5d7bb9fe", "force": true, "document_id": 5256360}, "flow_name": "bayesianAnalysisFlow", "dispatcher_id": "cc6284f7-d64a-4015-97ff-afb0177b9145"}
2018-03-12 09:14:10,276 [INFO] celery.app.trace: Task selinon.SelinonTaskEnvelope[cc71add1-e706-4573-a054-722f83c84cda] succeeded in 19.946269513107836s: None
2018-03-12 09:14:10,314 [CRITICAL] celery.worker: Unrecoverable error: Exception('Request Empty body  HTTP 599  Encountered end of file (None)',)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/lib/python3.4/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/usr/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/usr/lib/python3.4/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/usr/lib/python3.4/site-packages/kombu/async/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/lib/python3.4/site-packages/kombu/async/http/curl.py", line 111, in on_readable
    return self._on_event(fd, _pycurl.CSELECT_IN)
  File "/usr/lib/python3.4/site-packages/kombu/async/http/curl.py", line 124, in _on_event
    self._process_pending_requests()
  File "/usr/lib/python3.4/site-packages/kombu/async/http/curl.py", line 132, in _process_pending_requests
    self._process(curl, errno, reason)
  File "/usr/lib/python3.4/site-packages/kombu/async/http/curl.py", line 178, in _process
    buffer=buffer, effective_url=effective_url, error=error,
  File "/usr/lib/python3.4/site-packages/vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "/usr/lib/python3.4/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/usr/lib/python3.4/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/lib/python3.4/site-packages/vine/funtools.py", line 100, in _transback
    return callback(ret)
  File "/usr/lib/python3.4/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/usr/lib/python3.4/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/lib/python3.4/site-packages/vine/funtools.py", line 98, in _transback
    callback.throw()
  File "/usr/lib/python3.4/site-packages/vine/funtools.py", line 96, in _transback
    ret = filter_(*args + (ret,), **kwargs)
  File "/usr/lib/python3.4/site-packages/kombu/async/aws/connection.py", line 253, in _on_status_ready
    raise self._for_status(response, response.read())
Exception: Request Empty body  HTTP 599  Encountered end of file (None)
Restoring 7 unacknowledged message(s)
```

The reason could be that we enable Sentry integration in Selinon, which is probably too late.

**Comment by msrb** [comment]
Sentry docs here: https://docs.sentry.io/clients/python/

**Comment by tuxdna** [comment]
@GeetikaBatra You my want to follow these steps to configure sentry for local development: https://github.com/fabric8-analytics/fabric8-analytics-deployment/issues/21#issuecomment-372972232

**Comment by msrb** [comment]
I can see exceptions being reported twice now. Not a big deal. Let's see if we can catch the celery exception. If so, we will disable Sentry in Selinon.
