### ISSUE TITLE
Jenkins pod log contains WARN message

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#2601]
Checking up on the Jenkins pod log (waiting for a build to start) there is a WARN message.  
Please debug/explain/take some action to remove from the log.

![image](https://user-images.githubusercontent.com/524520/37427929-bfccc004-2798-11e8-9313-c3d2c4349b8d.png)

**Comment by RickJWagner** [comment]
Text version:


INFO: Obtained the updated data file for hudson.plugins.gradle.GradleInstaller
--
  | Mar 14, 2018 7:54:12 PM hudson.XmlFile replaceIfNotAtTopLevel
  | WARNING: JENKINS-45892: reference to jenkins.branch.OrganizationFolder@19b6aa1[rickjwagner] being saved from unexpected /var/lib/jenkins/jobs/rickjwagner/computation/computation.xml
  | java.lang.IllegalStateException
  | at hudson.XmlFile.replaceIfNotAtTopLevel(XmlFile.java:208)
  | at hudson.model.AbstractItem.writeReplace(AbstractItem.java:492)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteReplace(SerializationMethodInvoker.java:89)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:141)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
  | at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
  | at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
  | at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
  | at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
  | at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
  | at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
  | at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
  | at hudson.XmlFile.write(XmlFile.java:179)
  | at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.save(FolderComputation.java:208)
  | at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:192)
  | at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:911)
  | at hudson.model.ResourceController.execute(ResourceController.java:97)
  | at hudson.model.Executor.run(Executor.java:429)
  |  
  | Mar 14, 2018 7:54:12 PM jenkins.branch.OrganizationFolder$OrganizationScan run
  | INFO: rickjwagner #20180314.195403 organization scan action completed: SUCCESS in 8.8 sec
  | Mar 14, 2018 7:54:14 PM io.fabric8.jenkins.openshiftsync.PipelineJobListener buildConfigProjectForJob
  | INFO: Creating BuildConfigProjectProperty for namespace: rhn-support-rick name: osiotestday2
  | Mar 14, 2018 7:54:14 PM io.fabric8.jenkins.openshiftsync.PipelineJobListener upsertWorkflowJob
  | INFO: Upsert WorkflowJob master to BuildConfig: rhn-support-rick/osiotestday2 in OpenShift
  | Mar 14, 2018 7:54:14 PM hudson.model.DownloadService$Downloadable load
  | INFO: Obtained the updated data file for hudson.tools.JDKInstaller
  | Mar 14, 2018 7:54:14 PM hudson.model.AsyncPeriodicWork$1 run
  | INFO: Finished Download metadata. 38,409 ms
  | Mar 14, 2018 7:54:15 PM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2 call
  | INFO: Updated job osiotestday2 from BuildConfig NamespaceName{rhn-support-rick:osiotestday2} with revision: 1026662294
  | Mar 14, 2018 7:54:15 PM hudson.XmlFile replaceIfNotAtTopLevel
  | WARNING: JENKINS-45892: reference to org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject@66df29[rickjwagner/osiotestday2] being saved from unexpected /var/lib/jenkins/jobs/rickjwagner/jobs/osiotestday2/indexing/indexing.xml
  | java.lang.IllegalStateException
  | at hudson.XmlFile.replaceIfNotAtTopLevel(XmlFile.java:208)
  | at hudson.model.AbstractItem.writeReplace(AbstractItem.java:492)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteReplace(SerializationMethodInvoker.java:89)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:141)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
  | at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
  | at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
  | at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
  | at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
  | at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
  | at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
  | at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
  | at hudson.XmlFile.write(XmlFile.java:179)
  | at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.save(FolderComputation.java:208)
  | at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:192)
  | at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1004)
  | at hudson.model.ResourceController.execute(ResourceController.java:97)
  | at hudson.model.Executor.run(Executor.java:429)
  |  
  | Mar 14, 2018 7:54:15 PM jenkins.branch.MultiBranchProject$BranchIndexing run
  | INFO: rickjwagner/osiotestday2 #20180314.195412 branch indexing action completed: SUCCESS in 3.7 sec
  | Mar 14, 2018 7:54:36 PM hudson.model.AsyncPeriodicWork$1 run
  | INFO: Started Gravatar periodic lookup
  | Mar 14, 2018 7:54:36 PM hudson.model.AsyncPeriodicWork$1 run
  | INFO: Finished Gravatar periodic lookup. 3 ms
  | Mar 14, 2018 7:55:07 PM jenkins.metrics.api.Metrics$HealthChecker execute
  | WARNING: Some health checks are reporting as unhealthy: [disk-space : Only 0.398 Gb free on (master)]
  | Mar 14, 2018 7:56:36 PM hudson.XmlFile replaceIfNotAtTopLevel
  | WARNING: JENKINS-45892: reference to org.jenkinsci.plugins.workflow.job.WorkflowJob@503ac4[rickjwagner/osiotestday2/master] being saved from unexpected /var/lib/jenkins/jobs/rickjwagner/jobs/osiotestday2/branches/master/builds/1/build.xml
  | java.lang.IllegalStateException
  | at hudson.XmlFile.replaceIfNotAtTopLevel(XmlFile.java:208)
  | at hudson.model.AbstractItem.writeReplace(AbstractItem.java:492)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteReplace(SerializationMethodInvoker.java:89)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:141)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
  | at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
  | at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
  | at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
  | at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
  | at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
  | at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
  | at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
  | at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
  | at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
  | at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
  | at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
  | at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
  | at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
  | at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
  | at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
  | at hudson.XmlFile.write(XmlFile.java:179)
  | at hudson.model.Run.save(Run.java:1923)
  | at hudson.model.Run.setDescription(Run.java:2228)
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.onStarted(BuildSyncRunListener.java:143)
  | at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
  | at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:254)
  | at hudson.model.ResourceController.execute(ResourceController.java:97)
  | at hudson.model.Executor.run(Executor.java:429)

**Comment by hrishin** [comment]
Hi @RickJWagner 
Thanks for reporting an issue. Could you provide more details to reproduce this behavior?

Otherwise, its good to close for current Jenkins.
