### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined (user presented with "loading..." screen - appears to hang)

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#2915]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-ui/issues/2197/

```
Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (https://prod-preview.openshift.io/_assets/lib/polyfills.68242bc73dcace7ef76e.bundle.js:1:119)
    at https://prod-preview.openshift.io/_assets/lib/6.33912963b4fcf2a13b22.chunk.js:1:216078
    at ZoneDelegate.invoke (https://prod-preview.openshift.io/_assets/lib/polyfills.68242bc73dcace7ef76e.bundle.js:1:96015)
    at Object.onInvoke (https://prod-preview.openshift.io/_assets/lib/vendor.e4ac077668e93a67a17d.bundle.js:1:11270)
    at ZoneDelegate.invoke (https://prod-preview.openshift.io/_assets/lib/polyfills.68242bc73dcace7ef76e.bundle.js:1:95955)
    at Zone.run (https://prod-preview.openshift.io/_assets/lib/polyfills.68242bc73dcace7ef76e.bundle.js:1:91102)
    at https://prod-preview.openshift.io/_assets/lib/polyfills.68242bc73dcace7ef76e.bundle.js:1:101878
    at ZoneDelegate.invokeTask (https://prod-preview.openshift.io/_assets/lib/polyfills.68242bc73dcace7ef76e.bundle.js:1:96748)
    at Object.onInvokeTask (https://prod-preview.openshift.io/_assets/lib/vendor.e4ac077668e93a67a17d.bundle.js:1:11172)
    at ZoneDelegate.invokeTask (https://prod-preview.openshift.io/_assets/lib/polyfills.68242bc73dcace7ef76e.bundle.js:1:96669)
    at Zone.runTask (https://prod-preview.openshift.io/_assets/lib/polyfills.68242bc73dcace7ef76e.bundle.js:1:91799)
    at drainMicroTaskQueue (https://prod-preview.openshift.io/_assets/lib/polyfills.68242bc73dcace7ef76e.bundle.js:1:88764)
  at __webpack_require__ (webpack/bootstrap 1543e3f00786e69043f5:54:1)
  at apply (./src/app/space/create/create-routing.module.ts:15:128)
  at ZoneDelegate.invoke (./node_modules/zone.js/dist/zone.js:392:1)
  at onInvoke (./node_modules/patternfly/dist/css/patternfly.min.css:1:5147)
  at invoke (./node_modules/zone.js/dist/zone.js:391:1)
...
(14 additional frame(s) were not displayed)
```

**Comment by joshuawilson** [comment]
The work around is to open the dev tools console and go to the Network tab. Select the `disable cache` box at the top. Then refresh the browser.

**Comment by pbergene** [comment]
This is also seen on production.
![typeerror](https://user-images.githubusercontent.com/29919223/38426923-2c975d30-39b8-11e8-8154-302d645eb832.png)

**Comment by pbergene** [comment]
Related to caching likely  - a force reload clears this, but not a great experience.  Anything we can tweak to work around cases like this?

**Comment by joshuawilson** [comment]
@christianvogt and I are looking into it
