### ISSUE TITLE
ConfigMap / SpringBoot quickstart/booster fails to build

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3131]
Steps to recreate:
* Create new quickstart/booster, Mission = config, runtime = SpringBoot
* Observe build fail:

```
[INFO] Current reconnect backoff is 8000 milliseconds (T3)
[INFO] F8: Pushed 6/6 layers, 100% complete
[INFO] F8: Push successful
[INFO] F8: Build spring-boot-configmap-greeting-s2i-1 Complete
[INFO] Current reconnect backoff is 16000 milliseconds (T4)
[ERROR] Exception in reconnect
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5a4cb8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@158d817[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 8]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
	at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager$3.run(WatchHTTPManager.java:207)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by quintesse** [comment]
This doesn't seem like a problem with the launcher code but more like an infrastructure issue.

**Comment by gastaldi** [comment]
@gytis is verifying this issue. All we know right now is that https://github.com/snowdrop/spring-boot-configmap-booster/pull/43 needs to be merged too.

**Comment by gastaldi** [comment]
Actually @gytis is working on making the Spring Boot Configmap work in OSIO, which may not be related to this error specifically, but it would be nice to test anyway ;)

**Comment by mishaone** [comment]
Is the fail message below the same issue? This is after creating a spring boot quickstart and using the run button on the unaltered quickstart code:

http://pastebin.test.redhat.com/583632

**Comment by gytis** [comment]
Here the update on the ConfigMap issue. I've added a workaround to access the config within OSIO to a separate booster branch (osio) and added a new Spring Boot runtime version to the booster catalog, which only has configmap booster for OSIO https://github.com/snowdrop/launcher-booster-catalog/tree/istio/spring-boot/current-osio/configmap. It doesn't work yet, however, because the latest productised spring-boot-bom hasn't yet been synced to the GA repo, but it should be this week (hopefully at the beginning of the week).

**Comment by animuk** [comment]
@gytis Do you have any current update on the booster when It is available.
cc @slemeur @GeorgeActon

**Comment by slemeur** [comment]
What is the proposed change for @gytis ? Is there a PR somewhere?

**Comment by maxandersen** [comment]
@gytis what is the actual change made here ?  is it still blocked by https://github.com/snowdrop/spring-boot-configmap-booster/pull/43 ?

**Comment by gytis** [comment]
I've created a separate branch for [OSIO](https://github.com/snowdrop/spring-boot-configmap-booster/tree/osio) where configmap is loaded as a file rather that accessed via Kubernetes API. In addition I've added a separate version for OSIO (containing only configmap mission) to the [booster catalog](https://github.com/fabric8-launcher/launcher-booster-catalog/tree/master/spring-boot/current-osio/configmap).
However, the issue is that the OSIO branch same as the prod branch at the moment depends to the artifact which was supposed to become available yesterday, but prod rejected it. Same issue is true for all productised Spring Boot booster AFAIK.
@metacosm @cmoulliard do you think that we should wait for it to get release or would it make more sense to revert that artifact to an older version?

**Comment by maxandersen** [comment]
@gytis okey; if the fix here (or other issues) does not actually rely on using a new pom I would definitely go for rolling back use of the former *actually* relased version.

On the whole configmap discussion i think we need to catch up on this post summit as I do not think everyone has all the facts and reasons in place - and it seems we are now starting to apply *different* workarounds across the boosters to this problem. If somehow OSIO permissions are too limited/wrong we should work on fixing that - but doing that now as last minute is too high risk.

**Comment by gytis** [comment]
I'm checking now if the rollback would work (I assume it should).
As for the long term fix, we could go back to use the original booster implementation with Kubernetes API if we would be able to execute this command on OSIO: `oc policy add-role-to-user view system:serviceaccount:$(oc project -q):default -n $(oc project -q)` or if a user would have a view role by default.

**Comment by slemeur** [comment]
@gytis : Do you have an update?
@animuk : Why did you removed the P0 from this issue?

**Comment by gytis** [comment]
@slemeur I've rolled back the versions and the booster in theory should be usable on OSIO. However, @animuk tried it twice and it failed to deploy because of a socket timeout during the S2I build. Since I don't have access to OSIO I cannot debug the issue, but this doesn't sound like being related to ConfigMap.

**Comment by slemeur** [comment]
@gytis Thanks for the update!

**Comment by slemeur** [comment]
From discussing with @animuk (and email thread) that version of the booster is now working properly on OSIO.

> "New entry Springboot-Configmap booster is working e2e at the moment."
