### ISSUE TITLE
error: failed to load chunk

### ISSUE THREAD

**Issue by christianvogt** [openshiftio/openshift.io#3312]
Every time we push a change to production we are potentially causing grief for our users with existing sessions opened in the browser wherein their webapp may throw errors and they will need to refresh their page to fix the issue.

The build produces chunks and each chunk is named with a hash. The hash changes whenever the artifacts within a chunk change. The main artifact knows the names of all the chunks and is the first thing that loads in the browser. If the user hasn't browsed to a certain part of the app, then the chunk that serves that part of the app will not have been loaded yet. If we then update the production build and the chunk name that was previously known has changed, when the user navigates to the part of the app that needs that chunk it will fail to load as the old chunk name will be requested.

I reproduced the issue locally and this is the resulting error:
![image](https://user-images.githubusercontent.com/14068621/39276258-549a7eae-48b6-11e8-986b-98b38bf6a20e.png)

**Comment by christianvogt** [comment]
We need to reproduce this in production.

Open OSIO in a browser but do not navigate anywhere (may want to try different landing pages). Then wait till new changes are pushed to production and try to navigate the app. Check for errors in the console for failure to load chunk errors.

**Comment by christianvogt** [comment]
One solution could be:
Have the web client check for version changes (using a websocket connection?). When the version changes, our router instead of updating the page like a SPA would instead cause the new route to refresh the web app to the new URL. Upon refreshing the new chunk names would resolve without issue.

There are still potential problems here in that actions taken by the user that does not result in a route change has potential of failing. For example an action attempts to contact an end point that has changed API.

**Comment by christianvogt** [comment]
Lots of these errors reported in sentry.
```
Uncaught (in promise): Error: Loading chunk 11 failed.
Error: Loading chunk 11 failed.
    at HTMLScriptElement.onScriptComplete (https://openshift.io/_assets/lib/polyfills.ee9f94b796931054ccbf.bundle.js:1:659)
    at HTMLScriptElement.h (https://openshift.io/_assets/lib/polyfills.ee9f94b796931054ccbf.bundle.js:1:87435)
    at HTMLScriptElement.wrapped (https://openshift.io/_assets/lib/main.8eb481d57390e0f0d11d.bundle.js:1:695619)
    at ZoneDelegate.invokeTask (https://openshift.io/_assets/lib/polyfills.ee9f94b796931054ccbf.bundle.js:1:78248)
    at Object.onInvokeTask (https://openshift.io/_assets/lib/vendor.30b3db4a701076a9fc4c.bundle.js:1:91378)
    at ZoneDelegate.invokeTask (https://openshift.io/_assets/lib/polyfills.ee9f94b796931054ccbf.bundle.js:1:78169)
    at Zone.runTask (https://openshift.io/_assets/lib/polyfills.ee9f94b796931054ccbf.bundle.js:1:73299)
    at ZoneTask.invokeTask [as invoke] (https://openshift.io/_assets/lib/polyfills.ee9f94b796931054ccbf.bundle.js:1:79454)
    at p (https://openshift.io/_assets/lib/polyfills.ee9f94b796931054ccbf.bundle.js:1:56750)
    at HTMLScriptElement.h (https://openshift.io/_assets/lib/polyfills.ee9f94b796931054ccbf.bundle.js:1:56995)
```

**Comment by andrewazores** [comment]
Having the client check if a new version of the client is available seems like it makes sense. Causing a proper reload on path change would be a nice "automagic" feature, but perhaps a first step before implementing that could be to just display a banner informing the user that a new application version is available and that they can refresh the page to load it.
