### ISSUE TITLE
[f8a/workers] An error occurred (RequestThrottled) when calling the TagQueue operation

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#3329]
Following or similar error appears from time to time in worker's pre-hook container:

```
INFO:__main__:Creating or requesting QueueURL for queue 'STAGE_priority_CodeMetricsTask_v0'
DEBUG:__main__:Remote responded with {'ResponseMetadata': {'HTTPStatusCode': 200, 'RequestId': '3216c14d-9847-51c2-a228-921660f71dfe', 'RetryAttempts': 0, 'HTTPHeaders': {'x-amzn-requestid': '3216c14d-9847-51c2-a228-921660f71dfe', 'content-type': 'text/xml', 'date': 'Thu, 26 Apr 2018 15:55:28 GMT', 'connection': 'keep-alive', 'content-length': '225', 'server': 'Server'}}} after setting queue attributes for 'STAGE_priority_CodeMetricsTask_v0'
Traceback (most recent call last):
  File "/usr/bin/queue_conf.py", line 88, in <module>
    set_queue_attributes(sys.argv[1].split(','))
  File "/usr/bin/queue_conf.py", line 59, in set_queue_attributes
    'ENV': _DEPLOYMENT_PREFIX
  File "/usr/lib/python3.4/site-packages/botocore/client.py", line 324, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.4/site-packages/botocore/client.py", line 622, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (RequestThrottled) when calling the TagQueue operation (reached max retries: 4): Request is throttled.
```

**Comment by msrb** [comment]
We don't run the tagging tasks in staging/prod any more.
