### ISSUE TITLE
wildflyswarm rest http booster fails to build in the pipeline

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3430]
```
[0m[0m2018-05-03 10:14:50,029 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
[0m[0m2018-05-03 10:14:50,029 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Core 2.1.18.Final-redhat-1 "Kenny" started in 9604ms - Started 93 of 97 services (21 services are lazy, passive or on-demand)
[0m[0m2018-05-03 10:15:14,675 INFO  [org.wildfly.swarm.runtime.deployer] (main) deploying GreetingServiceTest.war
[0m[0m2018-05-03 10:15:22,414 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "GreetingServiceTest.war" (runtime-name: "GreetingServiceTest.war")
[0m
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 572.92 s <<< FAILURE! - in io.openshift.booster.GreetingServiceTest
[ERROR] io.openshift.booster.GreetingServiceTest  Time elapsed: 572.919 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
Caused by: org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   GreetingServiceTest.io.openshift.booster.GreetingServiceTest ? Deployment Proc...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:04 min
[INFO] Finished at: 2018-05-03T10:15:38+00:00
[INFO] Final Memory: 44M/69M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project app-test-rest-wildfly: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jenkins/workspace/pp-test-rest-wildfly_master-C57452VRCNA27KEK3SWGIKDQY7PT3EFAU74GAFCV4RK5BRLC7OVA/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project app-test-rest-wildfly: There are test failures.

Please refer to /home/jenkins/workspace/pp-test-rest-wildfly_master-C57452VRCNA27KEK3SWGIKDQY7PT3EFAU74GAFCV4RK5BRLC7OVA/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/jenkins/workspace/pp-test-rest-wildfly_master-C57452VRCNA27KEK3SWGIKDQY7PT3EFAU74GAFCV4RK5BRLC7OVA/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
	at org.apache.maven.plugin.surefire.SurefireHelper.throwException(SurefireHelper.java:204)
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:98)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:334)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:937)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by animuk** [comment]
reference issue: https://github.com/openshiftio/openshift.io/issues/3134
Updates from the wildflyswarm team : There will be no release of WF Swarm Boosters based on 7.1.0 until the end of May, any environment, anywhere
Only the community boosters have this fix, it's only the product boosters that are affected

**Comment by animuk** [comment]
As off now, Wildfly swarm -rest http community version is enabled at booster catalog and redhat version is disabled until this is fixed.
