### ISSUE TITLE
fabric8-init tenant failing to deploy in production

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3446]
found in logs of failing fabric8-inittenant:
```
pmcd: cannot open log "/dev/force-logging-to-stderr" for writing : Permission denied
Log for pmcd on f8tenant-474-jdj6m started Fri May  4 05:17:22 2018


active agent dom   pid  in out ver protocol parameters
============ === ===== === === === ======== ==========
pmcd           2                 2 dso i:6  lib=/var/lib/pcp/pmdas/pmcd/pmda_pmcd.so entry=pmcd_init [0x7f5a8c437550]
proc           3                 2 dso i:7  lib=/var/lib/pcp/pmdas/proc/pmda_proc.so entry=proc_init [0x7f5a8c2155f0]
linux         60                 2 dso i:7  lib=/var/lib/pcp/pmdas/linux/pmda_linux.so entry=linux_init [0x7f5a8bfe2980]
prometheus   144   121  13  14   2 bin pipe cmd=python /var/lib/pcp/pmdas/prometheus/pmdaprometheus.python

Host access list empty: host-based access control turned off
User access list empty: user-based access control turned off
Group access list empty: group-based access control turned off


pmcd: PID = 7, PDU version = 2
pmcd request port(s):
  sts fd   port  family address
  === ==== ===== ====== =======
  ok     5       unix   /var/run/pcp/pmcd.socket
  ok     3 44321 inet   INADDR_ANY
  ok     4 44321 ipv6   INADDR_ANY
[Fri May  4 05:17:23] pmcd(7) Info: PMNS file "DEFAULT" is unchanged
{"level":"info","msg":"Configured connection pool max idle 30","time":"2018-05-04 05:17:27"}
{"level":"info","msg":"Configured connection pool max open 30","time":"2018-05-04 05:17:27"}
{"current_version":4,"level":"info","msg":"Current version 4. Nothing to update.","next_version":5,"pkg":"github.com/fabric8-services/fabric8-tenant/migration","time":"2018-05-04 05:17:27"}
{"level":"info","msg":"toggles registered","payload":{"appName":"f8tenant","instanceId":"f8tenant-474-jdj6m","sdkVersion":"unleash-client-go:2.0.0","strategies":["default","applicationHostname","gradualRolloutRandom","gradualRolloutSessionId","gradualRolloutUserId","remoteAddress","userWithId"],"started":"2018-05-04T05:17:27.417254033Z","interval":60},"pkg":"github.com/fabric8-services/fabric8-tenant/toggles.listener","time":"2018-05-04 05:17:27"}
{"level":"info","msg":"toggles ready","pkg":"github.com/fabric8-services/fabric8-tenant/toggles.listener","time":"2018-05-04 05:17:27"}
{"key_id":"zD-57oBFIMUZsAWqUnIsVu_x71VIjd1irGkGUOiTsL8","level":"info","msg":"unmarshalled public key","pkg":"github.com/fabric8-services/fabric8-tenant/token","time":"2018-05-04 05:17:27"}
{"key_id":"PE6-BEECZZpPZIVxLR6NinbthOHJcGqYrfl8v7v6BVA","level":"info","msg":"unmarshalled public key","pkg":"github.com/fabric8-services/fabric8-tenant/token","time":"2018-05-04 05:17:27"}
{"level":"info","msg":"Public keys loaded","number_of_keys":2,"pkg":"github.com/fabric8-services/fabric8-tenant/token","time":"2018-05-04 05:17:27","url":"/api/token/keys"}
{"action":"Show","ctrl":"Status","level":"info","msg":"mount","route":"GET /api/status","time":"2018-05-04 05:17:27"}
{"action":"Clean","ctrl":"Tenant","level":"info","msg":"mount","route":"DELETE /api/tenant","security":"jwt","time":"2018-05-04 05:17:27"}
{"action":"Setup","ctrl":"Tenant","level":"info","msg":"mount","route":"POST /api/tenant","security":"jwt","time":"2018-05-04 05:17:27"}
{"action":"Show","ctrl":"Tenant","level":"info","msg":"mount","route":"GET /api/tenant","security":"jwt","time":"2018-05-04 05:17:27"}
{"action":"Update","ctrl":"Tenant","level":"info","msg":"mount","route":"PATCH /api/tenant","security":"jwt","time":"2018-05-04 05:17:27"}
{"action":"Delete","ctrl":"Tenants","level":"info","msg":"mount","route":"GET /api/tenants/:tenantID","security":"jwt","time":"2018-05-04 05:17:27"}
{"action":"Search","ctrl":"Tenants","level":"info","msg":"mount","route":"GET /api/tenants","security":"jwt","time":"2018-05-04 05:17:27"}
panic: wildcard already handles GET

goroutine 1 [running]:
github.com/fabric8-services/fabric8-tenant/vendor/github.com/dimfeld/httptreemux.(*node).setHandler(0xc420085900, 0xbb3599, 0x3, 0xc4203c02c0, 0x0)
	/tmp/go/src/github.com/fabric8-services/fabric8-tenant/vendor/github.com/dimfeld/httptreemux/tree.go:50 +0x2a7
github.com/fabric8-services/fabric8-tenant/vendor/github.com/dimfeld/httptreemux.(*Group).Handle.func1(0xbc4015, 0x16)
	/tmp/go/src/github.com/fabric8-services/fabric8-tenant/vendor/github.com/dimfeld/httptreemux/group.go:101 +0xfe
github.com/fabric8-services/fabric8-tenant/vendor/github.com/dimfeld/httptreemux.(*Group).Handle(0xc4201a2700, 0xbb3599, 0x3, 0xbc4015, 0x16, 0xc4203c02c0)
	/tmp/go/src/github.com/fabric8-services/fabric8-tenant/vendor/github.com/dimfeld/httptreemux/group.go:131 +0x1f0
github.com/fabric8-services/fabric8-tenant/vendor/github.com/goadesign/goa.(*mux).Handle(0xc4203a8b20, 0xbb3599, 0x3, 0xbc4015, 0x16, 0xc42041f080)
	/tmp/go/src/github.com/fabric8-services/fabric8-tenant/vendor/github.com/goadesign/goa/mux.go:62 +0x141
github.com/fabric8-services/fabric8-tenant/app.MountTenantsController(0xc420060720, 0xf2c840, 0xc4201665a0)
	/tmp/go/src/github.com/fabric8-services/fabric8-tenant/app/controllers.go:264 +0xc12
main.main()
	/tmp/go/src/github.com/fabric8-services/fabric8-tenant/main.go:178 +0x1453
```

seems related to https://github.com/fabric8-services/fabric8-tenant/commit/2614bf1824754901b7e2f9d7b4ad4d7e3bac61ff

**Comment by maxandersen** [comment]
prevents rollout of fix for https://github.com/openshiftio/openshift.io/issues/3422

**Comment by alexeykazakov** [comment]
Fixed by https://github.com/fabric8-services/fabric8-tenant/pull/588
