### ISSUE TITLE
HTTP 599  Could not resolve host: queue.amazonaws.com; Unknown error (None)

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#3567]
Graph-import worker seems to be stuck and it is not processing messages in this state.

It looks like it did not recover after an exception from kombu.

```
2018-05-09 19:23:57,162 [INFO] GraphImporterTask: Graph import succeeded with response: {
  "count_imported_EPVs": 1, 
  "epv": {
    "package_list": [
      {
        "ecosystem": "npm", 
        "name": "cross-env", 
        "version": "5.1.5"
      }
    ], 
    "select_ingest": [
      "source_licenses", 
      "dependency_snapshot", 
      "digests", 
      "security_issues", 
      "metadata"
    ]
  }, 
  "message": "The import finished successfully!"
}

{"node_args": {"_release": "npm:cross-env:5.1.5", "document_id": 6025899, "_audit": {"version": "v1", "ended_at": "2018-05-09T18:15:34.628916", "started_at": "2018-05-09T18:15:27.089890"}, "name": "cross-env", "version": "5.1.5", "recursive_limit": 0, "ecosystem": "npm"}, "task_id": "e7e91009-1836-4c49-95d8-b39e93b41f5f", "storage_name": "BayesianPostgres", "flow_name": "bayesianFlow", "task_name": "GraphImporterTask", "record_id": null, "storage_task_name": "GraphImporterTask", "event": "STORAGE_STORE"}
{"task_id": "e7e91009-1836-4c49-95d8-b39e93b41f5f", "queue": "prod_ingestion_GraphImporterTask_v0", "flow_name": "bayesianFlow", "storage": "BayesianPostgres", "node_args": {"_release": "npm:cross-env:5.1.5", "document_id": 6025899, "_audit": {"version": "v1", "ended_at": "2018-05-09T18:15:34.628916", "started_at": "2018-05-09T18:15:27.089890"}, "name": "cross-env", "version": "5.1.5", "recursive_limit": 0, "ecosystem": "npm"}, "dispatcher_id": "c644f611-582b-4a74-86b9-f167eda05ba3", "event": "TASK_END", "task_name": "GraphImporterTask", "parent": {"ResultCollector": "61b12d73-9f6c-45e7-8fce-3ae7892f9004"}}
2018-05-09 19:23:57,370 [INFO] celery.app.trace: Task selinon.SelinonTaskEnvelope[e7e91009-1836-4c49-95d8-b39e93b41f5f] succeeded in 2.233284065965563s: None
2018-05-09 19:24:13,384 [ERROR] kombu.async.hub: Error in timer: Exception('Request Empty body  HTTP 599  Could not resolve host: queue.amazonaws.com; Unknown error (None)',)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/kombu/async/hub.py", line 136, in fire_timers
    entry()
  File "/usr/lib/python3.4/site-packages/kombu/async/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/site-packages/kombu/async/timer.py", line 127, in _reschedules
    return fun(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/kombu/async/http/curl.py", line 108, in _timeout_check
    self._process_pending_requests()
  File "/usr/lib/python3.4/site-packages/kombu/async/http/curl.py", line 132, in _process_pending_requests
    self._process(curl, errno, reason)
  File "/usr/lib/python3.4/site-packages/kombu/async/http/curl.py", line 178, in _process
    buffer=buffer, effective_url=effective_url, error=error,
  File "/usr/lib/python3.4/site-packages/vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "/usr/lib/python3.4/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/usr/lib/python3.4/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/lib/python3.4/site-packages/vine/funtools.py", line 100, in _transback
    return callback(ret)
  File "/usr/lib/python3.4/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/usr/lib/python3.4/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/lib/python3.4/site-packages/vine/funtools.py", line 98, in _transback
    callback.throw()
  File "/usr/lib/python3.4/site-packages/vine/funtools.py", line 96, in _transback
    ret = filter_(*args + (ret,), **kwargs)
  File "/usr/lib/python3.4/site-packages/kombu/async/aws/connection.py", line 233, in _on_list_ready
    raise self._for_status(response, response.read())
Exception: Request Empty body  HTTP 599  Could not resolve host: queue.amazonaws.com; Unknown error (None)
```

**Comment by msrb** [comment]
I'd expect pod to restart, which would automatically fix this issue.

**Comment by msrb** [comment]
I restarted the pod.

**Comment by CermakM** [comment]
It is most likely bug in the upstream. There are quite a lot of related issues already:

- https://github.com/celery/celery/labels/Worker%20Hangs
- https://github.com/celery/celery/issues/4185
- https://github.com/celery/celery/issues/3712
- https://github.com/celery/celery/issues/3819
- ...

Also, the issue is very hard to reproduce, as it is caused by AWS.

<br>

As was discussed with @msrb, it will be necessary to do some ground work around worker monitoring and find out a way to diagnose worker status and act upon it.

**Comment by msrb** [comment]
Thanks for the summary Marek. Let's move this issue to backlog for now and create new issue for worker monitoring. I will take care of that.

**Comment by CermakM** [comment]
Agreed, Thanks @msrb
