### ISSUE TITLE
Importing a repository yield an error

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#373]
Importing a simple repository and I am getting an error message like this :  

`ExecuteForgeCommandError
The fabric8-import-git :: execute :: 3 command failed or only partially succeeded
name
ForgeApiClientExceptionError
origin
Fabric8ForgeService
message
An unexpected error occurred while consuming the http response returned from the server
inner
inner
message
Cannot read property 'type' of undefined
stack
TypeError: Cannot read property 'type' of undefined
at Fabric8ForgeService.handleError (https://www.openshift.io/_assets/lib/main.b5b4a29ce51127dab583.bundle.js:1:1253258)
at CatchSubscriber.selector (https://www.openshift.io/_assets/lib/main.b5b4a29ce51127dab583.bundle.js:1:1255714)
at CatchSubscriber.error (https://www.openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:598663)
at MapSubscriber.Subscriber._error (https://www.openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:194997)
at MapSubscriber.Subscriber.error (https://www.openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:194655)
at XMLHttpRequest.a (https://www.openshift.io/_assets/lib/main.b5b4a29ce51127dab583.bundle.js:1:184367)
at ZoneDelegate.invokeTask (https://www.openshift.io/_assets/lib/polyfills.f49acb8aeb061f0c40eb.bundle.js:1:64855)
at Object.onInvokeTask (https://www.openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:93135)
at ZoneDelegate.invokeTask (https://www.openshift.io/_assets/lib/polyfills.f49acb8aeb061f0c40eb.bundle.js:1:64776)
at Zone.runTask (https://www.openshift.io/_assets/lib/polyfills.f49acb8aeb061f0c40eb.bundle.js:1:59629)
at XMLHttpRequest.ZoneTask.invoke (https://www.openshift.io/_assets/lib/polyfills.f49acb8aeb061f0c40eb.bundle.js:1:65863)
status
500
ok
false
statusText
Internal Server Error
headers
type
2
url
https://forge.api.openshift.io/forge/commands/fabric8-import-git/execute
 OK
`

(Use cboudjna, trying to import github/chmouel/chmoufrack repository)

**Comment by joshuawilson** [comment]
@jstrachan any ideas on this one?
@alexeykazakov could this have anything to do with the account?

**Comment by jstrachan** [comment]
this is a fabric8-ui JavaScript error not reporting the underlying error; I'm afraid I've no clue what the real error is other than the server side returned 500. I thought this fabric8-ui was meant to be fixed recently though? @corinnekrych any idea?

**Comment by jstrachan** [comment]
It took a fair bit of effort but I've found your server side error. Its actually this:
```
ERROR [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-9) Failed to create Jenkins Organisation ConfigMap: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://api.starter-us-east-2.openshift.com/api/v1/configmaps/chmouel. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "cboudjna@redhat.com" cannot get configmaps at the cluster scope.: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://api.starter-us-east-2.openshift.com/api/v1/configmaps/chmouel. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "cboudjna@redhat.com" cannot get configmaps at the cluster scope.
```
So its looking like your OSO token doesn't have karma to get ConfigMaps in your main namespace `chmouel` which sounds wonky - sounds like your OSO account is a bit screwed up?

**Comment by jstrachan** [comment]
Aha! I've found it - this is a regression by the previous fix to avoid the Jenkins master; its broken for import (the namespace is not specified for the import goal).

Should be fixed shortly...

**Comment by jstrachan** [comment]
this is now fixed in production

**Comment by joshuawilson** [comment]
thanks @jstrachan

**Comment by chmouel** [comment]
wfm :)

![image](https://user-images.githubusercontent.com/98980/28425154-c030cda8-6d6f-11e7-910e-e5f36518ed4f.png)
