### ISSUE TITLE
WIT deployments are broken after latest DB migration

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#3879]
The latest commit in WIT master contains a DB migration step - https://github.com/fabric8-services/fabric8-wit/pull/2133
It seems that that migration broke something.
Now WIT deployments fail in both preview and prod:

```
﻿pmcd: cannot open log "/dev/force-logging-to-stderr" for writing : Permission denied
Log for pmcd on core-112-tcnp4 started Thu Jun 28 20:37:29 2018


active agent dom   pid  in out ver protocol parameters
============ === ===== === === === ======== ==========
pmcd           2                 2 dso i:6  lib=/var/lib/pcp/pmdas/pmcd/pmda_pmcd.so entry=pmcd_init [0x7f4e6d818500]
proc           3                 2 dso i:7  lib=/var/lib/pcp/pmdas/proc/pmda_proc.so entry=proc_init [0x7f4e6d5f7620]
linux         60                 2 dso i:7  lib=/var/lib/pcp/pmdas/linux/pmda_linux.so entry=linux_init [0x7f4e6d3c3d90]
prometheus   144   120  13  14   2 bin pipe cmd=python /var/lib/pcp/pmdas/prometheus/pmdaprometheus.python

Host access list empty: host-based access control turned off
User access list empty: user-based access control turned off
Group access list empty: group-based access control turned off


pmcd: PID = 6, PDU version = 2
pmcd request port(s):
  sts fd   port  family address
  === ==== ===== ====== =======
  ok     5       unix   /var/run/pcp/pmcd.socket
  ok     3 44321 inet   INADDR_ANY
  ok     4 44321 ipv6   INADDR_ANY
[Thu Jun 28 20:37:30] pmcd(6) Info: PMNS file "DEFAULT" is unchanged
time="2018-06-28T20:37:34Z" level=warning msg="unable to parse log level configuration error: \"not a valid logrus Level: \\\"\\\"\"" 
{"err":"user: unknown userid 1000070000","file":"/tmp/go/src/github.com/fabric8-services/fabric8-wit/main.go","func":"main.printUserInfo","level":"warning","msg":"failed to get current user","pkg":"main","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Configured connection pool max idle 90","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Configured connection pool max open 90","time":"2018-06-28 20:37:34"}
{"current_version":94,"level":"info","msg":"Current version 94. Nothing to update.","next_version":95,"pkg":"migration","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Loading work item link category","pkg":"workitem/link","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wilc_id":"b1482c65-a64d-4058-beb0-62f7198cb0f4"}
{"category":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z","ID":"b1482c65-a64d-4058-beb0-62f7198cb0f4","Name":"system","Description":"The system category is reserved for link types that are to be manipulated by the system only.","Version":0},"level":"info","msg":"Work item link category system exists, will update/overwrite the description","pkg":"migration","req_id":"eXF2krls","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Loading work item link category","pkg":"workitem/link","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wilc_id":"2f24724f-797c-4073-8b16-4bb8ce9e84a6"}
{"category":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z","ID":"2f24724f-797c-4073-8b16-4bb8ce9e84a6","Name":"user","Description":"The user category is reserved for link types that can to be manipulated by the user.","Version":0},"level":"info","msg":"Work item link category user exists, will update/overwrite the description","pkg":"migration","req_id":"eXF2krls","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"loading work item link type","pkg":"workitem/link","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wilt_id":"2cea3c79-3b79-423b-90f4-1e59174c8f43"}
{"level":"info","msg":"loading work item link type","pkg":"workitem/link","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wilt_id":"9b631885-83b1-4abb-a340-3a9ede8493fa"}
{"level":"info","msg":"loading work item link type","pkg":"workitem/link","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wilt_id":"25c326a7-6d03-4f5a-b23b-86a9ee4171e9"}
{"level":"info","msg":"space template imported successfully","pkg":"spacetemplate/importer","req_id":"eXF2krls","space_template_id":"1f48b7bf-bc51-4823-8101-9f10039035ba","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"bbf35418-04b6-426c-a60b-7f80beb0b624"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"26787039-b68f-4e28-8814-c2f93be1ef4e"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"0a24d3c2-e0a6-4686-8051-ec0ea1915a28"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"b9a71831-c803-4f66-8774-4193fffd1311"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"3194ab60-855b-4155-9005-9dce4a05f1eb"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"71171e90-6d35-498f-a6a7-2083b5267c18"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"ee7ca005-f81d-4eea-9b9b-1965df0988d0"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"6d603ab4-7c5e-4c5f-bba8-a3ba9d370985"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"space template imported successfully","pkg":"spacetemplate/importer","req_id":"eXF2krls","space_template_id":"929c963a-174c-4c37-b487-272067e88bd4","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"d3f48c61-b3d6-4971-b8b3-28d90543223f"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"ec6918d6-f732-4fc0-a902-6571415aa73c"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"d3f48c61-b3d6-4971-b8b3-28d90543223f"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"db906e00-a5fa-4a86-8ef7-772c89f703ac"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"d3f48c61-b3d6-4971-b8b3-28d90543223f"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"90e961d1-0de8-49f4-b197-ba13418c20a8"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"d3f48c61-b3d6-4971-b8b3-28d90543223f"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"23b1dfd5-f497-4843-97c3-e3eefdc9930e"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"d3f48c61-b3d6-4971-b8b3-28d90543223f"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"83852318-a69a-4092-a412-bb67527c4ba6"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"d3f48c61-b3d6-4971-b8b3-28d90543223f"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"f450d7d0-3d38-4887-83ca-38d27c109b59"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"d3f48c61-b3d6-4971-b8b3-28d90543223f"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"space template imported successfully","pkg":"spacetemplate/importer","req_id":"eXF2krls","space_template_id":"cfff59dc-007a-4fa5-acf7-376d5345aef2","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"719beee7-07cb-489c-9a4b-9618d45df35a"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"86af5178-9b41-469b-9096-57e5155c3f31"}
{"level":"info","msg":"Clearing work item cache","pkg":"workitem","time":"2018-06-28 20:37:34"}
{"level":"info","msg":"Work item type doesn't exist in the cache. Loading from DB...","pkg":"workitem","req_id":"eXF2krls","time":"2018-06-28 20:37:34","wit_id":"03b9bb64-4f65-4fa7-b165-494cd4f01401"}
{"err":"type of the field resolution changed from {{enum} {string} [Done Rejected Duplicate Incomplete Description Can not Reproduce Partially Completed Deferred Won't Fix Out of Date Explained Verified] %!s(bool=false)} to {{enum} {string} [None Done Duplicate Incomplete Description Can not Reproduce Deferred Won't Fix Out of Date Verified] %!s(bool=false)}","file":"/tmp/go/src/github.com/fabric8-services/fabric8-wit/spacetemplate/importer/repository.go","func":"github.com/fabric8-services/fabric8-wit/spacetemplate/importer.(*GormRepository).Import","level":"error","line":89,"msg":"failed to create or update work item types","pid":1,"pkg":"spacetemplate/importer","req_id":"eXF2krls","space_template":{"space_template":{"lifecycle":{"created_at":"2018-06-19T08:38:34.4124Z","updated_at":"2018-06-28T20:37:34.815533Z"},"id":"f405fa41-a8bb-46db-8800-2dbe13da1418","version":0,"name":"Agile","description":"An agile software development framework for managing development.\n","can_construct":true},"work_item_types":[{"lifecycle":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"},"id":"719beee7-07cb-489c-9a4b-9618d45df35a","name":"Agile Common Type","description":"This is the work item type that defines the common fields that are shared among all for all work item types of the agile template. It extends the planner item type and thereby already provides a great deal of common fields.\n","icon":"fa fa-question","space_template_id":"f405fa41-a8bb-46db-8800-2dbe13da1418","extends":"86af5178-9b41-469b-9096-57e5155c3f31"},{"lifecycle":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"},"id":"03b9bb64-4f65-4fa7-b165-494cd4f01401","name":"Impediment","description":"This describes an impediment blocking work on the project.\n","icon":"fa fa-stumbleupon","fields":{"resolution":{"required":false,"read_only":false,"label":"Resolution","description":"The reason why this work item's state was last changed.\n","type":{"simple_type":{"kind":"enum"},"base_type":{"kind":"string"},"values":["None","Done","Duplicate","Incomplete Description","Can not Reproduce","Deferred","Won't Fix","Out of Date","Verified"],"rewritable_values":false}},"system.state":{"required":true,"read_only":false,"label":"State","description":"The state of the impediment.","type":{"simple_type":{"kind":"enum"},"base_type":{"kind":"string"},"values":["New","Open","In Progress","Resolved","Closed"],"rewritable_values":false}}},"space_template_id":"f405fa41-a8bb-46db-8800-2dbe13da1418","extends":"719beee7-07cb-489c-9a4b-9618d45df35a","can_construct":true},{"lifecycle":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"},"id":"5182fc8c-b1d6-4c3d-83ca-6a3c781fa18a","name":"Theme","description":"A theme describes a high-level description of a functionality on the system.","icon":"fa fa-puzzle-piece","fields":{"acceptance_criteria":{"required":false,"read_only":false,"label":"Acceptance criteria","description":"The acceptance criteria describes rules for checking if a chunk of work is completed.","type":{"kind":"markup"}},"business_value":{"required":false,"read_only":false,"label":"Business Value","description":"Business value for this theme.","type":{"kind":"string"}},"system.state":{"required":true,"read_only":false,"label":"State","description":"The state of the theme.","type":{"simple_type":{"kind":"enum"},"base_type":{"kind":"string"},"values":["New","Open","In Progress","Resolved","Closed"],"rewritable_values":false}},"target_date":{"required":false,"read_only":false,"label":"Target date","description":"The target completion date of the theme.","type":{"kind":"instant"}}},"space_template_id":"f405fa41-a8bb-46db-8800-2dbe13da1418","extends":"719beee7-07cb-489c-9a4b-9618d45df35a","can_construct":true,"child_types":["fce0921f-ea70-4513-bb91-31d3aa8017f1","2c169431-a55d-49eb-af74-cc19e895356f","03b9bb64-4f65-4fa7-b165-494cd4f01401"]},{"lifecycle":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"},"id":"2c169431-a55d-49eb-af74-cc19e895356f","name":"Epic","description":"An epic describes a larger composition of stories to be implemented.","icon":"fa fa-bullseye","fields":{"acceptance_criteria":{"required":false,"read_only":false,"label":"Acceptance criteria","description":"The acceptance criteria describes rules for checking if a chunk of work is completed.","type":{"kind":"markup"}},"storypoints":{"required":false,"read_only":false,"label":"Storypoints","description":"The effort needed to implement the epic.","type":{"kind":"float"}},"system.state":{"required":true,"read_only":false,"label":"State","description":"The state of the Epic.","type":{"simple_type":{"kind":"enum"},"base_type":{"kind":"string"},"values":["New","Open","In Progress","Resolved","Closed"],"rewritable_values":false}}},"space_template_id":"f405fa41-a8bb-46db-8800-2dbe13da1418","extends":"719beee7-07cb-489c-9a4b-9618d45df35a","can_construct":true,"child_types":["fce0921f-ea70-4513-bb91-31d3aa8017f1","6ff83406-caa7-47a9-9200-4ca796be11bb","03b9bb64-4f65-4fa7-b165-494cd4f01401"]},{"lifecycle":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"},"id":"6ff83406-caa7-47a9-9200-4ca796be11bb","name":"Story","description":"A user story describes an executable chunk of a feature based on user experience.","icon":"pficon pficon-image","fields":{"acceptance_criteria":{"required":false,"read_only":false,"label":"Acceptance criteria","description":"The acceptance criteria describes rules for checking if a chunk of work is completed.","type":{"kind":"markup"}},"component":{"required":false,"read_only":false,"label":"Component","description":"The component for this area of work.","type":{"kind":"string"}},"storypoints":{"required":false,"read_only":false,"label":"Storypoints","description":"The effort needed to implement this user story.","type":{"kind":"float"}},"system.state":{"required":true,"read_only":false,"label":"State","description":"The state of the story item.","type":{"simple_type":{"kind":"enum"},"base_type":{"kind":"string"},"values":["New","Open","In Progress","Resolved","Closed"],"rewritable_values":false}}},"space_template_id":"f405fa41-a8bb-46db-8800-2dbe13da1418","extends":"719beee7-07cb-489c-9a4b-9618d45df35a","can_construct":true,"child_types":["2853459d-60ef-4fbe-aaf4-eccb9f554b34","fce0921f-ea70-4513-bb91-31d3aa8017f1","03b9bb64-4f65-4fa7-b165-494cd4f01401"]},{"lifecycle":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"},"id":"2853459d-60ef-4fbe-aaf4-eccb9f554b34","name":"Task","description":"An atomic task on the project.","icon":"fa fa-tasks","fields":{"effort":{"required":false,"read_only":false,"label":"Effort","description":"The effort needed to implement this user story.","type":{"kind":"float"}},"system.state":{"required":true,"read_only":false,"label":"State","description":"The state of the Task.","type":{"simple_type":{"kind":"enum"},"base_type":{"kind":"string"},"values":["New","Open","In Progress","Resolved","Closed"],"rewritable_values":false}}},"space_template_id":"f405fa41-a8bb-46db-8800-2dbe13da1418","extends":"719beee7-07cb-489c-9a4b-9618d45df35a","can_construct":true},{"lifecycle":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"},"id":"fce0921f-ea70-4513-bb91-31d3aa8017f1","name":"Defect","description":"This describes a defect in the system.","icon":"fa fa-bug","fields":{"effort":{"required":false,"read_only":false,"label":"Effort","description":"The effort needed to fix this defect.","type":{"kind":"float"}},"environment":{"required":false,"read_only":false,"label":"Environment","description":"The environment where this defect appears.","type":{"kind":"markup"}},"priority":{"required":false,"read_only":false,"label":"Priority","description":"The order in which the developer should resolve a defect.","type":{"simple_type":{"kind":"enum"},"base_type":{"kind":"string"},"values":["P1 - Critical","P2 - High","P3 - Medium","P4 - Low"],"rewritable_values":false}},"repro_steps":{"required":false,"read_only":false,"label":"Steps to reproduce","description":"Steps to reproduce the defect.","type":{"kind":"markup"}},"resolution":{"required":false,"read_only":false,"label":"Resolution","description":"The reason why this defect's state was last changed.\n","type":{"simple_type":{"kind":"enum"},"base_type":{"kind":"string"},"values":["Done","Duplicate","Incomplete Description","Can not Reproduce","Deferred","Won't Fix","Out of Date","Verified"],"rewritable_values":false}},"severity":{"required":false,"read_only":false,"label":"Severity","description":"The degree of impact that a defect has on the operation of the product or impact on security.","type":{"simple_type":{"kind":"enum"},"base_type":{"kind":"string"},"values":["SEV1 - Urgent","SEV2 - High","SEV3 - Medium","SEV4 - Low"],"rewritable_values":false}},"system.state":{"required":true,"read_only":false,"label":"State","description":"The state of the defect.","type":{"simple_type":{"kind":"enum"},"base_type":{"kind":"string"},"values":["New","Open","In Progress","Resolved","Closed"],"rewritable_values":false}}},"space_template_id":"f405fa41-a8bb-46db-8800-2dbe13da1418","extends":"719beee7-07cb-489c-9a4b-9618d45df35a","can_construct":true}],"work_item_link_types":[{"lifecycle":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"},"id":"48b1b953-ddf3-473d-8527-e705f7c5f943","name":"Impedes","description":"One work item item impedes another one","version":0,"topology":"dependency","forward_name":"impedes","reverse_name":"is impeded by","link_category_id":"00000000-0000-0000-0000-000000000000","space_template_id":"f405fa41-a8bb-46db-8800-2dbe13da1418"}],"work_item_type_groups":[{"lifecycle":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"},"id":"1c21af72-59ab-43d7-a84c-e76ee8ed3342","space_template_id":"f405fa41-a8bb-46db-8800-2dbe13da1418","bucket":"portfolio","name":"Work Items","icon":"fa fa-bullseye","type_list":["5182fc8c-b1d6-4c3d-83ca-6a3c781fa18a","2c169431-a55d-49eb-af74-cc19e895356f","6ff83406-caa7-47a9-9200-4ca796be11bb","2853459d-60ef-4fbe-aaf4-eccb9f554b34","fce0921f-ea70-4513-bb91-31d3aa8017f1","03b9bb64-4f65-4fa7-b165-494cd4f01401"]},{"lifecycle":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"},"id":"49d1a19f-02b4-4a10-a774-5723299f8944","space_template_id":"f405fa41-a8bb-46db-8800-2dbe13da1418","bucket":"iteration","name":"Execution","icon":"fa fa-repeat","type_list":["5182fc8c-b1d6-4c3d-83ca-6a3c781fa18a","2c169431-a55d-49eb-af74-cc19e895356f","6ff83406-caa7-47a9-9200-4ca796be11bb","2853459d-60ef-4fbe-aaf4-eccb9f554b34","fce0921f-ea70-4513-bb91-31d3aa8017f1","03b9bb64-4f65-4fa7-b165-494cd4f01401"]}]},"time":"2018-06-28 20:37:34"}
{"err":"failed to create or update work item types: type of the field resolution changed from {{enum} {string} [Done Rejected Duplicate Incomplete Description Can not Reproduce Partially Completed Deferred Won't Fix Out of Date Explained Verified] %!s(bool=false)} to {{enum} {string} [None Done Duplicate Incomplete Description Can not Reproduce Deferred Won't Fix Out of Date Verified] %!s(bool=false)}","file":"/tmp/go/src/github.com/fabric8-services/fabric8-wit/migration/migration.go","func":"github.com/fabric8-services/fabric8-wit/migration.PopulateCommonTypes","id":"f405fa41-a8bb-46db-8800-2dbe13da1418","level":"error","line":655,"msg":"failed to import space template #3 with name \"Agile\" and ID f405fa41-a8bb-46db-8800-2dbe13da1418","name":"Agile","pid":1,"pkg":"migration","req_id":"eXF2krls","time":"2018-06-28 20:37:34"}
{"err":"failed to import space template #3 with name \"Agile\" and ID f405fa41-a8bb-46db-8800-2dbe13da1418: failed to create or update work item types: type of the field resolution changed from {{enum} {string} [Done Rejected Duplicate Incomplete Description Can not Reproduce Partially Completed Deferred Won't Fix Out of Date Explained Verified] %!s(bool=false)} to {{enum} {string} [None Done Duplicate Incomplete Description Can not Reproduce Deferred Won't Fix Out of Date Verified] %!s(bool=false)}","level":"panic","msg":"failed to populate common types","pid":1,"req_id":"eXF2krls","time":"2018-06-28 20:37:34"}
panic: (*logrus.Entry) (0x1a8b840,0xc420075b30)

goroutine 1 [running]:
github.com/fabric8-services/fabric8-wit/vendor/github.com/sirupsen/logrus.Entry.log(0xc420074500, 0xc420938180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/sirupsen/logrus/entry.go:124 +0x5eb
github.com/fabric8-services/fabric8-wit/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc420075ae0, 0xc420af38a8, 0x1, 0x1)
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/sirupsen/logrus/entry.go:169 +0xa8
github.com/fabric8-services/fabric8-wit/vendor/github.com/sirupsen/logrus.(*Entry).Panicln(0xc420075ae0, 0xc420af3930, 0x1, 0x1)
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/vendor/github.com/sirupsen/logrus/entry.go:264 +0xe0
github.com/fabric8-services/fabric8-wit/log.Panic(0x27ea680, 0xc42062a090, 0xc420938090, 0x1b1acd8, 0x1f, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/log/log.go:248 +0x23c
main.main()
	/tmp/go/src/github.com/fabric8-services/fabric8-wit/main.go:150 +0x41a0
```

**Comment by alexeykazakov** [comment]
@kwk @michaelkleinhenz

**Comment by jarifibrahim** [comment]
The migrations are failing because the `values` for impediment field were changed but no `sql migration script` was added for it. We need sql migration script for these fields https://github.com/fabric8-services/fabric8-wit/pull/2133/files#diff-ef9bca69129f8d8e357ad2ba0192455aL55

**Comment by kwk** [comment]
> The migrations aren't failing, the initial loading of space templates is failing because the values for impediment field were changed but no sql migration script was added for it. We need sql migration script for these fields https://github.com/fabric8-services/fabric8-wit/pull/2133/files#diff-ef9bca69129f8d8e357ad2ba0192455aL55

@jarifibrahim I know which is why I said that in the mattermost chat.

**Comment by kwk** [comment]
This was fixed with https://github.com/openshiftio/saas-openshiftio/commit/3fe35033026a05182d38bb562542ebfb5ccf1c2d.
