### ISSUE TITLE
On prod-preview, blank booster with Vert.X runtime fails to run in CHE with ClassNotFoundException

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3948]
Steps to reproduce:
* On prod-preview:
* Create new space and new project
* In the new project, select mission = blank and Runtime = Vert.X
* Create a new Che workspace for the blank booster
* In Che, select 'run' from toolbar
* Observe this error:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building vertx-application 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- vertx-maven-plugin:1.0.15:initialize (vmp) @ vertx-application ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ vertx-application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /projects/july10test7/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ vertx-application ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- vertx-maven-plugin:1.0.15:run (default-cli) @ vertx-application ---
[INFO] Launching Vert.x Application
[INFO] Vert.x application redeploy enabled
[INFO] Observing path:/projects/july10test7/src/main
[INFO] Jul 10, 2018 8:11:53 PM io.vertx.core.impl.launcher.commands.Watcher
[INFO] INFO: Watched paths: [/projects/july10test7/target/classes]
[INFO] Jul 10, 2018 8:11:53 PM io.vertx.core.impl.launcher.commands.Watcher
[INFO] INFO: Starting the vert.x application in redeploy mode
[INFO] Starting vert.x application...
[INFO] 47919ffa-40e6-4801-ba09-0fbc7679eb25-redeploy
[INFO] java.lang.ClassNotFoundException: redeploy-termination-period=1000
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:42)
[INFO] 	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:234)
[INFO] 	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:207)
[INFO] 	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
[INFO] 	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:176)
[INFO] 	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:148)
[INFO] 	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:136)
[INFO] 	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:650)
[INFO] 	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:164)
[INFO] 	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:401)
[INFO] 	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:274)
[INFO] 	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
[INFO] 	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
[INFO] 	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
[INFO] 	at io.vertx.core.Launcher.main(Launcher.java:49)
[INFO] Jul 10, 2018 8:11:53 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
[INFO] SEVERE: Failed in deploying verticle
[INFO] java.lang.ClassNotFoundException: redeploy-termination-period=1000
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:42)
[INFO] 	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:234)
[INFO] 	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:207)
[INFO] 	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
[INFO] 	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:176)
[INFO] 	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:148)
[INFO] 	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:136)
[INFO] 	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:650)
[INFO] 	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:164)
[INFO] 	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:401)
[INFO] 	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:274)
[INFO] 	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
[INFO] 	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
[INFO] 	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
[INFO] 	at io.vertx.core.Launcher.main(Launcher.java:49)
[INFO] 
[INFO] java.lang.ClassNotFoundException: redeploy-termination-period=1000
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:42)
[INFO] 	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:234)
[INFO] 	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:207)
[INFO] 	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
[INFO] 	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:176)
[INFO] 	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:148)
[INFO] 	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:136)
[INFO] 	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:650)
[INFO] 	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:164)
[INFO] 	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:401)
[INFO] 	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:274)
[INFO] 	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
[INFO] 	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
[INFO] 	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
[INFO] 	at io.vertx.core.Launcher.main(Launcher.java:49)

```

**Comment by bartoszmajsak** [comment]
This, in fact, was even visible during Sprint Demo. Thanks for filing this issue.

**Comment by bartoszmajsak** [comment]
When I hit ">" `run` command I'm getting different error though

```
scl enable rh-maven33 'mvn compile vertx:run -f -Dvertx.disableDnsResolver=true'https://routepsxxyjhu-bartosz-1-che.1b7d.free-stg.openshiftapps.com
Unable to parse command line options: Missing argument for option: f
```

**Comment by animuk** [comment]
@ldimaggi at the moment, Blank mission booster is an empty repo with proper core run time dependencies. You can build in Che, but could not able to run unless developer put in the relavant codes in the repo to make it work. 
@ravsa please comment on this

**Comment by animuk** [comment]
This is as per designed.

**Comment by bartoszmajsak** [comment]
I don't agree with this design as we ship not working code at the moment. We could equally well just don't add any code nor runtime specific plugins. Re-opening until we address the gaps.
