### ISSUE TITLE
New Space / vanilla fails,  broken socket  

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#3958]
A new Space with a vanilla project (Spring Boot / REST) fails in the initial build.

The root of the problem seems to be:

org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 4 more
Caused by: java.net.SocketException: Connection reset

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot - HTTP Booster 1.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ july11 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java-version) @ july11 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-maven-version) @ july11 ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ july11 ---
Jul 11, 2018 2:50:44 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo1.maven.org:443: Connection reset
Jul 11, 2018 2:50:44 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo1.maven.org:443
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.866 s
[INFO] Finished at: 2018-07-11T14:50:45+00:00
[INFO] Final Memory: 20M/29M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (get-scm-revision) on project july11: Execution get-scm-revision of goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create failed: Plugin org.codehaus.mojo:buildnumber-maven-plugin:1.4 or one of its dependencies could not be resolved: Could not transfer artifact org.tmatesoft.svnkit:svnkit:jar:1.8.5 from/to central (https://repo1.maven.org/maven2): GET request of: org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar from central failed: Connection reset -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (get-scm-revision) on project july11: Execution get-scm-revision of goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create failed: Plugin org.codehaus.mojo:buildnumber-maven-plugin:1.4 or one of its dependencies could not be resolved: Could not transfer artifact org.tmatesoft.svnkit:svnkit:jar:1.8.5 from/to central (https://repo1.maven.org/maven2): GET request of: org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar from central failed
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution get-scm-revision of goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create failed: Plugin org.codehaus.mojo:buildnumber-maven-plugin:1.4 or one of its dependencies could not be resolved: Could not transfer artifact org.tmatesoft.svnkit:svnkit:jar:1.8.5 from/to central (https://repo1.maven.org/maven2): GET request of: org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar from central failed
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.codehaus.mojo:buildnumber-maven-plugin:1.4 or one of its dependencies could not be resolved: Could not transfer artifact org.tmatesoft.svnkit:svnkit:jar:1.8.5 from/to central (https://repo1.maven.org/maven2): GET request of: org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar from central failed
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:218)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:400)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:372)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:231)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:102)
	... 21 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.tmatesoft.svnkit:svnkit:jar:1.8.5 from/to central (https://repo1.maven.org/maven2): GET request of: org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar from central failed
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:210)
	... 26 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.tmatesoft.svnkit:svnkit:jar:1.8.5 from/to central (https://repo1.maven.org/maven2): GET request of: org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar from central failed
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.wagon.TransferFailedException: GET request of: org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar from central failed
	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:363)
	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:316)
	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:285)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:97)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 4 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.maven.wagon.providers.http.httpclient.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.maven.wagon.providers.http.httpclient.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:195)
	at org.apache.maven.wagon.providers.http.httpclient.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.maven.wagon.providers.http.httpclient.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:531)
	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:353)
	... 13 more

**Comment by RickJWagner** [comment]
Note: a Build restart did not show the error a second time, the Build completed without incident.
