### ISSUE TITLE
Unstable data-importer tests

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#4014]
Tests in data-importer are failing randomly, but very often: https://ci.centos.org/view/Devtools/job/devtools-fabric8-analytics-data-model-f8a-build-master/

Out of last 30 builds, only 5 of them succeeded.

With such unstable test suite, it would be almost impossible to push (tested) fixes to production for urgent issues.

```
Traceback (most recent call last):
  File "/root/payload/env-test/lib/python2.7/site-packages/_pytest/config.py", line 371, in _importconftest
    mod = conftestpath.pyimport()
  File "/root/payload/env-test/lib/python2.7/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/root/payload/env-test/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/root/payload/env-test/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/root/payload/test/conftest.py", line 5, in <module>
    from rest_api import create_app
  File "/root/payload/src/rest_api.py", line 286, in <module>
    raise RuntimeError("Failed to initialized graph schema")
RuntimeError: Failed to initialized graph schema
ERROR: could not load /root/payload/test/conftest.py
```

**Comment by msrb** [comment]
Fixed by https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/185.
