### ISSUE TITLE
Not able to build any Quickstart Application

### ISSUE THREAD

**Issue by piyush1594** [openshiftio/openshift.io#4077]
Steps to reproduce:

1. Go to your space.
2. Create an application
3. Choose a new codebase.
4. Follow all the steps and Setup application
5. See that master build fails with error.

Error:
```
Checking out Revision 47286003a6ac353d3cedc162ddbf634258c679be (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 47286003a6ac353d3cedc162ddbf634258c679be
Commit message: "Get space label from Build object and pass to fabric8-maven-plugin (#390)"
First time build. Skipping changelog.

GitHub has been notified of this commit’s build result

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/var/lib/jenkins/jobs/piyush1594/jobs/testtststtss/branches/master/builds/1/libs/github.com/fabric8io/fabric8-pipeline-library/src/io/fabric8/Fabric8Commands.groovy: 6: unable to resolve class io.fabric8.kubernetes.api.KubernetesHelper
 @ line 6, column 1.
   import io.fabric8.kubernetes.api.KubernetesHelper
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:554)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:133)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:557)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:518)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:290)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

I tried around 7-8 times and all failing for me. I don't know if its something related to my account only.

**Comment by piyush1594** [comment]
This is still an issue if we upgrade the latest tenant to prod. Reopening it. This is not in prod. But upgrading to prod is blocked on this.

**Comment by piyush1594** [comment]
This has been fixed using https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/183

Closing this.
