### ISSUE TITLE
[analytics/golang] IndexError: string index out of range

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#4087]
```
worker-ingestion_1      | 2018-07-30 08:39:39,889 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[00be7407-9398-48d0-abb9-d0f87145f735] raised unexpected: IndexError('string index out of range',)
worker-ingestion_1      | Traceback (most recent call last):
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 375, in trace_task
worker-ingestion_1      |     R = retval = fun(*args, **kwargs)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 632, in __protected_call__
worker-ingestion_1      |     return self.run(*args, **kwargs)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/selinon/task_envelope.py", line 169, in run
worker-ingestion_1      |     raise self.retry(max_retries=0, exc=exc)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
worker-ingestion_1      |     raise_with_context(exc)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/selinon/task_envelope.py", line 114, in run
worker-ingestion_1      |     result = task.run(node_args)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 106, in run
worker-ingestion_1      |     raise exc
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 81, in run
worker-ingestion_1      |     result = self.execute(node_args)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/workers/mercator.py", line 57, in execute
worker-ingestion_1      |     return self.run_mercator(arguments, cache_path)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/workers/mercator.py", line 109, in run_mercator
worker-ingestion_1      |     timeout=timeout)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/workers/mercator.py", line 123, in run_gofedlib
worker-ingestion_1      |     result = json.loads(data[0])
worker-ingestion_1      | IndexError: string index out of range
```

**Comment by msrb** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/705
