### ISSUE TITLE
[f8a] firehose-fetcher: ValueError: invalid literal for int() with base 16: b'

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#4143]
From logs:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/urllib3/response.py", line 539, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/usr/lib/python3.4/site-packages/urllib3/response.py", line 594, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3.4/site-packages/urllib3/response.py", line 543, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 747, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.4/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3.4/site-packages/urllib3/response.py", line 622, in read_chunked
    self._original_response.close()
  File "/usr/lib64/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.4/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cli", line 9, in <module>
    load_entry_point('fabric8-analytics-firehose-fetcher==0.1', 'console_scripts', 'cli')()
  File "/usr/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/fetcher_cli.py", line 16, in cli
    fetcher.run()
  File "/usr/lib/python3.4/site-packages/f8a_firehose_fetcher/firehose_fetcher.py", line 97, in run
    for event in client.events():
  File "/usr/lib/python3.4/site-packages/sseclient/__init__.py", line 58, in events
    for chunk in self._read():
  File "/usr/lib/python3.4/site-packages/sseclient/__init__.py", line 48, in _read
    for chunk in self._event_source:
```

**Comment by humaton** [comment]
This seems to be caused by the firehose stream instability. I have tested 3 different client implementations and they all crash after approximately 1 minute.

**Comment by humaton** [comment]
After the investigation into this issue, we decided to create new tasks to create our own release monitoring tool.
