### ISSUE TITLE
Pipeline: Maximum threads for service reached when downloading Maven artefacts

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4278]
##### Issue Overview

Error `Maximum threads for service reached` when Maven downloads dependencies from Maven Central (intermittent error)

##### Expected Behaviour

Maven downloads all direct and transitive dependencies successfully

##### Current Behaviour

Pipeline fails with following error (whole log [here](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/2005/05-02-jenkins-log.html))
```
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: http://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-annotations/3.3/maven-plugin-annotations-3.3.pom. Return code is: 503 , ReasonPhrase:Maximum threads for service reached.
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1021)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 47 more
```

##### Steps To Reproduce

1. create new Vert.x project
2. watch the pipeline

##### Additional Information

Related to #3796 ... it's not happenig that ofter after the change of Maven repositor URL to the official one

**Comment by hrishin** [comment]
@ppitonak is it still happening after updating maven central URL?

**Comment by ppitonak** [comment]
No, I probably haven't seen this bug since reporting it.

**Comment by hrishin** [comment]
Thanks @ppitonak for confirming it. For the time being I'm closing it. If you observe this issue please free to open it again with higher priority.
