### ISSUE TITLE
Che: 2 workspaces created instead of one

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4416]
The E2E tests started to fail while performing the following scenario:
1. Create space and application
2. Create new workspace
3. Run Che
4. Close Che
5. Assert number of workspaces is 1 fails, because there are 2 workspaces

This could be caused by some test programming issue, but we haven't changed the code for quite a long time. When @rhopp  checked the workspaces, they have both been created 3 seconds apart. However, what is interesting, it seems that only 1 workspace has been created by che-starter. 

I've also found several errors regarding Gateway timeout in browser logs. 
```
[18:09:27.510] SEVERE https://openshift.io/api/codebases/8eeb84a4-6cb1-40ae-8018-7f34e5024c2e/workspaces - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
[18:09:27.536] SEVERE https://openshift.io/_assets/lib/main.32948e14bcec7803146c.bundle.js 0:1540229 HttpErrorResponse
[18:09:28.030] SEVERE https://openshift.io/api/codebases/8eeb84a4-6cb1-40ae-8018-7f34e5024c2e/create - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
[18:09:28.048] SEVERE https://openshift.io/_assets/lib/main.32948e14bcec7803146c.bundle.js 0:1540229 HttpErrorResponse
[18:09:41.432] WARNING https://che.openshift.io/_app/keycloak/RhCheKeycloak.js 401 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
[18:09:41.770] WARNING https://che.openshift.io/_app/keycloak/RhCheKeycloak.js 401 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
[18:09:43.159] SEVERE https://che.openshift.io/_app/IDE.css - Failed to load resource: the server responded with a status of 404 ()
```
The E2E tests started to encounter this issue about a day ago.

**Comment by ibuziuk** [comment]
>  it seems that only 1 workspace has been created by che-starter.
Could you please provide more info about the tests & details that you have figured out during investigation - workspace ids, logs from kibana would be really useful here.

**Comment by ljelinkova** [comment]
@garagatyi @ibuziuk  I am afraid I do not have more details about this issue. The issue appeared approximately 10 times but was not reproducible. I have not seen this issue since last Friday. The only clue we have is that it was probably connected to _Gateway Time-out_ error that was encountered on multiple occasions during the time the issue existed. 

https://github.com/openshiftio/openshift.io/issues/4415

I know it is really hard to find the cause but the issue of randomly creating 2 workspaces is so weird that if you could write any suggestion about where it might have happened (at least between which components) I would appreciate that.

**Comment by rhopp** [comment]
I've just reproduced this issue (running reduced e2e tests locally). The common denominator is this:
```
SEVERE https://openshift.io/api/codebases/d693e8f8-aa2f-4e86-b7f6-be3e37c0ab2a/create - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
```
@ljelinkova Did some more investigation and localized possibly suspicious code, which could cause this request to be called once again and thus creating two workspaces. (She will comment in a minute with her findings)

**Comment by ljelinkova** [comment]
I've noticed that the createWorkspace  is called with retry in case any error occurs. This could have caused that 2 workspaces were created. 

https://github.com/fabric8-ui/fabric8-ui/blob/f26f5a98e17acca51036df2aa4f122bb466afc24/src/app/space/create/codebases/services/workspaces.service.ts#L43

```
 createWorkspace(codebaseId: string): Observable<WorkspaceLinks> {
    const url: string = `${this.workspacesUrl}/${codebaseId}/create`;
    return this.http
      .post<WorkspaceLinks>(url, null, { headers: this.headers }).pipe(
      catchError((error: HttpErrorResponse): Observable<WorkspaceLinks> => this.handleError(error)),
      retry(8)); // che-starter timeout is 3 min -- 30 sec default request timeout is not enough
}
```

@joshuawilson What is the reason for that retry? Is creating 2 workspaces the right approach?

**Comment by joshuawilson** [comment]
The Che pod/environment may not be started. It has to be running to allow/take the `createWorkspace` and if not then it returns an http error. The retry will continue to send until it gets no error.

**Comment by ljelinkova** [comment]
@joshuawilson Ok, but 
1. do you think this issue is caused by the retry in createWorkspace?
2. do you think it is OK that 2 workspaces have been created instead of one?
3. if not, how would you prevent that?

**Comment by joshuawilson** [comment]
We need to ask some Che people. @ibuziuk @l0rd

**Comment by l0rd** [comment]
1. I think that it was a workaround to be able to wait for more than 30s even if the router returned a timeout error.
2. It's not ok. If I remember correctly che-starter should handle that (if a second request is received, it should ignore it). @ibuziuk should be able to provide a better answer.

**Comment by joshuawilson** [comment]
The UI makes the call and if it gets an error it calls again after 30 sec. Are you sure no error is sent back?

**Comment by rhopp** [comment]
@joshuawilson It seems, that the error is sent back (or at least logged by WIT) after more, than 30 seconds.
In the instance from my previous comment:
* 14:39:28.079 - WIT logs first request to create workspace (POST `/api/codebases/d693e8f8-aa2f-4e86-b7f6-be3e37c0ab2a/create`)
* 14:39:58.196 - WIT logs second request to create workspace
* 14:40:10.251 - WIT logs the error from the first request (I don't know if it propagates that error further to UI or not - My go-fu and angular-fu is too weak for that)

I've just analyzed another instance of the same behaviour. the 504 happened again in communication between che-starter and che-server, but this time on another place:
<details>
<summary>Stacktrace</summary>
```
org.springframework.web.client.HttpServerErrorException: 504 Gateway Time-out
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:531)
	at io.fabric8.che.starter.client.WorkspaceClient.createWorkspace(WorkspaceClient.java:177)
	at io.fabric8.che.starter.client.WorkspaceClient$$FastClassBySpringCGLIB$$9ee2512d.invoke(\u003cgenerated\u003e)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652)
	at io.fabric8.che.starter.client.WorkspaceClient$$EnhancerBySpringCGLIB$$b1b53441.createWorkspace(\u003cgenerated\u003e)
	at io.fabric8.che.starter.controller.WorkspaceController.createWorkspaceFromParams(WorkspaceController.java:171)
	at io.fabric8.che.starter.controller.WorkspaceController.createWorkspace(WorkspaceController.java:151)
	at io.fabric8.che.starter.controller.WorkspaceController.create(WorkspaceController.java:97)
	at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at io.fabric8.che.starter.mdc.filter.RequestFilter.doFilter(RequestFilter.java:56)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

Here's link to kibana logs for this instance: https://logs.dsaas.openshift.com/goto/e44ae55055c9b02a39fea825f04aa004

**Comment by joshuawilson** [comment]
I can change the timing on the retry easy enough but I would like confirmation what is being done on the backend.

**Comment by ibuziuk** [comment]
@joshuawilson I believe `retry`[1][2] calls should be rem completely since those have been added back to the time  

[1] https://github.com/fabric8-ui/fabric8-ui/blob/f26f5a98e17acca51036df2aa4f122bb466afc24/src/app/space/create/codebases/services/workspaces.service.ts#L48
[2] https://github.com/fabric8-ui/fabric8-ui/blob/f26f5a98e17acca51036df2aa4f122bb466afc24/src/app/space/create/codebases/services/workspaces.service.ts#L86

**Comment by ibuziuk** [comment]
PR has been sent - https://github.com/fabric8-ui/fabric8-ui/pull/3394
Once merged this issue could be closed. @ljelinkova created a separate HK issue for analyzing root causes of 504 on the infrastructure level

**Comment by joshuawilson** [comment]
Thanks for the PR.
Merged to master, not prod yet. Let's see what it does to the prod-preview e2e tests.

**Comment by ibuziuk** [comment]
@joshuawilson che e2e tests [1] are passing on prod-preview (jenkins are still failing though). Could with proceed with rolling out the fix to prod ?

[1] https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released

**Comment by joshuawilson** [comment]
Yes, I'll push it prod.

**Comment by ibuziuk** [comment]
@joshuawilson thanks. 
@rhopp @ljelinkova once merged could you please verify & close ?

**Comment by joshuawilson** [comment]
I just merged it to prod. The PR that ran passes on both e2e tests.

**Comment by ibuziuk** [comment]
@ljelinkova could we close this issue now ?

**Comment by ljelinkova** [comment]
@ibuziuk We had trouble running e2e tests since yesterday (unrelated to che) so let's wait till tomorrow and see how che is doing.

**Comment by ibuziuk** [comment]
@ljelinkova hmm.. e2e seems to be stable on prod:

- https://ci.centos.org/job/devtools-saas-openshiftio-e2e-smoketest-released/
- https://ci.centos.org/job/devtools-saas-openshiftio-e2e-smoketest-released/

If there are some concerns sure we could still have it open, but otherwise I believe we should close

**Comment by ljelinkova** [comment]
Those jobs run on prod-preview, not production. These are production jobs:

https://ci.centos.org/view/Devtools/search/?q=devtools-test-e2e-openshift.io-smoketest-us-east

As I said, let's wait until production jobs and stable and run several times (since this issue was intermittent).

**Comment by ljelinkova** [comment]
I've not seen this issue in the last e2e test runs on production so I am closing it now.
