### ISSUE TITLE
Jenkins job was not created

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4436]
##### Issue Overview
The e2e tests failed during the pipeline build. The Jenkins WAS unidled but there was no job created. 
The OSIO part:

![OSIO screenshot](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/869/05-02-pipeline-failed.png)

Jenkins when accessed directly

![Jenkins screenshot](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/869/05-04-jenkins-direct-log.png)

##### Steps To Reproduce
The issue happened intermittently (twice in 2 days, both on cluster 2) 
##### Additional Information
This is log from oc
```
Oct 15, 2018 2:17:08 PM io.fabric8.jenkins.openshiftsync.ConfigMapWatcher onInitialConfigMaps
SEVERE: Failed to update job
java.io.IOException: Failed to persist config.xml
	at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:292)
	at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3812)
	at io.fabric8.jenkins.openshiftsync.ConfigMapWatcher$2.call(ConfigMapWatcher.java:256)
	at io.fabric8.jenkins.openshiftsync.ConfigMapWatcher$2.call(ConfigMapWatcher.java:180)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at io.fabric8.jenkins.openshiftsync.ConfigMapWatcher.upsertJob(ConfigMapWatcher.java:180)
	at io.fabric8.jenkins.openshiftsync.ConfigMapWatcher.onInitialConfigMaps(ConfigMapWatcher.java:146)
	at io.fabric8.jenkins.openshiftsync.ConfigMapWatcher.access$200(ConfigMapWatcher.java:81)
	at io.fabric8.jenkins.openshiftsync.ConfigMapWatcher$1.doRun(ConfigMapWatcher.java:104)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.transform.TransformerException: java.io.FileNotFoundException: /var/lib/jenkins/jobs/osiotestmachine/config.xml (No such file or directory)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getOutputHandler(TransformerImpl.java:513)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:328)
	at jenkins.util.xml.XMLUtils._transform(XMLUtils.java:212)
	at jenkins.util.xml.XMLUtils.safeTransform(XMLUtils.java:84)
	at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:272)
	... 17 more
Caused by: java.io.FileNotFoundException: /var/lib/jenkins/jobs/osiotestmachine/config.xml (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getOutputHandler(TransformerImpl.java:486)
	... 21 more

Oct 15, 2018 2:19:35 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
INFO: OpenShift OAuth: provider: OpenShiftProviderInfo: issuer: https://api.starter-us-east-2.openshift.com auth ep: https://api.starter-us-east-2.openshift.com/oauth/authorize token ep: https://api.starter-us-east-2.openshift.com/oauth/token
Oct 15, 2018 2:19:35 PM org.openshift.jenkins.plugin
```

You can see the whole log and more information here
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/869/oc-jenkins-logs.txt

**Comment by mvulavak** [comment]
@ljelinkova Should this issue be assigned to service delivery team?I think it will be helpful if we assign team so that there is visibility around who owns the issue.

**Comment by ljelinkova** [comment]
I've added team/build-cd label.

**Comment by sthaha** [comment]
@ljelinkova how frequently do you see this issue? does this happen on prod-preview? 
Could you please justify why this is a `P1` and e2e test blocker?

**Comment by ljelinkova** [comment]
It is hard to tell since some jobs do not un-idle Jenkins at all. However, when I saw that issue locally it seemed that the problem was not that the job was not created, but that the Jenkins restarted during the build. After it came up again, there was obviously no running job. I

I hoped that this will be resolved by

https://github.com/openshiftio/openshift.io/issues/4456

Can you confirm that the problem with restarting Jenkins should be fixed in production?

**Comment by sthaha** [comment]
> Can you confirm that the problem with restarting Jenkins should be fixed in production?


@ljelinkova no, waiting for @jfchevrette to merge https://github.com/openshiftio/saas-openshiftio/pull/1115

**Comment by sthaha** [comment]
@ljelinkova the new idler is deployed into production. Could you please run the tests and close the issue if you can't reproduce the problem?
