### ISSUE TITLE
Jenkins idles without waiting 45 mins

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#4456]
prod-preview, 2a

1. A build just finished. 
2. Started a new build by commit trigger
3. Jenkins was idled and back to spinning wheel page

**Comment by kishansagathiya** [comment]
Logs of Jenkins pod [build_failure.log](https://github.com/openshiftio/openshift.io/files/2491265/build_failure.log)

**Comment by kishansagathiya** [comment]
```
WARNING: Failed to load Owner[kishansagathiya/app-test-1/master/2:kishansagathiya/app-test-1/master #2]. Unregistering
java.io.IOException: kishansagathiya/app-test-1/master #2 did not yet start
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.get(WorkflowRun.java:940)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:65)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:57)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$ItemListenerImpl.onLoaded(FlowExecutionList.java:178)
	at jenkins.model.Jenkins.<init>(Jenkins.java:974)
	at hudson.model.Hudson.<init>(Hudson.java:86)
	at hudson.model.Hudson.<init>(Hudson.java:82)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
```

This one is also IOException, I wonder if the reason why this is happening has something to do with #4020

**Comment by kishansagathiya** [comment]
build logs
```
OpenShift Build ksagathi-preview/app-test-1-2 from https://github.com/kishansagathiya/app-test-1.git
06:50:10 Connecting to https://api.github.com using kishansagathiya/****** (cd-github)
Obtained Jenkinsfile from aed290f318cc537e9175573e9fb4a4bc09bf0edb
Running in Durability level: MAX_SURVIVABILITY
Loading library github.com/kishansagathiya/fabric8-pipeline-library@issue_4020
Attempting to resolve issue_4020 from remote references...
 > git --version # timeout=10
 > git ls-remote -h -t https://github.com/kishansagathiya/fabric8-pipeline-library.git # timeout=10
```

**Comment by kishansagathiya** [comment]
> jenkins was idled and back to spinning wheel page

Happened consecutively many times. Jenkins restart on every build.

**Comment by ljelinkova** [comment]
I've ran into this issue but for me, Jenkins restarts even DURING the build.

**Comment by sthaha** [comment]
@kishansagathiya I know the root cause and the fix will be deployed in the next idler deployment. The reason this happens is because dc condition was removed (as a solution to the high gluster load) from idler.

**Comment by ppitonak** [comment]
@sthaha since you closed this issue, can you link PR fixing it?

**Comment by piyush-garg** [comment]
I think PR https://github.com/fabric8-services/fabric8-jenkins-idler/pull/290 will resolve this issue and it is in prod-preview right now and will be moved to prod soon today. More details @sthaha can provide.
