### ISSUE TITLE
Jenkins build fails "Disk quota exceeded"

### ISSUE THREAD

**Issue by fabricepipart** [openshiftio/openshift.io#4504]
##### Issue Overview
When building my application on Jenkins, the pipeline fails with the following error:
org.codehaus.plexus.archiver.ArchiverException: Problem writing to output in xAR operation Disk quota exceeded

##### Expected Behaviour
The Docker build image should be built during that step.

##### Current Behaviour
`[INFO] --- fabric8-maven-plugin:3.5.40:build (default) @ frontend ---
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] io.fabric8.maven.core.config.Profile@48a5ef5c inheriting resources from default
[INFO] F8: Running generator wildfly-swarm
[INFO] F8: wildfly-swarm: Using Docker image registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift as base / builder
[INFO] Copying files to /home/jenkins/workspace/cepipart_teknichrono_master-CDR77KTDDOVUTCZDCTISNJG53AB7H3ZBGZWVZU2GSIDPMQ5ZIRSQ/target/docker/frontend/1.0.3/build/maven
[INFO] Building tar: /home/jenkins/workspace/cepipart_teknichrono_master-CDR77KTDDOVUTCZDCTISNJG53AB7H3ZBGZWVZU2GSIDPMQ5ZIRSQ/target/docker/frontend/1.0.3/tmp/docker-build.tar
[WARNING] When creating tar entry
org.codehaus.plexus.archiver.ArchiverException: Problem writing to output in xAR operation Disk quota exceeded
	at org.codehaus.plexus.archiver.util.Streams.copyFullyDontCloseOutput(Streams.java:122)
	at org.codehaus.plexus.archiver.tar.TarArchiver.tarFile(TarArchiver.java:318)
	at org.codehaus.plexus.archiver.tar.TarArchiver.execute(TarArchiver.java:171)
	at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:916)
	at io.fabric8.maven.docker.assembly.DockerAssemblyManager.createBuildTarBall(DockerAssemblyManager.java:272)
	at io.fabric8.maven.docker.assembly.DockerAssemblyManager.createDockerTarArchive(DockerAssemblyManager.java:155)
	at io.fabric8.maven.docker.service.ArchiveService.createArchive(ArchiveService.java:123)
	at io.fabric8.maven.docker.service.ArchiveService.createDockerBuildArchive(ArchiveService.java:75)
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.createBuildArchive(OpenshiftBuildService.java:138)
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.build(OpenshiftBuildService.java:93)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:275)
	at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:44)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.executeInternal(BuildMojo.java:236)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:223)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute(BuildMojo.java:207)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] F8: Build for null failed: entry 'maven/frontend-1.0.3-swarm.jar' closed at '15660032' before the '108111901' bytes specified in the header were written
[ERROR] F8: Failed to execute the build [null]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:34 min
[INFO] Finished at: 2018-10-30T12:07:17+00:00
sh: /home/jenkins/workspace/cepipart_teknichrono_master-CDR77KTDDOVUTCZDCTISNJG53AB7H3ZBGZWVZU2GSIDPMQ5ZIRSQ@tmp/durable-646d8bae/jenkins-result.txt.tmp: Disk quota exceeded
mv: cannot stat '/home/jenkins/workspace/cepipart_teknichrono_master-CDR77KTDDOVUTCZDCTISNJG53AB7H3ZBGZWVZU2GSIDPMQ5ZIRSQ@tmp/durable-646d8bae/jenkins-result.txt.tmp': No such file or directory
[INFO] Final Memory: 53M/104M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.40:build (default) on project frontend: Failed to execute the build: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.40:build (default) on project frontend: Failed to execute the build
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute the build
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:278)
	at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:44)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.executeInternal(BuildMojo.java:236)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:223)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute(BuildMojo.java:207)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133)
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.logBuildFailure(OpenshiftBuildService.java:619)
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.build(OpenshiftBuildService.java:123)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:275)
	... 26 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.`

##### Steps To Reproduce

1. Start the pipeline here : https://jenkins.openshift.io/job/fabricepipart/job/teknichrono/job/master/

##### Additional Information

I tried deleting the jenkins namesapace to flush the PV, but I dont have the rights:
`| => /Users/fabricepipart/Downloads/gofabric8-darwin-amd64 clean jenkins
WARNING this is destructive and will remove ALL of the jenkins jobs
for your tenant: fabrice-pipart running in namespace: fabrice-pipart-jenkins

Continue [y/N]: y
Cleaning jenkins for tenant: fabrice-pipart running in namespace: fabrice-pipart-jenkins
Waiting for a running pod in namespace fabrice-pipart-jenkins with labels map[provider:fabric8 app:jenkins]
Found newest pod: jenkins-16-qptjs
Found running jenkins pod jenkins-16-qptjs
Error from server: pods "jenkins-16-qptjs" is forbidden: User "fabrice.pipart@gmail.com" cannot create pods/exec in the namespace "fabrice-pipart-jenkins": User "fabrice.pipart@gmail.com" cannot create pods/exec in project "fabrice-pipart-jenkins"
Failed to run command oc exec -it jenkins-16-qptjs -n fabrice-pipart-jenkins -- bash -c rm -rf /var/lib/jenkins/jobs/* due to error exit status 1`
I tried in UI and with gofabric8

My repository can be found here:
https://github.com/fabricepipart/teknichrono/

  * log from the build
  * link to your repository (if public)

**Comment by chmouel** [comment]
@rohanKanojia f-m-p can probably handle more gracefully ?

@pbergene is there a way to clear these volume for @fabricepipart 

There is always the way to reset your tenant by going to `https://openshift.io/${USER}/_cleanup` but that would remove *everything*

**Comment by fabricepipart** [comment]
A complete reset could be ok. Can I restart everything afterwards by just re importing my github project ?

**Comment by hrishin** [comment]
@fabricepipart yes, you can.

**Comment by pbergene** [comment]
Would clearing that PV completely be a supported flow and would be correctly repopulated next run? If it comes down to that I can look into this.  We can handle a one off request now and then, but should strive to figure out what goes wrong here.  Lack of cleaning, or simply too large build artefacts?

**Comment by fabricepipart** [comment]
Unfortunately even after cleaning up and starting fresh, the build still fails. I don't get what is happening. During my build, fabric8 builds my war and then builds the docker image from it if I understand properly.

During the creation of the tar, I get an exception:
`org.codehaus.plexus.archiver.ArchiverException: Problem writing to output in xAR operation Disk quota exceeded`
https://jenkins.openshift.io/job/fabricepipart/job/teknichrono/job/master/2/console

Could someone advise what is the quota that is exceeded?

**Comment by chmouel** [comment]
@pbergene do we have any quota on IO thoughtput or disk size limitations on the gluster volume ?  This is an IO error coming back from the linux kernel/vfs which would come from the gluster underneath.
