### ISSUE TITLE
[che.openshift.io] Sometimes jdt.ls failed to initialize 

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#4507]
Steps to reproduce:
- create & start workspace via UD (user dashboard) based on `vertx` stack with `vertx-health-check-booster`
- Once workspace is started there are the error logs in the `dev-machine` console
- ERROR: open any java file and try to do content assist via `Cntrl - space` - Intellisense does not work and there is an NPE error message in dev machine logs.

**Comment by ibuziuk** [comment]
@fbricon do you happen to have some ideas about the root cause of those failures.

**Comment by scela** [comment]
I'm seeing similar issues with a fresh workspace from a centos-java workspace. Here's the exception when it starts:

`
2018-11-02 09:42:03,232[ool-13-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: Init...
2018-11-02 09:42:03,236[ool-13-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 0% Starting Java Language Server 
2018-11-02 09:42:03,312[rverInitializer]  [WARN ] [o.e.l.j.s.GenericEndpoint 171]       - Unsupported notification method: json/schemaAssociations
2018-11-02 09:42:03,365[rverInitializer]  [WARN ] [o.e.l.j.s.GenericEndpoint 171]       - Unsupported notification method: json/schemaAssociations
2018-11-02 09:42:03,421[rverInitializer]  [INFO ] [.a.l.LanguageServerInitializer 222]  - Initialized language server 'org.eclipse.che.plugin.java.languageserver'
2018-11-02 09:42:03,599[ool-13-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 30% Starting Java Language Server 
2018-11-02 09:42:04,746[ool-13-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 37% Starting Java Language Server 
2018-11-02 09:42:04,545[ool-13-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 37% Starting Java Language Server 
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5706)
	at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scan(BasicFileDetector.java:128)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
2018-11-02 09:42:05,039[ool-13-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 100% Starting Java Language Server 
Java Model Exception: Core Exception [code 0] Failed to scan /projects
2018-11-02 09:42:04,979[ool-13-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 100% Starting Java Language Server 
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:52)
2018-11-02 09:42:04,984[ool-13-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 75]      - Nov 2, 2018 9:42:04 AM Initialization failed 
Failed to scan /projects
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
2018-11-02 09:42:04,978[ool-13-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 100% Starting Java Language Server 
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5749)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:114)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:221)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:736)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.access$1(ProjectsManager.java:128)
Caused by: java.nio.file.NoSuchFileException: /projects/console-java-simple/.git/index.lock
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5706)
Caused by: java.nio.file.NoSuchFileException: /projects/console-java-simple/.git/index.lock
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:221)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:41)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$2.run(ProjectsManager.java:122)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$2.run(ProjectsManager.java:122)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5749)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:736)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	... 15 more
`

**Comment by ibuziuk** [comment]
issue for tracking this problem in upstream - https://github.com/eclipse/che/issues/11856
