### ISSUE TITLE
FMP: Unable to build the image using the OpenShift build service

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4519]
##### Issue Overview

`Build Image` stage in pipeline fails (Vert.x HTTP booster)

##### Expected Behaviour

Pipeline builds the application successfully

##### Current Behaviour

Build fails

```
[INFO] --- fabric8-maven-plugin:3.5.41:build (fmp) @ e2e-1102-2237-4760 ---
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] io.fabric8.maven.core.config.Profile@7bfc36d5 inheriting resources from default
[INFO] F8: Running generator vertx
[INFO] F8: vertx: Using Docker image registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5 as base / builder
[INFO] Copying files to /home/jenkins/workspace/e_e2e-1102-2237-4760_master-2AJJBAGREIFLMGJAUDDZ2ALZ3G75GJGJMYKGXVQXN2ZMAPXQCQ2Q/target/docker/e2e-1102-2237-4760/1.0.1/build/maven
[INFO] Building tar: /home/jenkins/workspace/e_e2e-1102-2237-4760_master-2AJJBAGREIFLMGJAUDDZ2ALZ3G75GJGJMYKGXVQXN2ZMAPXQCQ2Q/target/docker/e2e-1102-2237-4760/1.0.1/tmp/docker-build.tar
[INFO] F8: [e2e-1102-2237-4760:1.0.1] "vertx": Created docker source tar /home/jenkins/workspace/e_e2e-1102-2237-4760_master-2AJJBAGREIFLMGJAUDDZ2ALZ3G75GJGJMYKGXVQXN2ZMAPXQCQ2Q/target/docker/e2e-1102-2237-4760/1.0.1/tmp/docker-build.tar
[INFO] F8: Creating BuildServiceConfig e2e-1102-2237-4760-s2i for Source build
[INFO] F8: Creating ImageStream e2e-1102-2237-4760
[INFO] io.fabric8.maven.core.config.Profile@47f5ab58 inheriting resources from default
[INFO] F8: Starting Build e2e-1102-2237-4760-s2i
[ERROR] F8: Build for e2e-1102-2237-4760-s2i failed: timeout
[ERROR] F8: e2e-1102-2237-4760-s2i-1		CannotCreateBuildPod	Failed creating build pod.
[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:45 min
[INFO] Finished at: 2018-11-02T22:56:32+00:00
[INFO] Final Memory: 51M/83M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.41:build (fmp) on project e2e-1102-2237-4760: Failed to execute the build: Unable to build the image using the OpenShift build service: CannotCreateBuildPod Failed creating build pod. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.41:build (fmp) on project e2e-1102-2237-4760: Failed to execute the build
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
```

##### Steps To Reproduce

1. create a new app using launcher
2. navigate to pipeline
3. open Jenkins log

##### Additional Information

Couple of Jenkins jobs failed with this error:

* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1325/ (Nov 2, 2018 10:35:00 PM) 
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1337/  (Nov 3, 2018 10:35:00 PM) 
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1348/  (Nov 4, 2018 8:35:00 PM) 
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/976/  (Nov 2, 2018 12:05:00 PM) 
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/992/ (Nov 5, 2018 4:05:01 AM)
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/982/ (Nov 3, 2018 9:05:00 AM) 
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/974/  (Nov 2, 2018 3:05:00 AM) 
* https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/984/ (Nov 3, 2018 7:05:00 PM)

**Comment by sthaha** [comment]
From the logs it seems that issue is that s2i build fails since Openshift wasn't able to bring up a build pod. 

```
[ERROR] F8: Build for e2e-1102-2237-4760-s2i failed: timeout
[ERROR] F8: e2e-1102-2237-4760-s2i-1		CannotCreateBuildPod	Failed creating build pod.
[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
```

@ppitonak providing the output of `oc get ev` should certainly help

**Comment by ppitonak** [comment]
@sthaha it's a self-service ;) Click any of the links in the issue description, open console log, scroll to the end of Jenkins log and click on link next to `Artifacts were uploaded to`. Review `oc-jenkins-logs-before-all.txt` and `oc-jenkins-logs.txt`

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1325/oc-jenkins-logs-before-all.txt
```
1h          1h           1         jenkins-1.156369eb34133156          ReplicationController                                 Warning   FailedCreate                  replication-controller                   Error creating: pods "jenkins-1-cxmzc" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
1h          1h           1         jenkins-1-n6jgt.156369fd400bc5a4    Pod                                                   Warning   FailedMount                   kubelet, ip-172-21-49-82.ec2.internal    Unable to mount volumes for pod "jenkins-1-n6jgt_osio-ci-e2e-002-jenkins(1f319494-dee1-11e8-910c-125c769592ce)": timeout expired waiting for volumes to attach or mount for pod "osio-ci-e2e-002-jenkins"/"jenkins-1-n6jgt". list of unmounted volumes=[jenkins-home jenkins-config jenkins-token-jv2fp]. list of unattached volumes=[jenkins-home jenkins-config jenkins-token-jv2fp]
1h          1h           1         jenkins-1-tn5tw.15636a06e64027d8    Pod                     spec.containers{jenkins}      Warning   Unhealthy                     kubelet, ip-172-21-48-60.ec2.internal    Readiness probe failed: Get http://10.130.31.27:8080/login: dial tcp 10.130.31.27:8080: getsockopt: connection refused
1h          1h           1         jenkins-1-hsctp.15636a116b960ef5    Pod                                                   Warning   FailedMount                   kubelet, ip-172-21-60-111.ec2.internal   Unable to mount volumes for pod "jenkins-1-hsctp_osio-ci-e2e-002-jenkins(52eb82ca-dee1-11e8-910c-125c769592ce)": timeout expired waiting for volumes to attach or mount for pod "osio-ci-e2e-002-jenkins"/"jenkins-1-hsctp". list of unmounted volumes=[jenkins-home jenkins-config jenkins-token-jv2fp]. list of unattached volumes=[jenkins-home jenkins-config jenkins-token-jv2fp]
1h          1h           15        jenkins-1-tn5tw.15636a0b09043d63    Pod                     spec.containers{jenkins}      Warning   Unhealthy                     kubelet, ip-172-21-48-60.ec2.internal    Readiness probe failed: HTTP probe failed with statuscode: 503
```

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1337/oc-jenkins-logs-before-all.txt
```
1h          1h           1         jenkins-1-wmfd5.1563b7dae4b40c3a                  Pod                                                              Warning   FailedMount                   kubelet, ip-172-21-60-132.ec2.internal   Unable to mount volumes for pod "jenkins-1-wmfd5_osio-ci-e2e-002-jenkins(7568806f-dfa8-11e8-87b4-12510d4247be)": timeout expired waiting for volumes to attach or mount for pod "osio-ci-e2e-002-jenkins"/"jenkins-1-wmfd5". list of unmounted volumes=[jenkins-home]. list of unattached volumes=[jenkins-home jenkins-config jenkins-token-jv2fp]
1h          1h           1         jenkins-slave-lx4gw-krj2g.1563b83523690d74        Pod                     spec.containers{maven}                   Warning   Failed                        kubelet, ip-172-21-48-127.ec2.internal   Failed to pull image "openshift/jenkins-slave-maven-centos7:v4.0": rpc error: code = Canceled desc = context canceled
1h          1h           1         jenkins-slave-lx4gw-krj2g.1563b83523698706        Pod                     spec.containers{maven}                   Warning   Failed                        kubelet, ip-172-21-48-127.ec2.internal   Error: ErrImagePull
1h          1h           1         jenkins-slave-lx4gw-krj2g.1563b84579a3837e        Pod                     spec.containers{jnlp}                    Warning   Failed                        kubelet, ip-172-21-48-127.ec2.internal   Error: ErrImagePull
1h          1h           1         jenkins-slave-lx4gw-krj2g.1563b84579a3227f        Pod                     spec.containers{jnlp}                    Warning   Failed                        kubelet, ip-172-21-48-127.ec2.internal   Failed to pull image "openshift/jenkins-slave-base-centos7:v4.0": rpc error: code = Canceled desc = context canceled
1h          1h           1         jenkins-1-2lfcc.1563b8baadf43e8a                  Pod                     spec.containers{jenkins}                 Warning   Unhealthy                     kubelet, ip-172-21-48-60.ec2.internal    Readiness probe failed: Get http://10.130.31.43:8080/login: dial tcp 10.130.31.43:8080: getsockopt: connection refused
1h          1h           16        jenkins-1-2lfcc.1563b8bec54d704e                  Pod                     spec.containers{jenkins}                 Warning   Unhealthy                     kubelet, ip-172-21-48-60.ec2.internal    Readiness probe failed: HTTP probe failed with statuscode: 503
```

Failure to mount a volume is reported in https://github.com/openshiftio/openshift.io/issues/4451. Could it be related to this issue? I don't think so because this run has no issues with mount and it failed with the same error
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/982

**Comment by piyush-garg** [comment]
@ppitonak This is resource quota. No enough space to create a new build pod.

**Comment by ppitonak** [comment]
@piyush-garg it happened after account reset

**Comment by ppitonak** [comment]
Another failed job https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/1006/console, the same symptoms... there are two `jenkins-slave-*` pods. @piyush-garg @sthaha you should probably investigate why two pods are created, this is probably the root cause.

**Comment by piyush-garg** [comment]
@ppitonak This has already been fixed with https://github.com/openshiftio/saas-openshiftio/pull/1128 today. Closing this.
