### ISSUE TITLE
On prod-preview, after successful build of Node.js booster, analytics report fails

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4603]
##### Issue Overview
On prod-preview, after successful build of Node.js booster, analytics report fails

##### Expected Behaviour
Expected behavior is that the analytics report will be generated on both production and prod-preview.

##### Current Behaviour
The report is generated on production and fails on prod-preview.

##### Steps To Reproduce

1. Clone: https://github.com/ldimaggi/nodejs-rest-http-crud
2. Import into OpenShift.io
3. Replace Jenkins file with: https://github.com/fabric8io/fabric8-jenkinsfile-library/blob/master/node/Release/Jenkinsfile
4. Observe Jenkins build logs for analytics report errors

##### Additional Information

See log fragments below:

Production:
```
Exiting "Trigger OpenShift Build" successfully; build "nodejs-rest-http-crud-3" has completed with status:  [Complete].
[Pipeline] echo
invoking bayesian analytics
[Pipeline] retry
[Pipeline] {
[Pipeline] bayesianAnalysis
No direct or transitive dependencies found.
Running Bayesian stack analysis...
Bayesian API URL is https://recommender.api.openshift.io/api/v1
Bayesian Ecosystem is node
[Pipeline] echo
Adding annotation 'fabric8.io/bayesian.analysisUrl: https://recommender.api.openshift.io/api/v1/stack-analyses/dd264f019dbb4476b50f8eb23ee73964' to Build november30test3-3
```

Prod-preview:
```
No direct or transitive dependencies found.
Running Bayesian stack analysis...
Bayesian API URL is https://recommender.api.prod-preview.openshift.io/api/v1
Bayesian Ecosystem is node
com.redhat.jenkins.plugins.bayesian.BayesianException: Bayesian error: 500
	at com.redhat.jenkins.plugins.bayesian.Bayesian.submitStackForAnalysis(Bayesian.java:136)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:129)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:1)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[Pipeline] echo
Bayesian analysis failed com.redhat.jenkins.plugins.bayesian.BayesianStepResponse@6f55cd
```

**Comment by yzainee** [comment]
not able to reproduce this issue. The stack analyses call doesnt fail.

**Comment by tisnik** [comment]
Is it possible to show us the reproducer please?

**Comment by invincibleJai** [comment]
it's working fine in both prod/prod-preview cc @yzainee
