### ISSUE TITLE
Launcher backend leaks file descriptors

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#4697]
##### Issue Overview
The launcher-backend (https://github.com/fabric8-launcher/launcher-backend) stores all the boosters locally and the `/reindex` API is used to update the local cache.

If multiple requests (more than ~10 requests) are sent to launcher-backend (doesn't need to be sent concurrently), it crashes with `Too many files open` exception. With every request sent to `/reindex` endpoint, the number of open files keeps on increasing.
Use the following command to see the number of open files 
```
ls -l /proc/{launcher_backend_process_id}/fd | wc -l

```

This causes two issues
1. **The `/booster-catalog` endpoint returns empty (or partial response)**. The empty response issue https://github.com/openshiftio/openshift.io/issues/4670 (which was a SEV-1) was also caused because there were too many open files. To reproduce this issue, see [Part A](https://github.com/openshiftio/openshift.io/issues/4697#empty-reponse-issue) of steps to reproduce

2. **Backend crashes with an exception**.
```
2019-01-09 18:19:25,903 INFO  [NativeGitBoosterCatalogPathProvider] (EE-ManagedExecutorService-default-Thread-6) Created /tmp/booster-catalog1252048683612888507
2019-01-09 18:19:25,904 INFO  [NativeGitBoosterCatalogPathProvider] (EE-ManagedExecutorService-default-Thread-6) Executing: git clone https://github.com/fabric8-launcher/launcher-booster-catalog.git --branch master --recursive --depth=1 --quiet -c advice.detachedHead=false /tmp/booster-catalog1252048683612888507
2019-01-09 18:19:25,904 SEVERE [AbstractBoosterCatalogService] (EE-ManagedExecutorService-default-Thread-6) Error while indexing: java.io.IOException: Cannot run program "git": error=24, Too many open files
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at io.fabric8.launcher.booster.catalog.spi.NativeGitBoosterCatalogPathProvider.cloneRepository(NativeGitBoosterCatalogPathProvider.kt:63)
	at io.fabric8.launcher.booster.catalog.spi.NativeGitBoosterCatalogPathProvider.createCatalogPath(NativeGitBoosterCatalogPathProvider.kt:35)
	at io.fabric8.launcher.booster.catalog.AbstractBoosterCatalogService.doIndex(AbstractBoosterCatalogService.kt:214)
	at io.fabric8.launcher.booster.catalog.AbstractBoosterCatalogService.access$doIndex(AbstractBoosterCatalogService.kt:43)
	at io.fabric8.launcher.booster.catalog.AbstractBoosterCatalogService$index$1.get(AbstractBoosterCatalogService.kt:110)
	at io.fabric8.launcher.booster.catalog.AbstractBoosterCatalogService$index$1.get(AbstractBoosterCatalogService.kt:43)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)
Caused by: java.io.IOException: error=24, Too many open files
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 16 more


```
The only way to resolve this is to kill the process and start a new one. To reproduce this, see [Part B](https://github.com/openshiftio/openshift.io/issues/4697#server-crash-issue) of the steps to reproduce section

##### Expected Behaviour
Launcher-backend shouldn't crash with `Too many files open` exception. It should gracefully close all the open files.

##### Current Behaviour
Launcher-backend doesn't close the file descriptors and crashes.

##### Steps To Reproduce 

 - ## [The empty/partial response issue](#empty-reponse-issue)
    Start launcher backend with
    ```
    LAUNCHER_BACKEND_CATALOG_REINDEX_TOKEN="abc" java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 web/target/launcher-backend-thorntail.jar
    ```
    and run https://gist.github.com/jarifibrahim/ebb1b9e6e8e2d9a3eb4f2a27d7e4c940
    NOTE - This issue isn't always reproducible. You might have to try multiple times to reproduce the issue

 - ## [Server Crash](#server-crash-issue)
    Start launcher backend with
    ```
    LAUNCHER_BACKEND_CATALOG_REINDEX_TOKEN="abc" java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 web/target/launcher-backend-thorntail.jar
    ```
    and run https://gist.github.com/jarifibrahim/76def0939fb82b01897df2e3355f6f46

**Comment by sbose78** [comment]
Interesting, the fix would need to somewhere in the dependency of https://github.com/fabric8-launcher/launcher-backend/blob/master/core/core-impl/src/main/java/io/fabric8/launcher/core/impl/catalog/RhoarBoosterCatalogFactory.java#L104

**Comment by gastaldi** [comment]
Nice catch, can we have this issue moved to (or referenced in another issue in) https://github.com/fabric8-launcher/launcher-backend/ please?

**Comment by gastaldi** [comment]
It seems that it is only part of the solution, maybe there is somewhere in the launcher-booster-catalog-service code where file handles are not closed, @quintesse any clue?

**Comment by quintesse** [comment]
Not immediately, I can take a look next week.

**Comment by gastaldi** [comment]
This issue was moved to fabric8-launcher/launcher-backend#617
