### ISSUE TITLE
Can't initialize TypeScript language server

### ISSUE THREAD

**Issue by dv1x3r** [openshiftio/openshift.io#4703]
##### Issue Overview

I use the standard Node.JS stack with 'TypeScript Language Server' installer enabled.
When I open .ts files I get the following error message in dev console:

```
2019/01/11 15:04:41 Start new terminal.
	at org.eclipse.che.api.languageserver.LanguageServerInitializer.initializeServerInstance(LanguageServerInitializer.java:213)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.io.OutputStream.write(OutputStream.java:116)
	at org.eclipse.che.api.languageserver.LanguageServerInitializer.lambda$null$0(LanguageServerInitializer.java:127)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
2019-01-11 15:04:43,683[rverInitializer]  [ERROR] [.a.l.LanguageServerInitializer 231]  - Can't initialize language server for 'org.eclipse.che.plugin.web.typescript'
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	... 19 common frames omitted
	... 22 common frames omitted
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
Caused by: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at org.eclipse.che.api.languageserver.LanguageServerInitializer.lambda$initialize$1(LanguageServerInitializer.java:131)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at com.sun.proxy.$Proxy93.initialize(Unknown Source)
2019/01/11 15:05:15 Error occurs on sending ping message to websocket. websocket: close sent
2019/01/11 15:05:15 Failed to send websocket message: , due to occurred error websocket: close sent
```

##### Expected Behaviour

Add TypeScript Intellisense support

##### Current Behaviour

TypeScript Intellisense is not working

##### Steps To Reproduce

1. Create a workspace at che.openshift.io
2. Select 'CentOS nodejs' stack
3. Configure workspace -> Installers -> Enable 'TypeScript language server'
4. Reboot workspace
5. Create an empty Node.JS project
6. Create and open .ts file

**Comment by ljelinkova** [comment]
@ibuziuk Could you have a look?

**Comment by GeorgeActon** [comment]
@ljelinkova Can we get this labeled correctly. Sounds like a bug if so would also need a severity and a prioirity

**Comment by ibuziuk** [comment]
should be fixed in Che 7. Closing
