### ISSUE TITLE
Builds for Spring Boot quickstart application not going through.

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#4745]
##### Issue Overview

Builds for Spring Boot quickstart application not going through. While the build failed in the first attempt, despite restarting the pipelines twice (this was after resetting my environment before starting), in the second attempt (again after resetting my environment) the build has started but I see no pipelines since the last 2 hours.

##### Expected Behaviour
Pipelines build as expected.
##### Current Behaviour
While the build failed in the first attempt, despite restarting the pipelines twice (this was after resetting my environment before starting), in the second attempt (again after resetting my environment) the build has started but I see no pipelines since the last 2 hours.
##### Steps To Reproduce

1. Run through create Sprinboot app wizard. (mission: externalized configuration)
2. Go to Create> Pipelines

##### Additional Information

![screenshot from 2019-01-31 14-10-45](https://user-images.githubusercontent.com/16647625/52052974-129e9300-257e-11e9-9fd0-899f10772bb3.png)
![screenshot from 2019-01-31 14-10-40](https://user-images.githubusercontent.com/16647625/52052977-129e9300-257e-11e9-87f7-940ddb9169e5.png)
![screenshot from 2019-01-31 14-10-35](https://user-images.githubusercontent.com/16647625/52052978-13372980-257e-11e9-9bbc-1ceb892d51e8.png)

Here is the error I got: 
```
error: build error: unable to get docker-registry.default.svc:5000/openshift/python@sha256:
Pulling image "docker-registry.default.svc:5000/openshift/python@sha256:9f044e4c0ee877dd9b2e0108d8b33f034977f87a746cfccb7defc9a588144b2d" ...
pulling image error : Get https://docker-registry.default.svc:5000/v2/:  dial tcp 172.30.98.11:5000: getsockopt: no route to host
error: build error: unable to get docker-registry.default.svc:5000/openshift/python@sha256:9f044e4c0ee877dd9b2e0108d8b33f034977f87a746cfccb7defc9a588144b2d
```
Here are the snipped logs for the same:

```
[INFO] F8: ==================================================================
[INFO] F8: Starting S2I Java Build .....
[INFO] F8: S2I binary build from fabric8-maven-plugin detected
[INFO] F8: Copying binaries from /tmp/src/maven to /deployments ...
[INFO] F8: ... done
[INFO] F8: 
[INFO] F8: Pushing image docker-registry.default.svc:5000/pchandra-jenkins/booster-mission-runtime:1.0.2 ...
[INFO] Current reconnect backoff is 4000 milliseconds (T2)
[INFO] Current reconnect backoff is 8000 milliseconds (T3)
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] Current reconnect backoff is 16000 milliseconds (T4)
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] F8: Warning: Push failed, retrying in 5s ...
[INFO] F8: Registry server Address: 
[INFO] F8: Registry server User Name: serviceaccount
[INFO] F8: Registry server Email: serviceaccount@example.org
[INFO] F8: Registry server Password: <<non-empty>>
[INFO] F8: error: build error: Failed to push image: After retrying 6 times, Push image still failed due to error: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp 172.30.98.11:5000: getsockopt: no route to host
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[WARNING] Executor didn't terminate in time after shutdown in close(), killing it in: io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager@4a199271
[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:33 min
[INFO] Finished at: 2019-01-31T08:46:56+00:00
[INFO] Final Memory: 52M/91M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project booster-mission-runtime: Failed to execute the build: Unable to build the image using the OpenShift build service: OpenShift Build booster-mission-runtime-s2i-2: Failed: PushImageToRegistryFailed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project booster-mission-runtime: Failed to execute the build
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute the build
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:270)
	at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:44)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.executeInternal(BuildMojo.java:228)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:223)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute(BuildMojo.java:199)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: io.fabric8.maven.core.service.Fabric8ServiceException: Unable to build the image using the OpenShift build service
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.build(OpenshiftBuildService.java:121)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:267)
	... 26 more
Caused by: org.apache.maven.plugin.MojoExecutionException: OpenShift Build booster-mission-runtime-s2i-2: Failed: PushImageToRegistryFailed
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.waitForOpenShiftBuildToComplete(OpenshiftBuildService.java:404)
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.build(OpenshiftBuildService.java:114)
	... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE
```
In the second attempt here are the screenshots of the build stalled since 2 hours:
![screenshot from 2019-01-31 17-35-25](https://user-images.githubusercontent.com/16647625/52053199-b9832f00-257e-11e9-926d-0714707eb077.png)
![screenshot from 2019-01-31 17-20-39](https://user-images.githubusercontent.com/16647625/52053200-b9832f00-257e-11e9-9acd-c8a6c66e9642.png)
![screenshot from 2019-01-31 17-19-22](https://user-images.githubusercontent.com/16647625/52053201-ba1bc580-257e-11e9-86d5-21eab6e7e0a8.png)

**Comment by jarifibrahim** [comment]
```
error: build error: unable to get docker-registry.default.svc:5000/openshift/python@sha256:
Pulling image "docker-registry.default.svc:5000/openshift/python@sha256:9f044e4c0ee877dd9b2e0108d8b33f034977f87a746cfccb7defc9a588144b2d" ...
pulling image error : Get https://docker-registry.default.svc:5000/v2/:  dial tcp 172.30.98.11:5000: getsockopt: no route to host
error: build error: unable to get docker-registry.default.svc:5000/openshift/python@sha256:9f044e4c0ee877dd9b2e0108d8b33f034977f87a746cfccb7defc9a588144b2d
```
@pbergene any clue why the docker registry wasn't reachable?

**Comment by ppitonak** [comment]
I saw this bug in recent Jenkins test results.

**Comment by pbergene** [comment]
There have been some reports on cluster networking issues on east-2 - let's try to consolidate the reports and what we know.

**Comment by ppitonak** [comment]
Still happening https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1556/console
