### ISSUE TITLE
Import Wizard Fail: WF Swarm

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#518]
https://github.com/burrzinga/swarmgen1

jenkins job output

```
OpenShift Build burrzinga/swarmgen1-2 from https://github.com/burrzinga/swarmgen1.git
13:06:14 Connecting to https://api.github.com using burrzinga/****** (cd-github)
Obtained Jenkinsfile from 6b068a5326cbd4f9d52220392dfd742137cb7d63
Loading library github.com/fabric8io/fabric8-pipeline-library@master
 > git rev-parse --is-inside-work-tree # timeout=10
Setting origin to https://github.com/fabric8io/fabric8-pipeline-library.git
 > git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
Fetching origin...
Fetching upstream changes from origin
 > git --version # timeout=10
 > git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/*
 > git rev-parse master^{commit} # timeout=10
 > git rev-parse origin/master^{commit} # timeout=10
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git
 > git --version # timeout=10
 > git fetch --no-tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision 1a00f8c498d16437ae013c0ce3bfabab7ad960ad (master)
Commit message: "Merge pull request #287 from rupalibehera/settimeout"
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1a00f8c498d16437ae013c0ce3bfabab7ad960ad
 > git rev-list 1a00f8c498d16437ae013c0ce3bfabab7ad960ad # timeout=10
[Pipeline] echo
Loaded PipelineConfiguration PipelineConfiguration{jobNameToKindMap={}, ciBranchPatterns=[PR-.*], cdBranchPatterns=[master], cdGitHostAndOrganisationToBranchPatterns={}, disableITestsCD=false, disableITestsCI=false}
[Pipeline] echo
Loaded the useDockerSocket flag false
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
jenkins-slave-vpzdf-8b4gp is offline
Running on jenkins-slave-vpzdf-8b4gp in /home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ
[Pipeline] {
[Pipeline] checkout
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/burrzinga/swarmgen1.git
 > git init /home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ # timeout=10
Fetching upstream changes from https://github.com/burrzinga/swarmgen1.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials cd-github
 > git fetch --no-tags --progress https://github.com/burrzinga/swarmgen1.git +refs/heads/master:refs/remotes/origin/master
 > git config remote.origin.url https://github.com/burrzinga/swarmgen1.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config remote.origin.url https://github.com/burrzinga/swarmgen1.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/burrzinga/swarmgen1.git
using GIT_ASKPASS to set credentials cd-github
 > git fetch --no-tags --progress https://github.com/burrzinga/swarmgen1.git +refs/heads/master:refs/remotes/origin/master
Checking out Revision 6b068a5326cbd4f9d52220392dfd742137cb7d63 (master)
Commit message: "adding memory constraint"
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 6b068a5326cbd4f9d52220392dfd742137cb7d63
 > git rev-list 02cc7a4e4e22d22393dbdb7bf103df4ef6c46935 # timeout=10
[Pipeline] echo
NOTE: running pipelines for the first time will take longer as build and base docker images are pulled onto the node
[Pipeline] container
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build Release)
[Pipeline] sh
[burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ] Running shell script
Executing shell script inside container [maven] of pod [jenkins-slave-vpzdf-8b4gp]
Executing command: sh -c echo $$ > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-de7d9f50/pid'; jsc=durable-ef8d1361bc613fab26aa19cffcccf2e4; JENKINS_SERVER_COOKIE=$jsc '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-de7d9f50/script.sh' > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-de7d9f50/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-de7d9f50/jenkins-result.txt' 
[?1034hsh-4.2$ cd "/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCV 
EHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ"
sh-4.2$ sh -c echo $$ > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA 
767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-de7d9f50/pid'; jsc= 
durable-ef8d1361bc613fab26aa19cffcccf2e4; JENKINS_SERVER_COOKIE=$jsc '/home/jenk 
ins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U 
3WTAVWAF5VGAQ@tmp/durable-de7d9f50/script.sh' > '/home/jenkins/workspace/burrzin 
ga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/dur 
able-de7d9f50/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/burrzing 
a_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/dura 
ble-de7d9f50/jenkins-result.txt' 
sh-4.2$ exit
exit
+ git checkout -b burrzinga/swarmgen1/master-1.0.2
Switched to a new branch 'burrzinga/swarmgen1/master-1.0.2'
[Pipeline] sh
[burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ] Running shell script
Executing shell script inside container [maven] of pod [jenkins-slave-vpzdf-8b4gp]
Executing command: sh -c echo $$ > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-907409b5/pid'; jsc=durable-ef8d1361bc613fab26aa19cffcccf2e4; JENKINS_SERVER_COOKIE=$jsc '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-907409b5/script.sh' > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-907409b5/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-907409b5/jenkins-result.txt' 
[?1034hsh-4.2$ cd "/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCV 
EHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ"
sh-4.2$ sh -c echo $$ > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA 
767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-907409b5/pid'; jsc= 
durable-ef8d1361bc613fab26aa19cffcccf2e4; JENKINS_SERVER_COOKIE=$jsc '/home/jenk 
ins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U 
3WTAVWAF5VGAQ@tmp/durable-907409b5/script.sh' > '/home/jenkins/workspace/burrzin 
ga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/dur 
able-907409b5/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/burrzing 
a_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/dura 
ble-907409b5/jenkins-result.txt' 
+ mvn org.codehaus.mojo:versions-maven-plugin:2.2:set -U -DnewVersion=1.0.2
Cannot contact jenkins-slave-vpzdf-8b4gp: java.io.IOException: corrupted content in /home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-907409b5/pid: java.lang.NumberFormatException: For input string: ""
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building WildFly Swarm Example 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.2:set (default-cli) @ swarmgen1 ---
[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: /home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ
[INFO] Processing change of red.burr:swarmgen1:1.0.0-SNAPSHOT -> 1.0.2
[INFO] Processing red.burr:swarmgen1
[INFO]     Updating project red.burr:swarmgen1
[INFO]         from version 1.0.0-SNAPSHOT to 1.0.2
sh-4.2$ exit
exit
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.549 s
[INFO] Finished at: 2017-08-09T13:07:17+00:00
[INFO] Final Memory: 12M/491M
[INFO] ------------------------------------------------------------------------
[Pipeline] sh
[burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ] Running shell script
Executing shell script inside container [maven] of pod [jenkins-slave-vpzdf-8b4gp]
Executing command: sh -c echo $$ > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-7cb3f17c/pid'; jsc=durable-ef8d1361bc613fab26aa19cffcccf2e4; JENKINS_SERVER_COOKIE=$jsc '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-7cb3f17c/script.sh' > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-7cb3f17c/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-7cb3f17c/jenkins-result.txt' 
[?1034hsh-4.2$ cd "/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCV 
EHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ"
sh-4.2$ sh -c echo $$ > '/home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA 
767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-7cb3f17c/pid'; jsc= 
durable-ef8d1361bc613fab26aa19cffcccf2e4; JENKINS_SERVER_COOKIE=$jsc '/home/jenk 
ins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U 
3WTAVWAF5VGAQ@tmp/durable-7cb3f17c/script.sh' > '/home/jenkins/workspace/burrzin 
ga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/dur 
able-7cb3f17c/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/burrzing 
a_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/dura 
ble-7cb3f17c/jenkins-result.txt' 
+ mvn clean -e -U deploy -Dmaven.test.skip=false -P openshift
Cannot contact jenkins-slave-vpzdf-8b4gp: java.io.IOException: corrupted content in /home/jenkins/workspace/burrzinga_swarmgen1_master-CUDA767UZMH2QUQCVEHTS6PRO63EARBDF52AN3U3WTAVWAF5VGAQ@tmp/durable-7cb3f17c/pid: java.lang.NumberFormatException: For input string: ""
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building WildFly Swarm Example 1.0.2
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://central.maven.org/maven2/org/glassfish/javax.el-impl/3.0.1-b08-jbossorg-1/javax.el-impl-3.0.1-b08-jbossorg-1.pom
[WARNING] The POM for org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 is missing, no dependency information available
[INFO] Downloading: http://central.maven.org/maven2/org/glassfish/javax.el-impl/3.0.1-b08-jbossorg-1/javax.el-impl-3.0.1-b08-jbossorg-1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.218 s
[INFO] Finished at: 2017-08-09T13:07:22+00:00
sh-4.2$ exit
exit
[INFO] Final Memory: 17M/491M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "openshift" could not be activated because it does not exist.
[ERROR] Failed to execute goal on project swarmgen1: Could not resolve dependencies for project red.burr:swarmgen1:war:1.0.2: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project swarmgen1: Could not resolve dependencies for project red.burr:swarmgen1:war:1.0.2: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project red.burr:swarmgen1:war:1.0.2: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by jstrachan** [comment]
can you build that git repository normally without any magic profiles or custom repositories added to your pom? I wonder if you remove your local org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 dependency you can still build it locally?

am guessing this relates to either that dependency not being in maven central or your project or some special maven repo mirror is required to find it?

**Comment by burrsutter** [comment]
The problem is that it came straight from the WF Swarm Generator that way.

**Comment by qodfathr** [comment]
@burrsutter we have removed WF from the quickstart catalog for now. But I'm not sure how that would impact import. @slemeur , does the App Wizard import build the correct stack for Che if importing a WF Swarm project?

Is this simply not a supported scenario at this time? (Or is this maybe actually now working?)

**Comment by ldimaggi** [comment]
The import is now working for the wildfly-swarm health check booster - and it builds and deploys to stage and run.

But - I have not been able to get its Che workspace to open:

![screenshot from 2018-01-17 13-05-02](https://user-images.githubusercontent.com/642621/35058863-3b93e5d4-fb87-11e7-8d33-f6ef19a25ee3.png)

I'd suggest closing this issue until we get to a point where we want to officially support (and fully test) the RHOAR boosters on OSIO.

**Comment by qodfathr** [comment]
@slemeur would like you to see this closed, or would you like to keep it open and reference it from a Che/OSIO issue?

**Comment by bartoszmajsak** [comment]
This bug is related to old version of Wild Swarm boosters (affects latest productized version though). Latest ones based on Thorntail are working and these are currently available in OSIO Launcher Wizard. 

I think we can close it @slemeur as it is not relevant anymore.

**Comment by slemeur** [comment]
Agree. Closing
