### ISSUE TITLE
Bayesian recommender service inaccessible from pipelines

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#545]
I see an HTTP error 503 (service inaccessible)  while running a pipeline build - 
```
[Pipeline] bayesianAnalysis
Running Bayesian stack analysis...
Bayesian API URL is https://recommender.api.openshift.io/api/v1
com.redhat.jenkins.plugins.bayesian.BayesianException: Bayesian error: 503
	at com.redhat.jenkins.plugins.bayesian.Bayesian.submitStackForAnalysis(Bayesian.java:109)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:99)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:68)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

[Pipeline] error
[Pipeline] echo
Unable to run Bayesian analysis: hudson.AbortException: Bayesian analysis failed com.redhat.jenkins.plugins.bayesian.BayesianStepResponse@182ae13
```

The recommender.api.openshift.io is accessible from my local machine though.

**Comment by msrb** [comment]
It looks like it could be an issue in our jenkins plugin.

**Comment by samuzzal-choudhury** [comment]
This issue is not reproducible any more without doing any code/configuration changes in the Bayesian Jenkins plugin and in API server. My feeling is that there were communication anomalies. But, this needs verification.

**Comment by samuzzal-choudhury** [comment]
![image](https://user-images.githubusercontent.com/17740190/29205962-54f098c2-7e9d-11e7-8cd1-6aaee69fa53a.png)

**Comment by msrb** [comment]
I can confirm that the issue is not reproducible anymore.

**Comment by rawlingsj** [comment]
Agreed - shall we close this and reopen if we start seeing the 503's again?

**Comment by rawlingsj** [comment]
@burrsutter has just had a 503..

```
Running Bayesian stack analysis...
Bayesian API URL is https://recommender.api.openshift.io/api/v1
com.redhat.jenkins.plugins.bayesian.BayesianException: Bayesian error: 503
```

**Comment by rawlingsj** [comment]
Ok so the 503's still happen even when I wrap a retry around the recommender API call. 

So I added a couple of curl commands in the pipeline after we get a 503 and we get an interesting result:

First here's the reported 503 from the bayesian jenkins plugin:
```
Running Bayesian stack analysis...
Bayesian API URL is https://recommender.api.openshift.io/api/v1
com.redhat.jenkins.plugins.bayesian.BayesianException: Bayesian error: 503
```
Next curl the external URL which WORKS:
```
[Pipeline] sh
+ curl -v https://recommender.api.openshift.io/api/v1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to recommender.api.openshift.io port 443 (#0)
*   Trying 52.70.5.223...
* Connected to recommender.api.openshift.io (52.70.5.223) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
sh-4.2$ exit
exit
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.api.openshift.io,O=Red Hat Inc.,L=Raleigh,ST=North Carolina,C=US
* 	start date: Apr 05 00:00:00 2017 GMT
* 	expire date: Apr 10 12:00:00 2019 GMT
* 	common name: *.api.openshift.io
* 	issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET /api/v1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: recommender.api.openshift.io
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 11 Aug 2017 14:54:22 GMT
< Server: Apache
< Content-Length: 636
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Set-Cookie: 8a9ec3b54985b331ee7dba0edc8593fc=20785d450629c0c4628a3004cb47de48; path=/; HttpOnly; Secure
< Cache-control: private
< 
{ [data not shown]

100   636  100   636    0     0   1247      0 --:--:-- --:--:-- --:--:--  1247
* Connection #0 to host recommender.api.openshift.io left intact
{
    "paths": [
        "/api/v1",
        "/api/v1/component-analyses/<ecosystem>/<package>/<version>",
        "/api/v1/component-search/<package>",
        "/api/v1/schemas",
        "/api/v1/schemas/<collection>",
        "/api/v1/schemas/<collection>/<name>",
        "/api/v1/schemas/<collection>/<name>/<version>",
        "/api/v1/stack-analyses",
        "/api/v1/stack-analyses-v2",
        "/api/v1/stack-analyses-v2/<external_request_id>",
        "/api/v1/stack-analyses/<external_request_id>",
        "/api/v1/stack-analyses/by-origin/<origin>",
        "/api/v1/system/version",
        "/api/v1/user-feedback"
    ]
}
```
Now try the internal kubernetes service URL which in turn points at the external one above:
```
+ curl -v https://bayesian-link
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
sh-4.2$ exit
exit
* About to connect() to bayesian-link port 443 (#0)
*   Trying 52.70.151.80...
* Connected to bayesian-link (52.70.151.80) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Server certificate:
* 	subject: CN=*.09b5.dsaas.openshiftapps.com,OU=RHC Cloud Operations,O=Red Hat Inc.,L=Raleigh,ST=North Carolina,C=US
* 	start date: Feb 13 00:00:00 2017 GMT
* 	expire date: Feb 21 12:00:00 2018 GMT
* 	common name: *.09b5.dsaas.openshiftapps.com
* 	issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
* NSS error -12276 (SSL_ERROR_BAD_CERT_DOMAIN)
* Unable to communicate securely with peer: requested domain name does not match the server's certificate.

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
```

**Comment by maxandersen** [comment]
This looks very much like routing from inside and out don't honor SNI or one of the certs on its way is wrong. i.e. you should not be given a certificated with `*.09b5.dsaas.openshiftapps.com` when you are reaching out to  `https://recommender.api.openshift.io/api/v1`

**Comment by maxandersen** [comment]
for those wanting to try this without pipelines you can do the following:

```
oc login
oc project $ID-jenkins
oc get pods
<output will have a pod named jenkins-<something>
```
now run:

```
oc exec -it jenkins-<something> bash
```

now you are in env that excerts same behavior as @rawlingsj observed above.

**Comment by maxandersen** [comment]
note: It does not look like `https://recommender.api.openshift.io/api/v1` is what `https://bayesian-link` refer to.

When running without ssl check's I get this:

```
curl -vk https://bayesian-link
bash-4.2$ curl -vk https://bayesian-link
* About to connect() to bayesian-link port 443 (#0)
*   Trying 52.70.5.223...
* Connected to bayesian-link (52.70.5.223) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.09b5.dsaas.openshiftapps.com,OU=RHC Cloud Operations,O=Red Hat Inc.,L=Raleigh,ST=North Carolina,C=US
* 	start date: Feb 13 00:00:00 2017 GMT
* 	expire date: Feb 21 12:00:00 2018 GMT
* 	common name: *.09b5.dsaas.openshiftapps.com
* 	issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: bayesian-link
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 503 Service Unavailable
< Pragma: no-cache
< Cache-Control: private, max-age=0, no-cache, no-store
< Connection: close
< Content-Type: text/html
<
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<snip css stuff>
  </style>
  </head>
  <body>
    <div>
      <h1>Application is not available</h1>
      <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>

      <div class="alert alert-info">
        <p class="info">
          Possible reasons you are seeing this page:
        </p>
        <ul>
          <li>
            <strong>The host doesn't exist.</strong>
            Make sure the hostname was typed correctly and that a route matching this hostname exists.
          </li>
          <li>
            <strong>The host exists, but doesn't have a matching path.</strong>
            Check if the URL path was typed correctly and that the route was created using the desired path.
          </li>
          <li>
            <strong>Route and path matches, but all pods are down.</strong>
            Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
          </li>
        </ul>
      </div>
    </div>
  </body>
</html>
* Closing connection 0
```

versus

```
curl -vk https://recommender.api.openshift.io/api/v1
* About to connect() to recommender.api.openshift.io port 443 (#0)
*   Trying 52.70.151.80...
* Connected to recommender.api.openshift.io (52.70.151.80) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.api.openshift.io,O=Red Hat Inc.,L=Raleigh,ST=North Carolina,C=US
* 	start date: Apr 05 00:00:00 2017 GMT
* 	expire date: Apr 10 12:00:00 2019 GMT
* 	common name: *.api.openshift.io
* 	issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET /api/v1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: recommender.api.openshift.io
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 11 Aug 2017 20:30:23 GMT
< Server: Apache
< Content-Length: 636
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Set-Cookie: 8a9ec3b54985b331ee7dba0edc8593fc=20785d450629c0c4628a3004cb47de48; path=/; HttpOnly; Secure
< Cache-control: private
<
{
    "paths": [
        "/api/v1",
        "/api/v1/component-analyses/<ecosystem>/<package>/<version>",
        "/api/v1/component-search/<package>",
        "/api/v1/schemas",
        "/api/v1/schemas/<collection>",
        "/api/v1/schemas/<collection>/<name>",
        "/api/v1/schemas/<collection>/<name>/<version>",
        "/api/v1/stack-analyses",
        "/api/v1/stack-analyses-v2",
        "/api/v1/stack-analyses-v2/<external_request_id>",
        "/api/v1/stack-analyses/<external_request_id>",
        "/api/v1/stack-analyses/by-origin/<origin>",
        "/api/v1/system/version",
        "/api/v1/user-feedback"
    ]
}
* Connection #0 to host recommender.api.openshift.io left intact
```

**Comment by maxandersen** [comment]
btw. @rawlingsj  if the code are using https://recommender.api.openshift.io/api/v1 then that baysian-link fails on cert issue is a seperate issur, right ?

**Comment by maxandersen** [comment]
okey, with some help from @jfchevrette at https://chat.openshift.io/developers/pl/ccrh8y6bk7y8mfmmc1ht476i8a I'll conclude that `https://baysian-link` is not working is simply due to https/TLS not  being enabled on internal routed services in the cluster.

But then still weird why  `curl -v http://bayesian-link/api/v1` doesn't work either, I get an "Application is not available"

**Comment by samuzzal-choudhury** [comment]
However strange it might sound with all that explained here, I have been getting `stack reports` for every single build run since last evening :-)

**Comment by samuzzal-choudhury** [comment]
503 is back for me after a tenant update.

**Comment by invincibleJai** [comment]
Tested it now post updating tenant got 503 again now during OSIO build run
`Bayesian API URL is https://recommender.api.openshift.io/api/v1
com.redhat.jenkins.plugins.bayesian.BayesianException: Bayesian error: 503`

**Comment by kbsingh** [comment]
cross cluster, short urls will not work - you need the full real DNS name to be used. For the app itself unable to process the request, can we get the full html output of what is returned when you get the 503 error ? 

@samuzzal-choudhury you will need to check the app logs on the OSD to work through the issue ? it looks like the problem might be in the bayesian app itself, either unable to handle the concurrency required or it is itself failing internally.

**Comment by msrb** [comment]
I think the 503 in pipelines could be caused by trailing newline character in RECOMMENDER_API_TOKEN env. variable in Jenkins. It terminates headers section in a HTTP request and effectively cuts off Host header, causing the 503.

It looks like not all tokens have this trailing newline. My token is affected.

**Comment by msrb** [comment]
```
oc project <your-username>-jenkins
oc delete secret jenkins-recommender-api-token
```

And then click "update tenant" in UI. The problem should be fixed.

**Comment by GeorgeActon** [comment]
@msrb @samuzzal-choudhury Have we reached a conclusion on this?

**Comment by samuzzal-choudhury** [comment]
@kbsingh the core API service is working without any failure throughout as we have tested by invoking the recommender API endpoint immediately after we had encountered 503 during the build.

@rawlingsj's text on the openshiftio-saas channel conformed that behaviour https://chat.openshift.io/developers/pl/ohdf4ftzupda8b89ueqbmqt5or. During the occurrence of this error, API server did not print any supporting logs that could have indicated that it had something to do with this.

[This is the link](https://gist.github.com/burrsutter/4b27ce575c4f3ed9d874eb157a5ae1c0) to the build log with error 503 from Bayesian's Jenkins plugin.

**Comment by samuzzal-choudhury** [comment]
@GeorgeActon I don't see anything to be done from the fabric8 analytics application point of view because error 503 is not being thrown by the application server. Rather, it was on a position to handle requests even when Jenkins plugin reported error 503.

**Comment by samuzzal-choudhury** [comment]
Closing this issue as this issue does not occur any more. We will reopen this if required.
