### ISSUE TITLE
https://gist.github.com/burrsutter/4b27ce575c4f3ed9d874eb157a5ae1c0

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#549]
Noticed this in the Jenkins build with Vert.x Basic quickstart and Importing https://github.com/burrsutter/vertx-eventbus

```
Running Bayesian stack analysis...
Bayesian API URL is https://recommender.api.openshift.io/api/v1
com.redhat.jenkins.plugins.bayesian.BayesianException: Bayesian error: 503
	at com.redhat.jenkins.plugins.bayesian.Bayesian.submitStackForAnalysis(Bayesian.java:109)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:99)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:68)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

[Pipeline] error
[Pipeline] echo
Unable to run Bayesian analysis: hudson.AbortException: Bayesian analysis failed com.redhat.jenkins.plugins.bayesian.BayesianStepResponse@176da83
[Pipeline] echo
```

**Comment by aslakknutsen** [comment]
Duplicate https://github.com/openshiftio/openshift.io/issues/545
