### ISSUE TITLE
Intermittent issue - Creating a new Che workspace fails - "no route to host"

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#597]
Just started seeing this with Che 1.0.288:

2017-08-17 03:16:37,136[nio-8080-exec-3]  [ERROR] [c.r.c.k.s.KeycloakUserChecker 74]    - Exception while calling the user auth endpoint:
  | java.net.NoRouteToHostException: No route to host (Host unreachable)

```

Using embedded assembly...
--
  | WARN: parent dir is not writeable, CHE_LOCAL_CONF_DIR will be set to /data/conf
  | Using embedded che.properties... Copying template to /data/conf/che.properties
  | pmcd: cannot open log "/dev/no-such-file" for writing : Permission denied
  | Log for pmcd on che-1-f746h started Thu Aug 17 03:15:10 2017
  |  
  |  
  | active agent dom   pid  in out ver protocol parameters
  | ============ === ===== === === === ======== ==========
  | pmcd           2                 2 dso i:6  lib=/var/lib/pcp/pmdas/pmcd/pmda_pmcd.so entry=pmcd_init [0x7f547d5b4060]
  | proc           3                 2 dso i:6  lib=/var/lib/pcp/pmdas/proc/pmda_proc.so entry=proc_init [0x7f547d392d60]
  | linux         60                 2 dso i:6  lib=/var/lib/pcp/pmdas/linux/pmda_linux.so entry=linux_init [0x7f547d161b90]
  |  
  | Host access list empty: host-based access control turned off
  | User access list empty: user-based access control turned off
  | Group access list empty: group-based access control turned off
  |  
  |  
  | pmcd: PID = 34, PDU version = 2
  | pmcd request port(s):
  | sts fd   port  family address
  | === ==== ===== ====== =======
  | ok     5       unix   /var/run/pcp/pmcd.socket
  | ok     3 44321 inet   INADDR_ANY
  | ok     4 44321 ipv6   INADDR_ANY
  | 2017-08-17 03:15:12,094[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.5.11
  | 2017-08-17 03:15:12,114[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Jan 10 2017 21:02:52 UTC
  | 2017-08-17 03:15:12,114[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.5.11.0
  | 2017-08-17 03:15:12,114[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
  | 2017-08-17 03:15:12,114[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-514.25.2.el7.x86_64
  | 2017-08-17 03:15:12,115[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
  | 2017-08-17 03:15:12,115[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre
  | 2017-08-17 03:15:12,115[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_141-b16
  | 2017-08-17 03:15:12,116[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
  | 2017-08-17 03:15:12,116[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat
  | 2017-08-17 03:15:12,116[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat
  | 2017-08-17 03:15:12,117[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dnop
  | 2017-08-17 03:15:12,117[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
  | 2017-08-17 03:15:12,117[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseG1GC
  | 2017-08-17 03:15:12,118[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseStringDeduplication
  | 2017-08-17 03:15:12,119[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MinHeapFreeRatio=20
  | 2017-08-17 03:15:12,119[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxHeapFreeRatio=40
  | 2017-08-17 03:15:12,119[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxRAM=700m
  | 2017-08-17 03:15:12,120[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
  | 2017-08-17 03:15:12,120[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.docker.network=bridge
  | 2017-08-17 03:15:12,120[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
  | 2017-08-17 03:15:12,120[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT
  | 2017-08-17 03:15:12,121[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/data/logs
  | 2017-08-17 03:15:12,121[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
  | 2017-08-17 03:15:12,121[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djuli-logback.configurationFile=file:/home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat/conf/tomcat-logger.xml
  | 2017-08-17 03:15:12,121[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
  | 2017-08-17 03:15:12,122[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
  | 2017-08-17 03:15:12,122[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
  | 2017-08-17 03:15:12,122[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
  | 2017-08-17 03:15:12,123[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
  | 2017-08-17 03:15:12,123[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/data/conf
  | 2017-08-17 03:15:12,123[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat
  | 2017-08-17 03:15:12,124[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat
  | 2017-08-17 03:15:12,124[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat/temp
  | 2017-08-17 03:15:12,312[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 525]  - Initializing ProtocolHandler ["http-nio-8080"]
  | 2017-08-17 03:15:12,401[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 67]   - Using a shared selector for servlet write/read
  | 2017-08-17 03:15:12,404[main]             [INFO ] [o.a.catalina.startup.Catalina 617]   - Initialization processed in 1173 ms
  | 2017-08-17 03:15:12,500[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 336]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for the Platform server
  | 2017-08-17 03:15:12,501[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service Catalina
  | 2017-08-17 03:15:12,501[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.11
  | 2017-08-17 03:15:22,532[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat/webapps/ROOT.war
  | Aug 17, 2017 3:15:32 AM org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve keycloakInit
  | INFO: Using com.redhat.che.keycloak.shared.ApplicationKeycloakConfigResolver to resolve Keycloak configuration on a per-request basis.
  | 2017-08-17 03:15:32,817[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat/webapps/ROOT.war has finished in 10,283 ms
  | 2017-08-17 03:15:32,820[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat/webapps/dashboard.war
  | 2017-08-17 03:15:38,769[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat/webapps/dashboard.war has finished in 5,949 ms
  | 2017-08-17 03:15:38,772[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat/webapps/wsmaster.war
  | 2017-08-17 03:15:51,239[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
  | 2017-08-17 03:15:51,419[ost-startStop-1]  [INFO ] [o.f.c.i.util.VersionPrinter 44]      - Flyway 4.0.3 by Boxfuse
  | 2017-08-17 03:15:51,421[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
  | 2017-08-17 03:15:51,520[ost-startStop-1]  [INFO ] [i.f.CustomSqlMigrationResolver 153]  - Searching for sql scripts in locations [classpath:che-schema]
  | 2017-08-17 03:15:51,611[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbValidate 44]       - Successfully validated 11 migrations (execution time 00:00.093s)
  | 2017-08-17 03:15:51,707[ost-startStop-1]  [INFO ] [o.f.c.i.m.MetaDataTableImpl 44]      - Creating Metadata table: "PUBLIC"."schema_version"
  | 2017-08-17 03:15:51,807[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Current version of schema "PUBLIC": << Empty Schema >>
  | 2017-08-17 03:15:51,822[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.0.0.8.1 - 1__init.sql
  | 2017-08-17 03:15:52,432[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.0.0.9.1 - 1__add_index_on_workspace_temporary.sql
  | 2017-08-17 03:15:52,510[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.0.0.9.2 - 2__update_local_links_in_environments.sql
  | 2017-08-17 03:15:52,542[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.2.0.1 - 1__increase_project_attributes_values_length.sql
  | 2017-08-17 03:15:52,636[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.4.0.1 - 1__drop_user_to_account_relation.sql
  | 2017-08-17 03:15:52,938[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.4.0.2 - 2__create_missed_account_indexes.sql
  | 2017-08-17 03:15:53,000[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.6.0.1 - 1__add_exec_agent_where_terminal_agent_is_present.sql
  | 2017-08-17 03:15:53,017[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.7.0.1 - 1__add_factory.sql
  | 2017-08-17 03:15:53,160[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.7.0.2 - 2__remove_match_policy.sql
  | 2017-08-17 03:15:53,244[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.8.0.1 - 1__add_foreigh_key_indexes.sql
  | 2017-08-17 03:15:53,318[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.11.0.1 - 1__optimize_user_search.sql
  | 2017-08-17 03:15:53,326[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Successfully applied 11 migrations to schema "PUBLIC" (execution time 00:01.630s).
  | 2017-08-17 03:15:55,906[ost-startStop-1]  [WARN ] [o.e.c.a.w.s.stack.StackLoader 87]    - Reload stacks on start is deprecated policy, and it will be removed soon
  | 2017-08-17 03:15:56,328[ost-startStop-1]  [ERROR] [o.e.c.a.w.s.stack.StackLoader 101]   - Failed to store stacks from 'che-in-che.json'
  | 2017-08-17 03:15:56,330[ost-startStop-1]  [INFO ] [o.e.c.a.w.s.stack.StackLoader 104]   - Stacks initialization finished
  | 2017-08-17 03:15:56,422[ost-startStop-1]  [INFO ] [o.e.c.a.m.s.r.RecipeLoader 75]       - Recipes initialization finished
  | 2017-08-17 03:15:56,501[ost-startStop-1]  [INFO ] [e.c.a.w.s.i.ServerIdleDetector 60]   - Idling che server scheduled [timeout=3600] seconds]
  | 2017-08-17 03:15:56,503[ted-scheduler-1]  [INFO ] [ockerAbandonedResourcesCleaner 124]  - List containers registered in the api: []
  | Aug 17, 2017 3:15:57 AM org.keycloak.adapters.servlet.KeycloakOIDCFilter init
  | INFO: Using com.redhat.che.keycloak.shared.ServicesKeycloakConfigResolver to resolve Keycloak configuration on a per-request basis.
  | 2017-08-17 03:15:57,235[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/eclipse-che-5.17.0-fabric8-SNAPSHOT/tomcat/webapps/wsmaster.war has finished in 18,463 ms
  | 2017-08-17 03:15:57,297[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 570]  - Starting ProtocolHandler [http-nio-8080]
  | 2017-08-17 03:15:57,306[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 44901 ms
  | 2017-08-17 03:16:37,136[nio-8080-exec-3]  [ERROR] [c.r.c.k.s.KeycloakUserChecker 74]    - Exception while calling the user auth endpoint:
  | java.net.NoRouteToHostException: No route to host (Host unreachable)
  | at java.net.PlainSocketImpl.socketConnect(Native Method)
  | at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  | at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  | at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  | at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  | at java.net.Socket.connect(Socket.java:589)
  | at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
  | at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
  | at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
  | at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
  | at sun.net.www.http.HttpClient.New(HttpClient.java:339)
  | at sun.net.www.http.HttpClient.New(HttpClient.java:357)
  | at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
  | at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
  | at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
  | at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
  | at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
  | at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
  | at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
  | at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:248)
  | at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:158)
  | at com.redhat.che.keycloak.server.KeycloakUserChecker$1.load(KeycloakUserChecker.java:70)
  | at com.redhat.che.keycloak.server.KeycloakUserChecker$1.load(KeycloakUserChecker.java:63)
  | at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
  | at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
  | at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
  | at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
  | at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
  | at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
  | at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
  | at com.redhat.che.keycloak.server.KeycloakUserChecker.matchesUsername(KeycloakUserChecker.java:91)
  | at com.redhat.che.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:86)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
  | at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:317)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:574)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)


```

**Comment by amisevsk** [comment]
@ldimaggi I'm assuming this log is coming from a workspace pod?

Are you able to run `echo $CHE_API` in the pod? Also `curl $CHE_API/keycloak/settings`?

**Comment by ldimaggi** [comment]
No values found/returned:

![screenshot from 2017-08-17 09-33-20](https://user-images.githubusercontent.com/642621/29414902-3d3499f4-832f-11e7-9ba6-4599a4b53a3f.png)

**Comment by ldimaggi** [comment]
Note that this problem was seen repeatedly on August 16 - I am not seeing it on August 17.

All tests were performed only after "cleaning" the user account in OSO - and performing a tenant update.

**Comment by joshuawilson** [comment]
@ldimaggi are the tests failing on this? or is it fixed?

**Comment by ldimaggi** [comment]
Closing as not reproducible.

**Comment by ldimaggi** [comment]
It's back - seeing this error again on August 20. 

```
2017-08-20T23:17:24.588388201Z java.net.NoRouteToHostException: No route to host (Host unreachable)
2017-08-20T23:17:24.588395336Z 	at java.net.PlainSocketImpl.socketConnect(Native Method)
2017-08-20T23:17:24.588411217Z 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2017-08-20T23:17:24.588417341Z 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2017-08-20T23:17:24.588421964Z 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2017-08-20T23:17:24.588426414Z 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2017-08-20T23:17:24.588431266Z 	at java.net.Socket.connect(Socket.java:589)
2017-08-20T23:17:24.588436433Z 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
2017-08-20T23:17:24.58844136Z 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
2017-08-20T23:17:24.588446515Z 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
2017-08-20T23:17:24.588451277Z 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
2017-08-20T23:17:24.588456685Z 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
2017-08-20T23:17:24.588461414Z 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
2017-08-20T23:17:24.588465981Z 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
2017-08-20T23:17:24.588470691Z 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
2017-08-20T23:17:24.588475232Z 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
2017-08-20T23:17:24.588480096Z 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
2017-08-20T23:17:24.588501136Z 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
2017-08-20T23:17:24.588507478Z 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
2017-08-20T23:17:24.588511656Z 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
2017-08-20T23:17:24.588516342Z 	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:248)
2017-08-20T23:17:24.588520864Z 	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:158)
2017-08-20T23:17:24.588525471Z 	at com.redhat.che.keycloak.server.KeycloakUserChecker$1.load(KeycloakUserChecker.java:70)
2017-08-20T23:17:24.58852972Z 	at com.redhat.che.keycloak.server.KeycloakUserChecker$1.load(KeycloakUserChecker.java:63)
2017-08-20T23:17:24.588536894Z 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
2017-08-20T23:17:24.588541793Z 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
2017-08-20T23:17:24.588546496Z 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
2017-08-20T23:17:24.588550848Z 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
2017-08-20T23:17:24.588561961Z 	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
2017-08-20T23:17:24.588567529Z 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
2017-08-20T23:17:24.58857219Z 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
2017-08-20T23:17:24.588577161Z 	at com.redhat.che.keycloak.server.KeycloakUserChecker.matchesUsername(KeycloakUserChecker.java:91)
2017-08-20T23:17:24.588581853Z 	at com.redhat.che.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:86)
2017-08-20T23:17:24.588586894Z 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
2017-08-20T23:17:24.588591835Z 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
2017-08-20T23:17:24.588597149Z 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
2017-08-20T23:17:24.58860194Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
2017-08-20T23:17:24.588606677Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
2017-08-20T23:17:24.588611342Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
2017-08-20T23:17:24.588616547Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
2017-08-20T23:17:24.588621131Z 	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:317)
2017-08-20T23:17:24.588625648Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
2017-08-20T23:17:24.588630426Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
2017-08-20T23:17:24.588634887Z 	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
2017-08-20T23:17:24.58863934Z 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
2017-08-20T23:17:24.588643833Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
2017-08-20T23:17:24.588648308Z 	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:574)
2017-08-20T23:17:24.5886528Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
2017-08-20T23:17:24.588658758Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
2017-08-20T23:17:24.588663355Z 	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
2017-08-20T23:17:24.58866756Z 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
2017-08-20T23:17:24.58867222Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
2017-08-20T23:17:24.588676546Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
2017-08-20T23:17:24.588681116Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
2017-08-20T23:17:24.588691016Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
2017-08-20T23:17:24.588696356Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
2017-08-20T23:17:24.588701295Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
2017-08-20T23:17:24.58870621Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2017-08-20T23:17:24.588711157Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2017-08-20T23:17:24.58871545Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2017-08-20T23:17:24.588720046Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2017-08-20T23:17:24.588724734Z 	at java.lang.Thread.run(Thread.java:748)
che-1-l2hth
2017-08-20 23:14:57,198[ost-startStop-1]  [ERROR] [o.e.c.a.w.s.stack.StackLoader 101]   - Failed to store stacks from 'che-in-che.json'
2017-08-20 23:17:24,587[nio-8080-exec-1]  [ERROR] [c.r.c.k.s.KeycloakUserChecker 74]    - Exception while calling the user auth endpoint
```

**Comment by l0rd** [comment]
@ldimaggi it looks like Che could not reach keycloak server. Maybe that was because keycloak was down at that point?

**Comment by ldimaggi** [comment]
This issue has not been seen for weeks - closing.
