### ISSUE TITLE
SEVERE level error ("Unexpected error when retrieving changeset") consistently seen in jenkins pod log when creating new project - seems to not affect project creation

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#632]
This error is logged when a new project is successfully created - there doesn't seem to be any functional impact - but - is this pointing to a functional problem? Thx!

```

INFO: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
  | Aug 21, 2017 6:51:33 PM io.jenkins.blueocean.autofavorite.FavoritingScmListener onCheckout
  | SEVERE: Unexpected error when retrieving changeset
  | hudson.plugins.git.GitException: Error launching git whatchanged
  | at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$6.execute(CliGitAPIImpl.java:907)
  | at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
  | at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
  | at hudson.remoting.UserRequest.perform(UserRequest.java:181)
  | at hudson.remoting.UserRequest.perform(UserRequest.java:52)
  | at hudson.remoting.Request$2.run(Request.java:336)
  | at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at hudson.remoting.Engine$1$1.run(Engine.java:98)
  | at java.lang.Thread.run(Thread.java:745)
  | at ......remote call to JNLP4-connect connection from ip-10-131-2-1.us-east-2.compute.internal/10.131.2.1:57082(Native Method)
  | at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1554)
  | at hudson.remoting.UserResponse.retrieve(UserRequest.java:281)
  | at hudson.remoting.Channel.call(Channel.java:839)
  | at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
  | at com.sun.proxy.$Proxy149.execute(Unknown Source)
  | at io.jenkins.blueocean.autofavorite.FavoritingScmListener.getChangeSet(FavoritingScmListener.java:143)
  | at io.jenkins.blueocean.autofavorite.FavoritingScmListener.onCheckout(FavoritingScmListener.java:73)
  | at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:127)
  | at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
  | at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
  | at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
  | at hudson.security.ACL.impersonate(ACL.java:260)
  | at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:748)
 


```

**Comment by ldimaggi** [comment]
[jenkins_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1239857/jenkins_pod_log.txt)

**Comment by joshuawilson** [comment]
@ldimaggi are you still seeing this?

**Comment by ldimaggi** [comment]
Closing - this problem is no longer being seen.
