### ISSUE TITLE
After failed build, seeing large number of repeated printf statements in Jenkins log

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#655]
Scenario:
* User, with a clean account, creates a new space and attempts to create quickstart
* The build fails - see log below 
* The user restarts the build pipeline, the build is successful

The Jenkins pod log contains a large number of instances of this set of messages:
```
h-4.2$ printf "EXITCODE %3d" $?; exit
EXITCODE   1exit
sh-4.2$ "ps" "-o" "pid=" "21" 
    21
```
What is the meaning/impact of these statements?

**Comment by ldimaggi** [comment]
Failed build log:

```
OpenShift Build ldimaggi/august-1 from https://github.com/ldimaggi/august.git
13:24:59 Connecting to https://api.github.com using ldimaggi/****** (cd-github)
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
Caused: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:460)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:399)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:527)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
	at org.kohsuke.github.Requester.parse(Requester.java:592)
Caused: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/ldimaggi/august
	at org.kohsuke.github.Requester.parse(Requester.java:622)
	at org.kohsuke.github.Requester.parse(Requester.java:620)
	at org.kohsuke.github.Requester.parse(Requester.java:620)
	at org.kohsuke.github.Requester.parse(Requester.java:584)
	at org.kohsuke.github.Requester._to(Requester.java:264)
	at org.kohsuke.github.Requester.to(Requester.java:226)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:420)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:1078)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:564)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:95)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:263)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Finished: FAILURE
```

**Comment by ldimaggi** [comment]
Jenkins pod log attached:

[jenkins_pod_log.txt](https://github.com/openshiftio/openshift.io/files/1249018/jenkins_pod_log.txt)

**Comment by joshuawilson** [comment]
@jstrachan @rawlingsj any ideas?

**Comment by joshuawilson** [comment]
@ldimaggi are you still seeing this?

**Comment by ldimaggi** [comment]
This can be closed - not seeing these messages now.
