### ISSUE TITLE
Failures on stage: HTTP code 500 Internal Server Error is returned  for the stack analysis results

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#659]
_From @tisnik on August 2, 2017 15:10_

The test case with the "standard" requirements.txt sometimes fails with the 500 Internal Server Error. The probability of failure is approximately 4/10 analysis.

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#108_

**Comment by samuzzal-choudhury** [comment]
Observed on staging. StackAggregator task failed which caused this on server -

```
2017-09-11 16:07:45,078 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[31e38041-e3b4-4603-b109-2aa5a5f511f7] raised unexpected: TypeError("Can't convert 'NoneType' object to str implicitly",) 
Traceback (most recent call last): 
File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task 
R = retval = fun(*args, **kwargs) 
File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__ 
return self.run(*args, **kwargs) 
File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 170, in run 
raise self.retry(max_retries=0, exc=exc) 
File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry 
raise_with_context(exc) 
File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 115, in run 
result = task.run(node_args) 
File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 38, in run 
result = self.execute(node_args) 
File "/usr/lib/python3.4/site-packages/f8a_worker/workers/stackaggregator_v2.py", line 220, in execute 
finished = self._get_dependency_data(resolved, ecosystem) 
File "/usr/lib/python3.4/site-packages/f8a_worker/workers/stackaggregator_v2.py", line 185, in _get_dependency_data 
"has('version','"+elem["version"]+"')." \ 
TypeError: Can't convert 'NoneType' object to str implicitly

```

**Comment by samuzzal-choudhury** [comment]
We are dependent on the mercator task for returning resolved versions of the repository. But, that is unable to resolve the version for `click==6.*` currently.

**Comment by jpopelka** [comment]
> We are dependent on the mercator task for returning resolved versions of the repository. But, that is unable to resolve the version for click==6.* currently.

https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/348 should fix it

**Comment by samuzzal-choudhury** [comment]
Closing this as this does not occur any more. Please reopen in case this issue still persists.
