### ISSUE TITLE
Stack analysis failure on stage when the === clause is used to specify component version

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#660]
_From @tisnik on August 1, 2017 14:58_

```click===6.7```

Log messages:

```
2017-08-01 14:50:15,027 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[418d1c6e-34e0-4b0e-b607-5e449630e94a] raised unexpected: ValueError("'===' is not in list",)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 170, in run
    raise self.retry(max_retries=0, exc=exc)
  File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
    raise_with_context(exc)
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 115, in run
    result = task.run(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 38, in run
    result = self.execute(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/workers/graphaggregator.py", line 83, in execute
    out["details"][0]["dependencies"])
  File "/usr/lib/python3.4/site-packages/f8a_worker/workers/graphaggregator.py", line 21, in _handle_external_deps
    versions = solver.solve(deps)
  File "/usr/lib/python3.4/site-packages/f8a_worker/solver.py", line 615, in solve
    for release in releases
  File "/usr/lib/python3.4/site-packages/f8a_worker/solver.py", line 616, in <listcomp>
    if release in dep], key=cmp_to_key(compare_version))
  File "/usr/lib/python3.4/site-packages/f8a_worker/solver.py", line 291, in __contains__
    return self.check(item)
  File "/usr/lib/python3.4/site-packages/f8a_worker/solver.py", line 335, in check
    results |= _compare_spec(spec)
  File "/usr/lib/python3.4/site-packages/f8a_worker/solver.py", line 310, in _compare_spec
    token = Tokens.operators.index(spec[0])
ValueError: '===' is not in list
```

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#104_

**Comment by jpopelka** [comment]
Should be fixed now, closing.
