### ISSUE TITLE
Intermittent issue - unable to access OSO token when creating new codespace

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#717]
Intermittent issue being seen today - when creating a new codespace, the OSO token is treated as invalid.

**Comment by ldimaggi** [comment]
[che-1-log.txt.txt](https://github.com/openshiftio/openshift.io/files/1264976/che-1-log.txt.txt)
```


java.io.IOException: Failed access: https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token?token, method: GET, response code: 400, message: {"errorMessage":"Invalid token."}
--
  | at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:262)
  | at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:152)
  | at com.redhat.che.keycloak.token.provider.service.KeycloakTokenProvider.getResponseBody(KeycloakTokenProvider.java:110)
  | at com.redhat.che.keycloak.token.provider.service.KeycloakTokenProvider.obtainOsoToken(KeycloakTokenProvider.java:91)
  | at com.redhat.che.keycloak.token.provider.util.KeycloakUserValidator$TokenLoader.load(KeycloakUserValidator.java:213)
  | at com.redhat.che.keycloak.token.provider.util.KeycloakUserValidator$TokenLoader.load(KeycloakUserValidator.java:207)
  | at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
  | at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
  | at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
  | at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
  | at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
  | at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
  | at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
  | at com.redhat.che.keycloak.token.provider.util.KeycloakUserValidator.getOpenShiftToken(KeycloakUserValidator.java:157)
  | at com.redhat.che.keycloak.token.provider.util.KeycloakUserValidator.matchesUsername(KeycloakUserValidator.java:113)
  | at com.redhat.che.keycloak.token.provider.contoller.TokenController.getUserMatches(TokenController.java:121)
  | at sun.reflect.GeneratedMethodAccessor226.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
  | at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
  | at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
  | at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
  | at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
  | at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
  | at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
  | at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
  | at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  | at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
  | at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
  | at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
  | at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
  | at org.eclipse.che.api.local.filters.EnvironmentInitializationFilter.doFilter(EnvironmentInitializationFilter.java:53)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:419)
  | at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at com.redhat.che.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:81)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
  | at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:317)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:574)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)


```

**Comment by joshuawilson** [comment]
What do you mean "creating a new codebase"? Through the app wizard?

**Comment by ldimaggi** [comment]
Closing as non reproducible.

The issue had been seen in creatnig a new codebase after creating a new (quickstart) project. Thx!
