### ISSUE TITLE
UI module build failures

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#809]
PR's are not being built, example: https://github.com/fabric8-ui/fabric8-planner/pull/2143

**Comment by joshuawilson** [comment]
cc: @rawlingsj @michaelkleinhenz @nimishamukherjee

**Comment by jstrachan** [comment]
what PR is #809 and where does it live?

**Comment by maxandersen** [comment]
sorry, bad copy/paste - updated it to https://github.com/fabric8-ui/fabric8-planner/pull/2143 and @rawlingsj said he was looking at it. Assigned it to you (@jstrachan) by mistake - sorry :)

**Comment by joshuawilson** [comment]
@rawlingsj this PRs are failing for me and I don't know why.
https://github.com/fabric8-ui/ngx-login-client/pull/63

**Comment by rawlingsj** [comment]
> PRs are failing for me and I don't know why.

Did you look at the CI build log that is linked to the failure of the issue you referenced?  Click the 'Details' link to the right of the red cross
<img width="715" alt="screenshot 2017-09-14 09 21 10" src="https://user-images.githubusercontent.com/1457180/30419403-1a8083e0-992e-11e7-9226-673b291b7bba.png">

That takes you to the log which explains why it is failing:

```

hudson.plugins.git.GitException: Command "git merge 59de6e301c0b70d71bd0cdd2e0328ac77957b17c" returned status code 1:
stdout: Auto-merging package.json
CONFLICT (content): Merge conflict in package.json
Automatic merge failed; fix conflicts and then commit the result.

stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1892)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1888)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1533)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$3.execute(CliGitAPIImpl.java:642)
	at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:122)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1023)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1116)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:130)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:120)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:263)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)

```

**Comment by joshuawilson** [comment]
@rawlingsj I missed that, thanks. I'll look into it.

**Comment by rawlingsj** [comment]
Subsequent commits to an open PR will now trigger build jobs again.  Fix in commit above and it's now rolled out to our GKE cluster.
