### ISSUE TITLE
Intermittent/recurring error - OSIO fails to create Che workspace due to 500 error from keycloak when trying to obtain OSO token

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#824]
Started seeing this error frequently today - steps to recreate:
* Reset user environment
* Create new space
* Create new quickstart project
* Attempt to create new code base

User is presented with this error:

![screenshot from 2017-09-15 10-19-13](https://user-images.githubusercontent.com/642621/30486708-5bac6dbc-99ff-11e7-9c88-300c354da6b2.png)

Che pod log (see attached) reports this error:
[che_log.txt](https://github.com/openshiftio/openshift.io/files/1306598/che_log.txt)

```

2017-09-15 14:11:27,719[nio-8080-exec-1]  [ERROR] [.k.t.p.u.KeycloakUserValidator 221]  - Exception while obtaining OSO token:
--
  | java.io.IOException: Failed access: https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token?token, method: GET, response code: 500, message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">;
  | <html xmlns="http://www.w3.org/1999/xhtml" class="login-pf">
  |  
  | <head>
  | <meta charset="utf-8">
  | <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  | <meta name="robots" content="noindex, nofollow">
  |  
  | <meta name="viewport" content="width=device-width,initial-scale=1"/>
  | <title>        We're sorry...
  | </title>
  | <link rel="icon" href="/auth/resources/3.2.0.final/login/keycloak/img/favicon.ico" />
  | <link href="/auth/resources/3.2.0.final/login/keycloak/lib/patternfly/css/patternfly.css" rel="stylesheet" />
  | <link href="/auth/resources/3.2.0.final/login/keycloak/lib/zocial/zocial.css" rel="stylesheet" />
  | <link href="/auth/resources/3.2.0.final/login/keycloak/css/login.css" rel="stylesheet" />
  | </head>
  |  
  | <body class="">
  | <div id="kc-logo"><a href="http://www.keycloak.org"><div id="kc-logo-wrapper"></div></a></div>
  |  
  | <div id="kc-container" class="">
  | <div id="kc-container-wrapper" class="">
  |  
  | <div id="kc-header" class="col-xs-12 col-sm-8 col-md-8 col-lg-7">
  | <div id="kc-header-wrapper" class="">        We're <strong>sorry</strong> ...
  | </div>
  | </div>
  |  
  |  
  | <div id="kc-content" class="col-sm-12 col-md-12 col-lg-12 container">
  | <div id="kc-content-wrapper" class="row">
  |  
  |  
  | <div id="kc-form" class="col-xs-12 col-sm-8 col-md-8 col-lg-7 login">
  | <div id="kc-form-wrapper" class="">
  | <div id="kc-error-message">
  | <p class="instruction">Unexpected error when retrieving token from identity provider.</p>
  | </div>
  | </div>
  | </div>
  |  
  | </div>
  | </div>
  | </div>
  | </div>
  | </body>
  | </html>
  |  
  | at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:262)
  | at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:152)
  | at com.redhat.che.keycloak.token.provider.service.KeycloakTokenProvider.getResponseBody(KeycloakTokenProvider.java:110)
  | at com.redhat.che.keycloak.token.provider.service.KeycloakTokenProvider.obtainOsoToken(KeycloakTokenProvider.java:91)
  | at com.redhat.che.keycloak.token.provider.util.KeycloakUserValidator$TokenLoader.load(KeycloakUserValidator.java:213)
  | at com.redhat.che.keycloak.token.provider.util.KeycloakUserValidator$TokenLoader.load(KeycloakUserValidator.java:207)
  | at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
  | at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
  | at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
  | at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
  | at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
  | at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
  | at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
  | at com.redhat.che.keycloak.token.provider.util.KeycloakUserValidator.getOpenShiftToken(KeycloakUserValidator.java:157)
  | at com.redhat.che.keycloak.token.provider.util.KeycloakUserValidator.matchesUsername(KeycloakUserValidator.java:113)
  | at com.redhat.che.keycloak.token.provider.contoller.TokenController.getUserMatches(TokenController.java:121)
  | at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
  | at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
  | at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
  | at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
  | at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
  | at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
  | at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
  | at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
  | at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  | at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
  | at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
  | at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
  | at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
  | at org.eclipse.che.api.local.filters.EnvironmentInitializationFilter.doFilter(EnvironmentInitializationFilter.java:53)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:419)
  | at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at com.redhat.che.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:81)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
  | at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:317)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:574)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)
```

**Comment by ibuziuk** [comment]
`Failed access: https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token?token  method: GET, response code: 500`
@alexeykazakov looks like keycloak problem ?

**Comment by alexeykazakov** [comment]
I don't see any problem with `https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token`
Make sure you pass an access token in this request.
If the token is an empty string it will cause 500.
And btw the correct url is `https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token` not `https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token?token`. But the extra "token" param should not cause failure. It's ignored.

**Comment by ibuziuk** [comment]
@alexeykazakov the issue is defined as `Intermittent/recurring`, is it possible to check some logs on keycloak side to figure out what might have happened?

`If the token is an empty string it will cause 500.`
Quite weird status code, I would expect 400

**Comment by ibuziuk** [comment]
Just checker some code in rh-che - `KeycloakUserValidator` has not been changed for a couple of month and it only retrieves oso token based on keycloak one. So, I am pretty sure the problem is not on che side

**Comment by alexeykazakov** [comment]
> Quite weird status code, I would expect 400

I would expect 400 too :)

**Comment by ibuziuk** [comment]
Was not able to reproduce. Double checked cm value set by init tenant script - all looks good:
![image](https://user-images.githubusercontent.com/1461122/30496904-2af64d08-9a51-11e7-9cb4-a500db14ca3d.png)
@ldimaggi look like it is coupled with some  keycloak outage

>Unexpected error when retrieving token from identity provider

When workspace is failing to start with this problem could you please paste js logs. Maybe there would be also some keycloak related traces (e.g 403 forbidden)

**Comment by ldimaggi** [comment]
[che_log.txt](https://github.com/openshiftio/openshift.io/files/1307515/che_log.txt)

**Comment by l0rd** [comment]
@alexeykazakov I've been looking to add some information in the logs but taking aside the token there is not much to add. 

With these informations:

- the HTTP error code (`500`)
- the error timestamp (`2017-09-15 14:11:27`)
- the user for whom KC returned the error (@ldimaggi)

you may be able to find more details KC side no? What can we add in the che-server logs to help you investigate?

**Comment by joshuawilson** [comment]
@ldimaggi are you still seeing this?

What is the status on this?

**Comment by ldimaggi** [comment]
Will try to recreate this today - in the past, it was seen by multiple users.

**Comment by ldimaggi** [comment]
The "default" error message shown to the user - for example:
Could not start workspace exvke. Reason: Start of environment 'default' failed. Error: Fail launching agent Exec. Workspace ID:workspacesxld5z75b2ajcbrg

Is showing up again yesterday and today.

The error written to the Che pod log this time does not refer to a token issue:



```

2017-09-29 11:25:03,828[aceSharedPool-4]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.terminal' agent at workspace workspacesxld5z75b2ajcbrg
--
  | 2017-09-29 11:25:11,240[aceSharedPool-4]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.exec' agent at workspace workspacesxld5z75b2ajcbrg
  | 2017-09-29 11:25:11,295[AgentLauncher-4]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread AgentLauncher-4. Message: null
  | java.lang.NullPointerException: null
  | at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.startExec(OpenShiftConnector.java:1057)
  | at org.eclipse.che.plugin.docker.machine.DockerProcess.start(DockerProcess.java:118)
  | at org.eclipse.che.api.agent.server.launcher.AbstractAgentLauncher.lambda$start$0(AbstractAgentLauncher.java:137)
  | at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | 2017-09-29 11:27:13,502[aceSharedPool-4]  [ERROR] [.a.a.s.l.AbstractAgentLauncher 100]  - Fail launching agent 'Exec' in 'workspacesxld5z75b2ajcbrg' workspace due to timeout
  | 2017-09-29 11:27:16,354[aceSharedPool-4]  [ERROR] [.a.a.s.l.AbstractAgentLauncher 166]  - An error occurs while starting 'Exec' agent in 'workspacesxld5z75b2ajcbrg' workspace in 'machine3677emqhh7io6aib' machine on 'localhost' node. The agent didn't produce any logs.
  | 2017-09-29 11:27:16,618[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route codeserver-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:16,675[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route exec-agent-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:16,685[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route server-22-tcp-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:16,693[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route server-4403-tcp-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:16,707[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route terminal-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:16,715[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route tomcat8-debug-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:16,726[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route vertx-debug-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:16,737[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route vertx-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:16,746[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route wsagent-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:16,763[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 62]   - Removing OpenShift Service che-ws-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:16,803[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 67]   - Removing OpenShift Deployment che-ws-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:17,001[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 72]   - Removing OpenShift ReplicaSets for deployment che-ws-sxld5z75b2ajcbrg
  | 2017-09-29 11:27:17,288[aceSharedPool-4]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 677]    - Workspace 'che/exvke' can't be started because: Fail launching agent Exec. Workspace ID:workspacesxld5z75b2ajcbrg


```

**Comment by l0rd** [comment]
@ldimaggi this new exception is related to a timeout when starting a process (the so called exec agent). Since it's not related to keycloak we could open a new issue to track that. What do you think? 

And it would be nice if you could add more details: 
- What Che version where you running? 
- How can I try to reproduce it (what's the che-stack, the git repo)? 
- Have you spotted any error in the dev console of the workspace? 
- Can you post the full log of the che pod?

**Comment by ldimaggi** [comment]
See the new issue - https://github.com/openshiftio/openshift.io/issues/1041

Thx!

**Comment by joshuawilson** [comment]
Is this fixed or is someone working on it?

**Comment by ibuziuk** [comment]
@@ldimaggi is it still reproducible ?

**Comment by ldimaggi** [comment]
This problem seems to be solved - closing the issue - thx!
