### ISSUE TITLE
Intermittent but recurring problem - codebase not populated with project code

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#882]
_From @ldimaggi on July 5, 2017 14:1_

Seeing this problem intermittently - no repeatable pattern seen yet - sometimes, when a new project is created, creating a codebase does not populate the codebase with the project's code:

![screenshot from 2017-07-03 14-20-20](https://user-images.githubusercontent.com/642621/27867814-ca8b9d5e-6168-11e7-9c4c-117111ece804.png)

Assigning to ldimaggi until a repeatable pattern can be identified.

_Copied from original issue: fabric8-ui/fabric8-ui#1635_

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 8, 2017 12:42_

Another example - created 3 new projects - and attempted to create workspaces for each project - only 1 workspace was populated with project code:

![screenshot from 2017-07-08 08-40-50](https://user-images.githubusercontent.com/642621/27985467-5bc9098a-63b9-11e7-836b-e65d79ae7d13.png)

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 8, 2017 12:48_

Error logged to Che when one of the workspaces missing project code was created:

```
2017-07-08 03:46:21,408[nio-8080-exec-4]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 892]    - Workspace 'che/mtou9hc8' with id 'workspaceh1nux4dczfj0x4ia' created by user 'che'
https://che-osiotest314-che.8a09.starter-us-east-2.openshiftapps.com/wsmaster/api/workspace/workspacezjbiz2msdpnrup2i/check status : 200
https://che-osiotest314-che.8a09.starter-us-east-2.openshiftapps.com/wsmaster/api/workspace status : 201
https://che-osiotest314-che.8a09.starter-us-east-2.openshiftapps.com/wsmaster/api/oauth/token status : 405
https://che-osiotest314-che.8a09.starter-us-east-2.openshiftapps.com/wsmaster/api/token/github status : 204
2017-07-08 03:46:21,954[nio-8080-exec-5]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2017-07-08 03:46:21
java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:459) ~[na:1.8.0_131]
	at java.util.Hashtable.putAll(Hashtable.java:523) ~[na:1.8.0_131]
	at org.eclipse.persistence.indirection.IndirectMap.putAll(IndirectMap.java:631) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.persistence.indirection.IndirectMap.putAll(IndirectMap.java:631) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]
	at org.eclipse.che.api.user.server.PreferenceManager.update(PreferenceManager.java:90) ~[che-core-api-user-5.6.0-openshift-connector-SNAPSHOT.jar:5.6.0-openshift-connector-SNAPSHOT]
	at org.eclipse.che.api.user.server.PreferencesService.update(PreferencesService.java:102) ~[che-core-api-user-5.6.0-openshift-connector-SNAPSHOT.jar:5.6.0-openshift-connector-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140) ~[everrest-core-1.13.3.jar:na]
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60) ~[everrest-core-1.13.3.jar:na]
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306) ~[everrest-core-1.13.3.jar:na]
	at org.everrest.core.impl.RequestDispatcher.invokeResourceMethod(RequestDispatcher.java:268) ~[everrest-core-1.13.3.jar:na]
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:198) ~[everrest-core-1.13.3.jar:na]
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128) ~[everrest-core-1.13.3.jar:na]
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62) ~[everrest-core-1.13.3.jar:na]
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120) [everrest-core-1.13.3.jar:na]
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61) [everrest-core-1.13.3.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
	at org.eclipse.che.api.local.filters.EnvironmentInitializationFilter.doFilter(EnvironmentInitializationFilter.java:54) [wsmaster-local-5.6.0-openshift-connector-SNAPSHOT.jar:5.6.0-openshift-connector-SNAPSHOT]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:436) [catalina.jar:8.0.38]
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177) [catalina.jar:8.0.38]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
	at org.keycloak.adapters.servlet.KeycloakOIDCFilter.doFilter(KeycloakOIDCFilter.java:179) [keycloak-servlet-filter-adapter-2.5.0.Final.jar:2.5.0.Final]
	at com.redhat.che.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:28) [che-keycloak-plugin-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.38]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.38]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.38]
	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:305) [catalina.jar:8.0.38]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.38]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.38]
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) [catalina.jar:8.0.38]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.38]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) [catalina.jar:8.0.38]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100) [tomcat-coyote.jar:8.0.38]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687) [tomcat-coyote.jar:8.0.38]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) [tomcat-coyote.jar:8.0.38]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) [tomcat-coyote.jar:8.0.38]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.38]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
https://che-osiotest314-che.8a09.starter-us-east-2.openshiftapps.com/wsmaster/api/preferences status : 500
https://che-osiotest314-che.8a09.starter-us-east-2.openshiftapps.com/wsmaster/api/workspace status : 200
https://che-osiotest314-che.8a09.starter-us-east-2.openshiftapps.com/wsmaster/api/workspace/workspacezjbiz2msdpnrup2i/runtime status : 204
```
[che_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1132970/che_log.txt)

**Comment by joshuawilson** [comment]
_From @ldimaggi on July 8, 2017 18:8_

Another example - 4 new projects created:

![screenshot from 2017-07-08 14-07-26](https://user-images.githubusercontent.com/642621/27988049-e14093da-63e6-11e7-9198-e0db5cdeb280.png)

**Comment by l0rd** [comment]
This should be fixed now. @ldimaggi have you been able to reproduce it recently?

**Comment by ldimaggi** [comment]
We can close this issue - it is no longer being seen.
